#!/bin/bash
#
# Short:    App Policy Script - Setup prefs for an app from an apps Content dir.
# Author:   Mark J Swift
# Version:  3.2.0
# Modified: 12-Nov-2020
#
# Triggered by the following events:
#   App-WillLaunch (as user)
#
# Called as follows:    
#   App-PrefsPrimer <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST="Usr-AppPrefsPrimer"

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

if [ -z "${GLB_SV_CONSOLEUSERHOMEDIRPATH}" ]
then
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - user home is not defined"
  # Exit if the user home is undefined
else
  if [ ! -e "${GLB_SV_CONSOLEUSERHOMEDIRPATH}" ]
  then
    # Exit if the user home does not exist
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - user home '${GLB_SV_CONSOLEUSERHOMEDIRPATH}' does not exist"
  else
  
# ---

case ${GLB_SV_EVENTNAME} in
    
App-WillLaunch)  
  sv_MasterPrefsDirPath="${GLB_SV_LAUNCHEDAPPFILEPATH}/Contents/Resources/${GLB_SV_POLICYNAME}/${GLB_SV_HOSTNAME}/Library/"
  if ! test -e "${sv_MasterPrefsDirPath}"
  then
    sv_MasterPrefsDirPath="${GLB_SV_LAUNCHEDAPPFILEPATH}/Contents/Resources/${GLB_SV_POLICYNAME}/General/Library/"
  fi
  sv_MasterPrefsFilePath="${sv_MasterPrefsDirPath}Preferences/${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}.plist"
  if test -f "${sv_MasterPrefsFilePath}"
  then
    bv_CopyPrefs=${GLB_BC_TRUE}
    sv_MasterPrefsFileID="$(GLB_SF_GETPLISTPROPERTY "${sv_MasterPrefsFilePath}" ":${GLB_SV_POLICYNAME}")"
    sv_RunningPrefsDirPath="${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/"
    sv_RunningPrefsFilePath="${sv_RunningPrefsDirPath}Preferences/${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}.plist"
    if test -f "${sv_RunningPrefsFilePath}"
    then
      sv_RunningPrefsFileID="$(GLB_SF_GETPLISTPROPERTY "${sv_RunningPrefsFilePath}" ":${GLB_SV_POLICYNAME}")"
      if [ "${sv_MasterPrefsFileID}" = "${sv_RunningPrefsFileID}" ]
      then
        bv_CopyPrefs=${GLB_BC_FALSE}
      fi
    fi
    if [ "${bv_CopyPrefs}" = ${GLB_BC_TRUE} ]
    then
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Copying master prefs to user prefs folder"
      
      # Quit App
      kill ${GLB_IV_LAUNCHEDAPPPROCESSID}
      
      # Copy prefs
      while read sv_MasterPrefFilePath
      do
        sv_RunningPrefFilePath=$(echo "${sv_MasterPrefFilePath}" | sed "s|^${sv_MasterPrefsDirPath}|${sv_RunningPrefsDirPath}|")
        if test -d "${sv_RunningPrefFilePath}"
        then
          mkdir -p "${sv_RunningPrefFilePath}"
        else
          cp "${sv_MasterPrefFilePath}" "${sv_RunningPrefFilePath}"
        fi
      done < <(find "${sv_MasterPrefsFilePath}")

      # Re-launch App
      /usr/bin/open -b "${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}"
    fi
  fi
  ;;

Usr-PolicyInstall|Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---
  
  fi
fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
