#!/bin/bash
#
# Short:    App Policy script - Shows a hint when a specified application opened
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   App-DidLaunch (as user)
#
# Called as follows:    
#   App-ShowHints <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST="Usr-AppShowHints"

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

case ${GLB_SV_EVENTNAME} in
    
App-DidLaunch)
  bv_HintWasShown=${GLB_BC_FALSE}
  iv_HintCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint")"
  for (( iv_LoopCount=0; iv_LoopCount<${iv_HintCount}; iv_LoopCount++ ))
  do
    sv_ListedAppBundleIdentifier="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint:${iv_LoopCount}:ApplicationBundleIdentifier")"
    if [ "${sv_ListedAppBundleIdentifier}" = "${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}" ]
    then

      # Get message content
      sv_HintContent="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint:${iv_LoopCount}:MessageContent")"

      if test -n "${sv_HintContent}"
      then
        # Substitute APPNAME in the title and content with the actual Application name
        sv_HintContent="$(echo "${sv_HintContent}" | sed "s|APPNAME|${GLB_SV_LAUNCHEDAPPNAME}|")"

        bv_ShowHint=${GLB_BC_TRUE}

        # Optional IsAdmin
        if [ "${bv_ShowHint}" = ${GLB_BC_TRUE} ]
        then
          bv_IsAdmin="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint:${iv_LoopCount}:IsAdmin")"
          if test -n "${bv_IsAdmin}"
          then
            if [ "${bv_IsAdmin}" != "${GLB_BV_CONSOLEUSERISADMIN}" ]
            then
              bv_ShowHint=${GLB_BC_FALSE}
            fi
          fi
        fi

        # Optional IsLocalAccount
        if [ "${bv_ShowHint}" = ${GLB_BC_TRUE} ]
        then
          bv_IsLocalAccount="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint:${iv_LoopCount}:IsLocalAccount")"
          if test -n "${bv_IsLocalAccount}"
          then
            if [ "${bv_IsLocalAccount}" != "${GLB_BV_CONSOLEUSERISLOCAL}" ]
            then
              bv_ShowHint=${GLB_BC_FALSE}
            fi
          fi
        fi

        # Optional IsLocalHome
        if [ "${bv_ShowHint}" = ${GLB_BC_TRUE} ]
        then
          bv_IsLocalHome="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHint:${iv_LoopCount}:IsLocalHome")"
          if test -n "${bv_IsLocalHome}"
          then
            if [ "${bv_IsLocalHome}" != "${GLB_BV_CONSOLEUSERHOMEISLOCAL}" ]
            then
              bv_ShowHint=${GLB_BC_FALSE}
            fi
          fi
        fi

        # Display the Message
        if [ "${bv_ShowHint}" = ${GLB_BC_TRUE} ]
        then
          GLB_NF_SHOWNOTIFICATION ${GLB_IC_MSGLEVELNOTICE} "${sv_HintContent}"
        
          bv_HintWasShown=${GLB_BC_TRUE}
        fi
      fi
    fi
    
  done
  
  if [ "${bv_HintWasShown}" = ${GLB_BC_FALSE} ]
  then
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "There are no hints for the application '${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}'"
  fi

  ;;

Usr-PolicyInstall|Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
