#!/bin/bash
#
# Short:    Policy script - Turns wireless on or off, and defines whether non-admins can change the wireless state
# Author:   Mark J Swift
# Version:  3.2.0
# Modified: 12-Nov-2020
#
# Triggered by the following events:
#   Sys-Boot (as root)
#
# Called as follows:    
#   Sys-WirelessSetState <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST="Sys-WiFiControl"

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

if [ -z "${GLB_SV_WIFIINTERFACEDEVICE}" ]
then
  # Exit if there is no wi-fi hardware
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - There is no Wi-Fi hardware (thats odd)"
else

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-Boot|Sys-PolicyInstall)
  sv_WirelessState="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:WirelessState")"

  if test -n "${sv_WirelessState}"
  then
    # Turn Wi-Fi port on or off
    networksetup -setairportpower ${GLB_SV_WIFIINTERFACEDEVICE} ${sv_WirelessState}

    bv_RequireAdminIBSS="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:RequireAdminIBSS")"
    if [ "${bv_RequireAdminIBSS}" = ${GLB_BC_TRUE} ]
    then
      sv_YesNoAdminIBSS="YES"
    else
      sv_YesNoAdminIBSS="NO"
    fi
      
    bv_RequireAdminNetworkChange="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:RequireAdminNetworkChange")"
    if [ "${bv_RequireAdminNetworkChange}" = ${GLB_BC_TRUE} ]
    then
      sv_YesNoAdminNetworkChange="YES"
    else
      sv_YesNoAdminNetworkChange="NO"
    fi
      
    bv_RequireAdminPowerToggle="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:RequireAdminPowerToggle")"
    if [ "${bv_RequireAdminPowerToggle}" = ${GLB_BC_TRUE} ]
    then
      sv_YesNoAdminPowerToggle="YES"
    else
      sv_YesNoAdminPowerToggle="NO"
    fi
      
    # Set the Wi-Fi options
    /usr/libexec/airportd prefs RequireAdminIBSS="${sv_YesNoAdminIBSS}" RequireAdminNetworkChange="${sv_YesNoAdminNetworkChange}" RequireAdminPowerToggle="${sv_YesNoAdminPowerToggle}"
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Setting Wi-Fi options to RequireAdminIBSS=${sv_YesNoAdminIBSS} RequireAdminNetworkChange=${sv_YesNoAdminNetworkChange} RequireAdminPowerToggle=${sv_YesNoAdminPowerToggle}"
  fi
  ;;

Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
