#!/bin/bash
#
# Short:    Sys Policy script - Will reboot if the workstation is at the LoginWindow and the system detects that there is a network drive mounted
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Sys-LoginWindow (as root)
#
# Called as follows:    
#   Sys-RestartIfNetMount <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-LoginWindow)
  if [ -z "$(mount | grep "mounted by")" ]
  then
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "There are no network shares mounted - so no need to restart."
    
  else
    # Restart if there are any mounted network volumes
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Network shares are mounted - we need to restart."
    GLB_NF_NAMEDFLAGCREATE "Restart"
    
  fi
  ;;

Sys-PolicyInstall|Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
