#!/bin/bash
#
# Short:    Sys Policy script - Remove unknown wireless SSIDs and passwords
# Author:   Mark J Swift
# Version:  3.2.0
# Modified: 12-Nov-2020
#
# Triggered by the following events:
#   Sys-Boot (as root)
#
# Called as follows:    
#   Sys-WirelessRemoveUnknownSSIDs <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST="Sys-WiFiControl"

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

if [ -z "${GLB_SV_WIFIINTERFACEDEVICE}" ]
then
  # Exit if there is no wi-fi hardware
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - There is no Wi-Fi hardware (thats odd)"
else

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-Boot|Sys-PolicyInstall)
  # Run through all the installed SSIDs
  while read sv_SSIDName
  do
    # Check the known list of SSIDs
    if test -z "$(/usr/libexec/PlistBuddy 2>&1 -c "Print ':${GLB_SV_CONFIGUUID}:Config:KnownSSIDs'" "${GLB_SV_CONFIGFILEPATH}" | grep -v "{" | grep -v "}" | sed "s|^[ ]*||;s|[ ]*$||" | grep -E "^${sv_SSIDName}$")"
    then
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Removing SSID '${sv_SSIDName}' and password from preferred networks on ${GLB_SV_WIFIINTERFACEDEVICE}"

      # The SSID is not in the list, so we need to remove it  
      networksetup -removepreferredwirelessnetwork "${GLB_SV_WIFIINTERFACEDEVICE}" "${sv_SSIDName}"

      # Note to self - at the moment, deleting an entry is still possible when a keychain is locked
      security delete-generic-password -D "AirPort network password" -l "${sv_SSIDName}" /Library/Keychains/System.keychain
    fi
      
  done < <(networksetup -listpreferredwirelessnetworks "${GLB_SV_WIFIINTERFACEDEVICE}" | tr -d "\t" | grep -v "^Preferred networks on" | grep -v "No preferred networks")
  ;;

Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
