#!/bin/bash
#
# Short:    Sys Policy script - Give certain processes access through proxy using AD workstation credentials
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Sys-Boot            (as root)
#
# Called as follows:    
#   Sys-ADTrustAccountProxyAccess <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

nf_RemoveADTrustAccountProxyAccess() # protocol (eg 'http' 'htps' 'ftp') server (eg yourproxy.your.domain) port (eg 8080)
{
  local iv_ProxyPort
  local sv_AllowAccessDirPathList
  local sv_Label
  local sv_ProxyProtocol
  local sv_ProxyAddress
  local sv_Toption
  local iv_LegacyCount

  sv_ProxyProtocol="${1}"
  sv_ProxyAddress="${2}"
  iv_ProxyPort="${3}"
  sv_AllowAccessDirPathList="${4}"
  
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Removing access through proxy ${sv_ProxyProtocol}://${sv_ProxyAddress}:${iv_ProxyPort}."
  
  # Remove entry
  sv_Label="${sv_ProxyProtocol}_${sv_ProxyAddress}_${iv_ProxyPort}_${GLB_SV_CONFIGUUID}"
  
  # We delay removing the password until the next SYS-BOOT

  # Add the password label to the Policies Global Prefs legacy array - if there is no active policy the password will never be removed
  iv_LegacyCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy")"
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy:${iv_LegacyCount}" "${sv_Label}"
}

nf_GiveADTrustAccountProxyAccess() # protocol (eg 'http' 'htps' 'ftp') server (eg yourproxy.your.domain) port (eg 8080) appPath (eg /usr/sbin/ocspd)
{
  local iv_ProxyPort
  local sv_AllowAccessDirPathList
  local sv_Label
  local sv_ProxyProtocol
  local sv_ProxyAddress
  local sv_Toption

  sv_ProxyProtocol="${1}"
  sv_ProxyAddress="${2}"
  iv_ProxyPort="${3}"
  sv_AllowAccessDirPathList="${4}"
  
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Allowing ${sv_AllowAccessDirPathList} through ${sv_ProxyProtocol}://${sv_ProxyAddress}:${iv_ProxyPort}."

  sv_Toption="$(echo "${sv_AllowAccessDirPathList}" | sed "s|^|-T '|;s|$|'|;s|,|' -T '|g")"
  
  sv_Label="${sv_ProxyProtocol}_${sv_ProxyAddress}_${iv_ProxyPort}_${GLB_SV_CONFIGUUID}"

  # Note to self - at the moment, deleting an entry is still possible when a keychain is locked
  security delete-internet-password -l "${sv_Label}" /Library/Keychains/System.keychain

  # Just a little trick to expand the sv_Toption variable, but keep the password quoted (eval wouldnt do)
  /usr/bin/su root <<HEREDOC
  security add-internet-password -U -a "${GLB_SV_ADTRUSTACCOUNTNAME}" -w "${GLB_SV_ADTRUSTACCOUNTPASSWORD}" -l "${sv_Label}" -P "${iv_ProxyPort}" -r "${sv_ProxyProtocol}" -s "${sv_ProxyAddress}" ${sv_Toption} /Library/Keychains/System.keychain
HEREDOC

}

# ---

if [ -z "${GLB_SV_ADDNSDOMAINNAME}" ]
then
  # Exit if the workstation is not bound to AD
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Policy aborted - Computer probably not bound to AD."
else

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-Boot|Sys-PolicyUninstall)

  case ${GLB_SV_EVENTNAME} in
    
  Sys-Boot)
    # We can only remove passwords from the system keychain at boot-time because it eventually gets locked
    iv_LegacyCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy")"
    while [ ${iv_LegacyCount} -ne 0 ]
    do
      iv_LegacyIndex=$((${iv_LegacyCount}-1))
      sv_Label=$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy:${iv_LegacyIndex}")
      
      # Note to self - at the moment, deleting an entry is still possible when a keychain is locked
      security delete-internet-password -l "${sv_Label}" /Library/Keychains/System.keychain
      if [ $? -ne 0 ]
      then
        # Exit if something went wrong when deleting the password
        break
      fi

      GLB_SF_DELETEPLISTPROPERTY "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy:${iv_LegacyIndex}"
      iv_LegacyCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_SHAREDPREFSFILEPATH}" ":${GLB_SV_POLICYNAME}:Shared:Legacy")"
      if [ ${iv_LegacyCount} -ne ${iv_LegacyIndex} ]
      then
        # Exit if deleting an entry did not have the expected result
        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Unexpected result when deleting property ${sv_PropertyName} from ${sv_PlistFilePath}"
        break
      fi
    done    
  esac
  
  # Get the list of processes that have access through the proxy using the workstation name/password
  sv_ProcessList=""
  iv_ProcessCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Process")"
  for (( iv_LoopCount2=0; iv_LoopCount2<${iv_ProcessCount}; iv_LoopCount2++ ))
  do
    sv_ProcessName="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Process:${iv_LoopCount2}")"
    if test -n "${sv_ProcessName}"
    then
      if ! test -f "${sv_ProcessName}"
      then
        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Binary ${sv_ProcessName} does not exist."

      else
        if test -n "${sv_ProcessList}"
        then
          sv_ProcessList="${sv_ProcessList},"
        fi
        sv_ProcessList="${sv_ProcessList}${sv_ProcessName}"
      fi
    fi
  done

  iv_ProxyCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Proxy")"
  for (( iv_LoopCount1=0; iv_LoopCount1<${iv_ProxyCount}; iv_LoopCount1++ ))
  do
    sv_ProxyProtocol="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Proxy:${iv_LoopCount1}:Protocol")"
    if test -n "${sv_ProxyProtocol}"
    then
      sv_ProxyAddress="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Proxy:${iv_LoopCount1}:Address")"
      if test -n "${sv_ProxyAddress}"
      then
        iv_ProxyPort="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Proxy:${iv_LoopCount1}:Port")"
        if test -n "${iv_ProxyPort}"
        then

          case ${GLB_SV_EVENTNAME} in
    
          Sys-Boot)
            # Give certain processes access to through proxy using workstation credentials

            if test -n "${sv_ProcessList}"
            then
              nf_GiveADTrustAccountProxyAccess "${sv_ProxyProtocol}" "${sv_ProxyAddress}" "${iv_ProxyPort}" "${sv_ProcessList}"
            fi
            ;;
            
          Sys-PolicyUninstall)
            nf_RemoveADTrustAccountProxyAccess "${sv_ProxyProtocol}" "${sv_ProxyAddress}" "${iv_ProxyPort}"
            ;;
          
          esac
          
        fi
      fi
    fi
  done
  ;;

Sys-PolicyInstall)
  # We can only activate this policy at boot time when the system keychain is unlocked
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
