#!/bin/bash
#
# Short:    Payload Handler Script - verify that a .LabWarden.plist payload is installed OK
# Author:   Mark J Swift
# Version:  1.0.100
# Modified: 27-Oct-2016
#
# Called as follows:    
#   LabWarden-plist-verify <somefile.LabWarden.plist> [user]
#
# Without a user specified, verifies for the workstation.
# With a user, verifies for the specified user.

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_BuildVersionStampAsString}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.LabWarden.plist"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Users/${sv_GPOuser}"
  
else
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Computers/${LW_sv_ADComputerName}"
  
fi
mkdir -p "${sv_ConfigDirPath}"

# ---

# Verify the LabWarden.plist config

mkdir -p "${sv_ConfigDirPath}"

sv_ObjectName=$(LW_sf_GetPlistProperty "${sv_PayloadFilePath}" ":Name")
sv_ObjectType=$(LW_sf_GetPlistProperty "${sv_PayloadFilePath}" ":Type")
sv_ObjectUUID=$(LW_sf_GetPlistProperty "${sv_PayloadFilePath}" ":UUID")

sv_ConfigEntryName=${sv_ObjectUUID}

if test -n "${sv_ConfigEntryName}"
then
  if test -n "${sv_ObjectName}"
  then
    if test -n "${sv_ObjectType}"
    then
  
      # Check entry
      /usr/libexec/PlistBuddy >/dev/null 2>/dev/null -c "Print ':${sv_ConfigEntryName}'" "${sv_ConfigDirPath}/LabWarden.plist"
      if [ $? -ne 0 ]
      then
        LW_nf_QuickExit "ATTENTION, ${sv_ObjectType} config ${sv_ObjectName} is not installed"

      else

        case "${sv_ObjectType}" in
        Printer)
          # Verify the printer
          sv_PrinterDesc=$(echo $sv_ObjectName | tr " " "_")
          sv_PrinterName=$(echo $sv_PrinterDesc | tr "-" "_")
          if test -z "$(lpstat 2>/dev/null -a | cut -d" " -f1 | grep -E "^${sv_PrinterName}$")"
          then
            LW_nf_QuickExit "ATTENTION, ${sv_ObjectType} config ${sv_ObjectName} is not correctly installed"
        
          else
            LW_nf_logmessage "${sv_ObjectType} config ${sv_ObjectName} is already installed"

          fi
          ;;

        Policy)
          sv_PolicyFilePath="/usr/local/LabWarden/Policies/custom/${sv_ObjectName}"
          if ! test -e "${sv_PolicyFilePath}"
          then
            sv_PolicyFilePath="/usr/local/LabWarden/Policies/${sv_ObjectName}"
            if ! test -e "${sv_PolicyFilePath}"
            then
              sv_PolicyFilePath="/usr/local/LabWarden/Policies/legacy/${sv_ObjectName}"
              if ! test -e "${sv_PolicyFilePath}"
              then
                sv_PolicyFilePath=""
              fi
            fi
          fi
          if test -z "${sv_PolicyFilePath}"
          then
            LW_nf_QuickExit "ATTENTION, there is no handler script for the ${sv_ObjectType} config ${sv_ObjectName}"
        
          else
            LW_nf_logmessage "${sv_ObjectType} config ${sv_ObjectName} is already installed"

          fi
          ;;
  
        esac
        
      fi
    fi
  fi
fi

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

exit 0
