#!/bin/bash
#
# Short:    Payload Handler Script - shrink a .LabWarden.plist payload down to its bare minimum content
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Called as follows:    
#   mobileconfig-install <somefile.mobileconfig>
#
# Outputs the path to the shrunken mobileconfig.

# -- Get some info about this script

# Full source of this script
sv_ThisScriptFilePath="${0}"

# Get dir of this script
sv_ThisScriptDirPath="$(dirname "${sv_ThisScriptFilePath}")"

# Get filename of this script
sv_ThisScriptFileName="$(basename "${sv_ThisScriptFilePath}")"

# Filename without extension
sv_ThisScriptName="$(echo ${sv_ThisScriptFileName} | sed 's|\.[^.]*$||')"

# --

# Get the name of the mobileconfig
sv_ConfigFilePath="${1}"

if test -z "${sv_ConfigFilePath}"
then
  echo "Usage ${sv_ThisScriptFileName} SomeFile.LabWarden.plist"
  exit 0
fi

# Filename of the mobileconfig
sv_DocFileName="$(basename ${sv_ConfigFilePath})"

# Filename without extension
sv_DocName=$(echo ${sv_DocFileName} | sed "s|\.[^.]*$||")

# A place to store the shrunken mobileconfigs
sv_ShrunkDirPath="$(mktemp -dq /tmp/XXXXXXXX)"
cd "${sv_ShrunkDirPath}"

cat "${sv_ConfigFilePath}" | tr -d "\t" | tr -d "\n" > "${sv_ShrunkDirPath}/${sv_DocFileName}"

echo "${sv_ShrunkDirPath}/${sv_DocFileName}"
