#!/bin/bash
#
# Short:    Payload Handler Script - uninstall a .mobileconfig payload
# Author:   Mark J Swift
# Version:  2.0.19
# Modified: 22-Oct-2017
#
# Called as follows:    
#   mobileconfig-uninstall <somefile.mobileconfig> [user]
#
# Without a user specified, uninstalls for the workstation.
# With a user, uninstalls for the specified user.

# ---

sv_CodeVersion="2.0.19"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Common.sh
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  GLB_nf_QuickExit "Usage ${GLB_sv_ThisScriptFileName} somefile.mobileconfig"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  GLB_nf_QuickExit "File not found - ${sv_PayloadFilePath}" ${GLB_iv_MsgLevelWarn}
fi

# ---

sv_GPOuser="${2}"

# ---

# Installing/uninstalling mobileconfigs for other users, is not supported prior to 10.11
# so normal users will have to be able to install/uninstall.
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  if [ ${GLB_iv_SystemVersionStampAsNumber} -lt 168493056 ]
  then
    # MacOS prior to 10.11
    sv_GPOuser=""
  else
    # MacOS 10.11 or later
    exit 0
  fi
fi

# ---

# Uninstall the mobileconfig
if test -n "${sv_GPOuser}"
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Uninstalling config "$(basename ${sv_PayloadFilePath})
  sv_Cmd="/usr/bin/profiles -R -F '${sv_PayloadFilePath}' -U '${sv_GPOuser}'"
  sv_Err=$(/usr/bin/profiles 2>&1 -R -F "${sv_PayloadFilePath}" -U "${sv_GPOuser}")
  iv_Err=$?
    
else
  GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Uninstalling config "$(basename ${sv_PayloadFilePath})
  sv_Cmd="/usr/bin/profiles -R -F '${sv_PayloadFilePath}'"
  sv_Err=$(/usr/bin/profiles 2>&1 -R -F "${sv_PayloadFilePath}")
  iv_Err=$?
  
fi

# Fish the actual error number out from inside the error message
if [ ${iv_Err} -ne 0 ]
then
  iv_ErrNo=$(echo "${sv_Err}" | grep -i " returned " | sed 's| returned |\
|' | tail -n1 | cut -d " " -f1)
  if test -n "${iv_ErrNo}"
  then
    iv_Err=${iv_ErrNo}
  fi
fi

# Debug message
GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "${sv_Cmd} (returned ${iv_Err}) (${sv_Err})"

# Special cases for errors that aren't errors
case ${iv_Err} in
-205)
  # Mobileconfig isn't installed, so no need to uninstall
  iv_Err=0
  ;;
 
esac

# Remove temporary files
rm -fPR "${GLB_sv_ThisScriptTempDirPath}"

exit ${iv_Err}
