#!/bin/bash
#
# Short:    Payload Handler Script - verify that a .mobileconfig payload is installed OK
# Author:   Mark J Swift
# Version:  2.0.19
# Modified: 22-Oct-2017
#
# Called as follows:    
#   mobileconfig-verify <somefile.mobileconfig> [user]
#
# Without a user specified, verifies for the workstation.
# With a user, verifies for the specified user.

# ---

sv_CodeVersion="2.0.19"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Common.sh
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  GLB_nf_QuickExit "Usage ${GLB_sv_ThisScriptFileName} somefile.mobileconfig"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  GLB_nf_QuickExit "File not found - ${sv_PayloadFilePath}" ${GLB_iv_MsgLevelWarn}
fi

# ---

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  sv_ConfigDirPath="${GLB_sv_ProjectConfigDirPath}/Config/Users/${sv_GPOuser}"
  
else
  sv_ConfigDirPath="${GLB_sv_ProjectConfigDirPath}/Config/Computers/${GLB_sv_Hostname}"
  
fi
mkdir -p "${sv_ConfigDirPath}"

# ---

# Verify the mobileconfig
sv_PayloadUUID=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadUUID'" "${sv_PayloadFilePath}")
if test -n "${sv_GPOuser}"
then
  if test -n "$(/usr/bin/profiles -U "${sv_GPOuser}" -Lv | grep -E "profileUUID: ${sv_PayloadUUID}$")"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "MobileConfig "$(basename ${sv_PayloadFilePath})" is installed OK"

  else
    GLB_nf_QuickExit "MobileConfig "$(basename ${sv_PayloadFilePath})" is not installed" ${GLB_iv_MsgLevelWarn}
    
  fi  
  
else
  if test -n "$(/usr/bin/profiles -Pv | grep -E "profileUUID: ${sv_PayloadUUID}$")"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "MobileConfig "$(basename ${sv_PayloadFilePath})" is already installed"
    
  else
    GLB_nf_QuickExit "MobileConfig "$(basename ${sv_PayloadFilePath})" is not installed" ${GLB_iv_MsgLevelWarn}
    
  fi  
fi

# Remove temporary files
rm -fPR "${GLB_sv_ThisScriptTempDirPath}"
    
# Everything is OK
exit 0
