#!/bin/bash
#
# Short:    Payload Handler Script - uninstall a .mobileconfig payload
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.mobileconfig"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

# ---

# Uninstall the mobileconfig
if test -n "${sv_GPOuser}"
then
  LW_nf_logmessage "ATTENTION, uninstalling config "$(basename ${sv_PayloadFilePath})
  LW_nf_logmessage "DEBUG: /usr/bin/profiles -R -F '${sv_PayloadFilePath}' -U '${sv_GPOuser}'"
  /usr/bin/profiles -R -F "${sv_PayloadFilePath}" -U "${sv_GPOuser}"
  iv_ErrCode="$?"
    
else
  LW_nf_logmessage "ATTENTION, uninstalling config "$(basename ${sv_PayloadFilePath})
  LW_nf_logmessage "DEBUG: /usr/bin/profiles -R -F '${sv_PayloadFilePath}'"
  /usr/bin/profiles -R -F "${sv_PayloadFilePath}"
  iv_ErrCode="$?"
  
fi

# Remove temporary files
srm -fR "${LW_sv_ThisScriptTempDirPath}"

exit ${iv_ErrCode}
