#!/bin/bash
#
# Short:    Payload Handler Script - shrink a .mobileconfig payload down to its bare minimum content
# Author:   Mark J Swift
# Version:  1.0.98
# Modified: 11-Oct-2016
#
# Called as follows:    
#   mobileconfig-shrink <somefile.mobileconfig>
#
# Outputs the path to the shrunken mobileconfig.

# -- Get some info about this script

# Full source of this script
sv_ThisScriptFilePath="${0}"

# Get dir of this script
sv_ThisScriptDirPath="$(dirname "${sv_ThisScriptFilePath}")"

# Get filename of this script
sv_ThisScriptFileName="$(basename "${sv_ThisScriptFilePath}")"

# Filename without extension
sv_ThisScriptName="$(echo ${sv_ThisScriptFileName} | sed 's|\.[^.]*$||')"

# --

# Get the name of the mobileconfig
sv_MobileConfigFilePath="${1}"

if test -z "${sv_MobileConfigFilePath}"
then
  echo "Usage ${sv_ThisScriptFileName} SomeManagedClient.mobileconfig"
  exit 0
fi

# Filename of the mobileconfig
sv_DocFileName="$(basename ${sv_MobileConfigFilePath})"

# Filename without extension
sv_DocName=$(echo ${sv_DocFileName} | sed "s|\.[^.]*$||")

# A place to store the shrunken mobileconfigs
sv_ShrunkDirPath="$(mktemp -dq /tmp/XXXXXXXX)"
cd "${sv_ShrunkDirPath}"

sv_TempFilePath="${sv_ShrunkDirPath}"/Temp.mobileconfig

cp "${sv_MobileConfigFilePath}" "${sv_TempFilePath}"

sv_PayloadUUID=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadUUID'" "${sv_TempFilePath}")

# Set the PayloadIdentifier to be the PayLoad UUID
/usr/libexec/PlistBuddy -c "Set ':PayloadIdentifier' ${sv_PayloadUUID}" "${sv_TempFilePath}"

# Set the PayloadDisplayName to be the DocName
#sv_PayloadDisplayName="${sv_DocName}"
#/usr/libexec/PlistBuddy -c "Set ':PayloadDisplayName' ${sv_PayloadDisplayName}" "${sv_TempFilePath}"

iv_Count=0
while [ 1 ]
do
  sv_PayloadContentPayloadType=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadContent:${iv_Count}:PayloadType'" "${sv_TempFilePath}")
  if test -z "${sv_PayloadContentPayloadType}"
  then
    break

  else
    case "${sv_PayloadContentPayloadType}" in
    'com.apple.ManagedClient.preferences')
      sv_PayloadContentName=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadContent:${iv_Count}:PayloadContent'" "${sv_TempFilePath}" | head -n2 | grep "= Dict {" | tr -d " " | cut -d"=" -f1)

      # Delete mcx [optional] timestamp
      /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:0:PayloadContent:${sv_PayloadContentName}:Set-Once:0:mcx_data_timestamp'" "${sv_TempFilePath}"

      /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:0:PayloadContent:${sv_PayloadContentName}:Forced:0:mcx_data_timestamp'" "${sv_TempFilePath}"
      ;;
    
    esac
    
    sv_PayloadContentPayloadUUID=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadContent:${iv_Count}:PayloadUUID'" "${sv_TempFilePath}")

    # Set the Sub-Payload Content PayloadIdentifier to the Sub-Payload UUID
    /usr/libexec/PlistBuddy -c "Set ':PayloadContent:${iv_Count}:PayloadIdentifier' ${sv_PayloadContentPayloadUUID}" "${sv_TempFilePath}"

    # Delete the PayloadDisplayName
    /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:${iv_Count}:PayloadDisplayName'" "${sv_TempFilePath}"

    # Delete the PayloadOrganization
    /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:${iv_Count}:PayloadOrganization'" "${sv_TempFilePath}"

    # Delete the PayloadDescription
    /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:${iv_Count}:PayloadDescription'" "${sv_TempFilePath}"

    # Delete the PayloadVersion (assumes 1)
    /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:${iv_Count}:PayloadVersion'" "${sv_TempFilePath}"

    # Delete the PayloadEnabled (assumes true)
    /usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadContent:${iv_Count}:PayloadEnabled'" "${sv_TempFilePath}"

  fi
  iv_Count=$((${iv_Count}+1))
done

# Delete the [optional] PayloadOrganization
/usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadOrganization'" "${sv_TempFilePath}"

# Delete the [optional] PayloadDescription
/usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadDescription'" "${sv_TempFilePath}"

# Delete the PayloadVersion (assumes 1)
/usr/libexec/PlistBuddy -c "Delete ':PayloadVersion'" "${sv_TempFilePath}"

# Delete the PayloadScope (User/System is determined by how its installed)
/usr/libexec/PlistBuddy 2>/dev/null -c "Delete ':PayloadScope'" "${sv_TempFilePath}"

## Delete the PayloadType (assumes configuration)
#/usr/libexec/PlistBuddy -c "Delete ':PayloadType'" "${sv_TempFilePath}"

#sv_ShrunkFilePath="${sv_ShrunkDirPath}/${sv_DocFileName}"
sv_ShrunkFilePath="${sv_ShrunkDirPath}/${sv_PayloadUUID}.mobileconfig"

cat "${sv_TempFilePath}" | sed 's|<!DOCTYPE[^>]*>||;s|<?xml[^>]*>||;s|<plist[^>]*>|<plist>|' | tr -d "\t" | tr -d "\n" > "${sv_ShrunkFilePath}"
rm -f "${sv_TempFilePath}"

echo "${sv_ShrunkFilePath}"
