#!/bin/bash
#
# Short:    Payload Handler Script - verify that a .mobileconfig payload is installed OK
# Author:   Mark J Swift
# Version:  1.0.93
# Modified: 21-Aug-2016

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.mobileconfig"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Users/${sv_GPOuser}"
  
else
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Computers/${LW_sv_ADComputerName}"
  
fi
mkdir -p "${sv_ConfigDirPath}"

# ---

# Verify the mobileconfig
sv_PayloadUUID=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadUUID'" "${sv_PayloadFilePath}")
if test -n "${sv_GPOuser}"
then
  if test -n "$(/usr/bin/profiles -U "${sv_GPOuser}" -Lv | grep -E "profileUUID: ${sv_PayloadUUID}$")"
  then
    # Remove temporary files
    rm -fPR "${LW_sv_ThisScriptTempDirPath}"
    
    # Everything is OK
    exit 0
    
  else
    LW_nf_QuickExit "Profile "$(basename ${sv_PayloadFilePath})" is not installed"
    
  fi  
  
else
  if test -n "$(/usr/bin/profiles -Pv | grep -E "profileUUID: ${sv_PayloadUUID}$")"
  then
    # Remove temporary files
    rm -fPR "${LW_sv_ThisScriptTempDirPath}"
    
    exit 0
    
  else
    LW_nf_QuickExit "Profile "$(basename ${sv_PayloadFilePath})" is not installed"
    
  fi  
fi

