#!/bin/bash
#
# Short:    Payload Handler Script - shrink a PolicyBanner.rtf payload down to its bare minimum content
# Author:   Mark J Swift
# Version:  1.0.98
# Modified: 11-Oct-2016
#
# Called as follows:    
#   policybanner-rtf-shrink <somefile.policybanner.rtf>
#
# Outputs the path to the shrunken policybanner.rtf.

# -- Get some info about this script

# Full source of this script
sv_ThisScriptFilePath="${0}"

# Get dir of this script
sv_ThisScriptDirPath="$(dirname "${sv_ThisScriptFilePath}")"

# Get filename of this script
sv_ThisScriptFileName="$(basename "${sv_ThisScriptFilePath}")"

# Filename without extension
sv_ThisScriptName="$(echo ${sv_ThisScriptFileName} | sed 's|\.[^.]*$||')"

# --

# Get the name of the PolicyBanner
sv_ConfigFilePath="${1}"

if test -z "${sv_ConfigFilePath}"
then
  echo "Usage ${sv_ThisScriptFileName} SomeFile.PolicyBanner.rtf"
  exit 0
fi

# Filename of the config
sv_DocFileName="$(basename ${sv_ConfigFilePath})"

# Filename without extension
sv_DocName=$(echo ${sv_DocFileName} | sed "s|\.[^.]*$||")

# A place to store the shrunken mobileconfigs
sv_ShrunkDirPath="$(mktemp -dq /tmp/XXXXXXXX)"
cd "${sv_ShrunkDirPath}"

sv_PayloadUUID=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':UUID'" "${sv_ConfigFilePath}")

sv_ShrunkFilePath=$(mktemp "${sv_ShrunkDirPath}/XXXXXXXX.PolicyBanner.rtf")

cat "${sv_ConfigFilePath}" | sed "s|\\\\$|\\\\line |g" | tr -d "\n" | sed "s| \\\\|\\\\|g;s|\\\\line|\\\\\\
|g" | sed "s|^[ ]*||g" > "${sv_ShrunkFilePath}"

sv_MD5=$(cat "${sv_ShrunkFilePath}" | md5)

mv "${sv_ShrunkDirPath}/XXXXXXXX.PolicyBanner.rtf" "${sv_ShrunkDirPath}/${sv_MD5}.PolicyBanner.rtf"

echo "${sv_ShrunkDirPath}/${sv_MD5}.PolicyBanner.rtf"
