#!/bin/bash
#
# Short:    Payload Handler Script - uninstall a .rtf payload
# Author:   Mark J Swift
# Version:  1.0.86
# Modified: 09-Jun-2016

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Full souce of this script
LCL_MySource="${0}"

# Filename of this script
LCL_MyScript="$(basename ${LCL_MySource})"

# ---

# Full souce of this script
LCL_MySource="${0}"

# Filename of this script
LCL_MyScript="$(basename ${LCL_MySource})"

# ---

LCL_Payload="${1}"

if test -z "${LCL_Payload}"
then
  f_QuickExit "Usage ${LCL_MyScript} somefile.rtf"
fi

if ! test -e "${LCL_Payload}"
then
  f_QuickExit "File not found - ${LCL_Payload}"
fi

# ---

LCL_GPOuser="${2}"

# ---

# Uninstall the RTF
LCL_PayloadName="$(basename ${LCL_Payload})"
case ${LCL_PayloadName} in
PolicyBanner.rtf)
  if test -n "${LCL_GPOuser}"
  then
    f_QuickExit "I cannot uninstall this payload for a user - ${LCL_PayloadName}"
    
  else
    if [ "${GLB_ThisUserName}" != "root" ]
    then
      f_QuickExit "${LCL_Payload} can only be uninstalled as root"

    else
      f_logmessage "ATTENTION, uninstalling ${LCL_PayloadName}"
      rm -f "/Library/Security/${LCL_PayloadName}"
    fi
  fi
  ;;

  *)
  f_QuickExit "I dont know how to uninstall this payload - ${LCL_PayloadName}"

  ;;

esac	    

# Remove temporary files
srm -fR "${GLB_ThisScriptTempDir}"
