#!/bin/bash
#
# Short:    Payload Handler Script - verify that a .rtf payload is installed OK
# Author:   Mark J Swift
# Version:  1.0.95
# Modified: 01-Sep-2016

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.rtf"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Users/${sv_GPOuser}"
  
else
  sv_ConfigDirPath="${LW_sv_SettingsDirPath}/Config/Computers/${LW_sv_ADComputerName}"
  
fi
mkdir -p "${sv_ConfigDirPath}"

# ---

# Verify the RTF
sv_PayloadFileName="$(basename ${sv_PayloadFilePath})"
case ${sv_PayloadFileName} in
PolicyBanner.rtf)
  if test -n "${sv_GPOuser}"
  then
    LW_nf_QuickExit "This is not a user payload - ${sv_PayloadFileName}"

  else
    if test -f "/Library/Security/${sv_PayloadFileName}"
    then

      sv_ExistingShaSum="$(shasum -a 256 "/Library/Security/${sv_PayloadFileName}" | cut -d" " -f1)"
      sv_PayloadShaSum="$(shasum -a 256 "${sv_PayloadFilePath}" | cut -d" " -f1)"
      
      if [ "${sv_ExistingShaSum}" != "${sv_PayloadShaSum}" ]
      then
        LW_nf_QuickExit "The installed ${sv_PayloadFileName} needs updating"
        
      fi
    else
      LW_nf_QuickExit "${sv_PayloadFileName} is not installed"

    fi
  fi
  ;;

  *)
  LW_nf_QuickExit "I dont know what to do with this payload - ${sv_PayloadFileName}"

  ;;

esac	    

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"
