#!/bin/bash
#
# Short:    Payload Handler Script - verify that a .rtf payload is installed OK
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.rtf"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  sv_ConfigDirPath="${LW_sv_ConfigDirPath}/${sv_GPOuser}"
  
else
  sv_ConfigDirPath="${LW_sv_ConfigDirPath}/${LW_sv_ADComputerName}"
  
fi
mkdir -p "${sv_ConfigDirPath}"

# ---

# Verify the RTF
sv_PayloadFileName="$(basename ${sv_PayloadFilePath})"
case ${sv_PayloadFileName} in
PolicyBanner.rtf)
  if test -n "${sv_GPOuser}"
  then
    LW_nf_QuickExit "This is not a user pyload - ${sv_PayloadFileName}"

  else
    if test -f "/Library/Security/${sv_PayloadFileName}"
    then
      # Remove temporary files
      srm -fR "${LW_sv_ThisScriptTempDirPath}"
      
      exit 0
      
    else
      LW_nf_QuickExit "Profile ${sv_PayloadFileName} is not installed"

    fi
  fi
  ;;

  *)
  LW_nf_QuickExit "I dont know what to do with this payload - ${sv_PayloadFileName}"

  ;;

esac	    

# Remove temporary files
srm -fR "${LW_sv_ThisScriptTempDirPath}"
