#!/bin/bash
#
# Short:    Payload Handler Script - install a .rtf payload
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Called as follows:    
#   rtf-install <somefile.rtf> [user]
#
# Without a user specified, installs for the workstation.
# With a user, installs for the specified user.
#
# At the moment, it only handles PolicyBanner.rtf files, which can only
# be installed for the workstation.

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "Usage ${LW_sv_ThisScriptFileName} somefile.rtf"
fi

if ! test -e "${sv_PayloadFilePath}"
then
  LW_nf_QuickExit "File not found - ${sv_PayloadFilePath}"
fi

# ---

sv_GPOuser="${2}"

# ---

# Install the RTF
sv_PayloadFileName="$(basename ${sv_PayloadFilePath})"
case ${sv_PayloadFileName} in
PolicyBanner.rtf)
  if test -n "${sv_GPOuser}"
  then
    LW_nf_QuickExit "I cannot install this payload for a user - ${sv_PayloadFileName}"
    
  else
    if [ "${LW_sv_ThisUserName}" != "root" ]
    then
      LW_nf_QuickExit "${sv_PayloadFilePath} can only be installed as root"

    else
      LW_nf_logmessage "ATTENTION, installing ${sv_PayloadFileName}"
      rm -f "/Library/Security/${sv_PayloadFileName}"
      cp "${sv_PayloadFilePath}" "/Library/Security/"
    fi
  fi
  ;;

  *)
  LW_nf_QuickExit "I dont know how to install this payload - ${sv_PayloadFileName}"

  ;;

esac	    

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"
