#!/bin/bash
#
# Short:    Sys Policy script - Sets a policy banner which is displayed at the Login Window
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Triggered by the following events:
#   Sys-Boot (as root)
#
#   ... see associated config 'PolicyBanner.mobileconfig'
#
# Called as follows:    
#   Sys-PolicyBanner <ConfigFilePath> <ConfigEntryName> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.5"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

case ${GLB_SV_EVENTNAME} in

Sys-Boot|Sys-PolicyInstall)
  sv_RTFfile="/Library/Security/${GLB_SV_CONFIGUUID}.rtf"
  if [ ! -e "${sv_RTFfile}" ]
  then
    # If our policy banner doesn't exist - then rebuild it
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Creating policy banner file '${sv_RTFfile}'"
    sv_Title="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Title")"
    sv_Text="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Text")"
    echo "{\rtf1\ansi\pard\qc\b\fs36" >"${sv_RTFfile}"
    echo "${sv_Title}" | sed 's|$|\\|g' >>"${sv_RTFfile}"
    echo '\b0' >>"${sv_RTFfile}"
    echo '\' >>"${sv_RTFfile}"
    echo "${sv_Text}" | sed 's|$|\\|g' >>"${sv_RTFfile}"
    echo '}' >>"${sv_RTFfile}"
  fi
  
  if [ "$(stat -f "%Y" "/Library/Security/PolicyBanner.rtf")" != "${sv_RTFfile}" ]
  then
    # If the active policy banner is not a link to our policy banner - then create the link
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Activating policy banner file '${sv_RTFfile}'"
    rm -f "/Library/Security/PolicyBanner.rtf"
    ln -s "${sv_RTFfile}" "/Library/Security/PolicyBanner.rtf"
  fi
  ;;
  
Sys-PolicyUninstall)
  sv_RTFfile="/Library/Security/${GLB_SV_CONFIGUUID}.rtf"
  if [ -e "${sv_RTFfile}" ]
  then
    # Uninstall the PolicyBanner.rtf file
    rm -f "/Library/Security/PolicyBanner.rtf"
    rm -f "${sv_RTFfile}"
  fi
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
