#!/bin/bash
#
# Short:    Gen Policy script - Writes debug info to the policy prefs
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Triggered by the following events:
#   All events (as user or root)
#
# Called as follows:    
#   Gen-Debug <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.5"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

case ${GLB_SV_EVENTNAME} in
    
*)
  while read sv_GlobalName
  do
    # Could do this simpler, but I'd like to test the 'GLB_SF_EXPANDGLOBALSINSTRING' function
    sv_GlobalDef='%'$(echo ${sv_GlobalName} | sed "s|^GLB_||")'%'
    
    sv_GlobalValue=$(GLB_SF_EXPANDGLOBALSINSTRING ${sv_GlobalDef})
    
    if test -n "${sv_GlobalValue}"
    then
      if [ "${sv_GlobalDef}" = "%SV_ADTRUSTACCOUNTPASSWORD%" ]
      then
        sv_GlobalValue='*****'
      fi
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "(${GLB_SV_EVENTNAME}) ${sv_GlobalDef} '${sv_GlobalValue}'"
    fi
  
  done < <(cat "${GLB_SV_PROJECTDIRPATH}"/inc-sh/Common.sh | grep -E "^[ ]*#[ ]*GLB_(B|I|S)V_[A-Za-z0-9]*[ ]*-.*" | grep -iv "F_" | sed "s|^[ ]*#[ ]*||" | cut -d" " -f1 | sort -u)
  ;;

esac
  
# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
