#!/bin/bash
#
# Short:    Sys Policy script - Will shutdown laptop when the lid is shut
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Sys-WillSleep (as root)
#
# Called as follows:    
#   Sys-ShutdownWhenLidShut <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-WillSleep)
  iv_ShutdownDelaySecs="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:ShutdownDelaySecs")"
  if test -z "${iv_ShutdownDelaySecs}"
  then
    iv_ShutdownDelaySecs=10
  fi
  
  # Get the current lid status
  sv_LidClosedStatus="$(ioreg -r -k AppleClamshellState -d 4 | grep AppleClamshellState | tr " " "\n" | tail -n1)"

  if [ "${sv_LidClosedStatus}" = "Yes" ]
  then
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Laptop lid has been closed - waiting up to ${iv_ShutdownDelaySecs} seconds shutting down."

    # Allow lid to be closed a short time before shutting down
    iv_DelayCount=0
    while [ ${iv_DelayCount} -lt ${iv_ShutdownDelaySecs} ]
    do
      sv_LidClosedStatus="$(ioreg -r -k AppleClamshellState -d 4 | grep AppleClamshellState | tr " " "\n" | tail -n1)"
      if [ "${sv_LidClosedStatus}" = "No" ]
      then
        break
      fi
  
      # we don't want to hog the CPU - so lets sleep a while
      sleep 1

      iv_DelayCount=$((${iv_DelayCount}+1))
    done
    
    # Check if the lid is still closed
    if [ "${sv_LidClosedStatus}" = "Yes" ]
    then
      # Shutdown if the lid has been closed for a while
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Laptop lid has been closed for ${iv_ShutdownDelaySecs} seconds - we need to shutdown."
      GLB_NF_NAMEDFLAGCREATE "Shutdown"
    
    else
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Policy aborted - laptop lid has been re-opened."
    
   fi

  else
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Policy aborted - laptop lid is open."
    
  fi

  ;;

Sys-PolicyInstall|Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
