#!/bin/bash
#
# Short:    Sys Policy script - Installs Software
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Sys-ManualTrigger  (as root)
#   Sys-Idle           (as root)
#
# Called as follows:    
#   Sys-SoftwareManifest <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

# It's early days for this quite complex policy, so enable debug logging
GLB_IV_LOGLEVELTRAP=${GLB_IC_MSGLEVELDEBUG}

# ---

# Return the next epoch that matches with the given unit value
if_NextUnitValueEpoch()   # ReferenceEpoch, Unit (i.e. S, M, H, d, m or Y), Value
{
  local iv_ReferenceEpoch
  local sv_Unit
  local iv_Value
  local sv_NewDateString
  local iv_NewEpoch
  local sv_NextUnit
  
  iv_ReferenceEpoch=${1}
  sv_Unit=${2}
  iv_Value=${3}
  
  sv_NewDateString=$(echo "%S:%M:%H:%d:%m:%Y" | sed "s|%"${sv_Unit}"|"${iv_Value}"|")
  iv_NewEpoch=$(date -j -f "%S:%M:%H:%d:%m:%Y" $(date -r ${iv_ReferenceEpoch} "+"${sv_NewDateString}) "+%s")
  
  if [ ${iv_NewEpoch} -ge ${iv_ReferenceEpoch} ]
  then
    iv_ReferenceEpoch=${iv_NewEpoch}
  else
    sv_NextUnit=$(echo "SMHdmy" | tr "${sv_Unit}" "\n" | tail -n1 | cut -c1)
    if [ -n "${sv_NextUnit}" ]
    then
      iv_ReferenceEpoch=$(date -j -r ${iv_NewEpoch} -v +1${sv_NextUnit} +%s)
    fi
  fi

  echo "${iv_ReferenceEpoch}"
}

if_PrevUnitValueEpoch()   # ReferenceEpoch, Unit (i.e. S, M, H, d, m or Y), Value
{
  local iv_ReferenceEpoch
  local sv_Unit
  local iv_Value
  local sv_NewDateString
  local iv_NewEpoch
  local sv_NextUnit
  
  iv_ReferenceEpoch=${1}
  sv_Unit=${2}
  iv_Value=${3}
  
  sv_NewDateString=$(echo "%S:%M:%H:%d:%m:%Y" | sed "s|%"${sv_Unit}"|"${iv_Value}"|")
  iv_NewEpoch=$(date -j -f "%S:%M:%H:%d:%m:%Y" $(date -r ${iv_ReferenceEpoch} "+"${sv_NewDateString}) "+%s")
  
  if [ ${iv_NewEpoch} -le ${iv_ReferenceEpoch} ]
  then
    iv_ReferenceEpoch=${iv_NewEpoch}
  else
    sv_NextUnit=$(echo "SMHdmy" | tr "${sv_Unit}" "\n" | tail -n1 | cut -c1)
    if [ -n "${sv_NextUnit}" ]
    then
      iv_ReferenceEpoch=$(date -j -r ${iv_NewEpoch} -v -1${sv_NextUnit} +%s)
    fi
  fi

  echo "${iv_ReferenceEpoch}"
}

bf_VersionIsLater() #VersionStringA, VersionStringB - returns true if A is later than B
{
  local sv_VersionAString
  local sv_VersionBString
  local iv_VersionALen
  local iv_VersionBLen
  local bv_VersionAHasLaterVersion
  local iv_Count
  local iv_VersionADigit
  local iv_VersionBDigit
  
  # Sanitise the input
  sv_VersionAString=$(echo ${1} | sed "s|\([^0-9.]*\)\(\([0-9]*[\.]\)*[0-9]*\)\(.*\)|\2|" | head -n1)
  sv_VersionBString=$(echo ${2} | sed "s|\([^0-9.]*\)\(\([0-9]*[\.]\)*[0-9]*\)\(.*\)|\2|" | head -n1)
  
  # Get the maximum length version string
  iv_VersionALen=$(echo ${sv_VersionAString} | tr "." "\n" | wc -l | sed "s|^[ ]*||;s|[ ]*$||")
  iv_VersionBLen=$(echo ${sv_VersionBString} | tr "." "\n" | wc -l | sed "s|^[ ]*||;s|[ ]*$||")
  if [ ${iv_VersionALen} -gt ${iv_VersionBLen} ]
  then
    iv_VersionLen=${iv_VersionALen}
  else
    iv_VersionLen=${iv_VersionBLen}
  fi

  # Extend version strings to the maximum
  sv_VersionAString=$(echo ${sv_VersionAString}"$(jot -b "." ${iv_VersionLen} | tr "\n" "0")" | cut -d"." -f1-${iv_VersionLen})
  sv_VersionBString=$(echo ${sv_VersionBString}"$(jot -b "." ${iv_VersionLen} | tr "\n" "0")" | cut -d"." -f1-${iv_VersionLen})

  bv_VersionAHasLaterVersion=${GLB_BC_FALSE}

  for (( iv_Count = 1; iv_Count <= iv_VersionLen; iv_Count++ )); do
    iv_VersionADigit=$(echo ${sv_VersionAString} | cut -d"." -f${iv_Count})
    iv_VersionBDigit=$(echo ${sv_VersionBString} | cut -d"." -f${iv_Count})
    if [ ${iv_VersionADigit} -lt ${iv_VersionBDigit} ]
    then
      break
    fi
    if [ ${iv_VersionADigit} -gt ${iv_VersionBDigit} ]
    then
      bv_VersionAHasLaterVersion=${GLB_BC_TRUE}
      break
    fi
  done
    
  echo ${bv_VersionAHasLaterVersion}
}

# Returns the following:
# "false:false" - Item is not installed
# "true:false"  - Item is installed, but the version is not current
# "true:true"   - Item is installed, and the version is current
sf_ItemInstallStatus() # ItemRoot, DefaultStatus i.e. :${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}, true
{
  local sv_ItemRoot
  local bv_DefaultInstalledStatus
  local bv_ItemIsInstalled
  local bv_VersionIsCurrent
  local sv_ManifestURIPath
  local sv_ManifestURIFileName
  local sv_ItemFileName
  local sv_ItemType
  local sv_ItemExt
  local sv_TryMethod
  local sv_ItemDstDir
  local sv_ItemDstPath
  local sv_VersionKey
  local sv_ItemVersion
  local sv_InfoFile
  local sv_InstalledVersion
  local sv_Itemmd5checksum
  local sv_Installedmd5checksum
  
  sv_ItemRoot="${1}"
  
  # When action is "INSTALL", default to thinking the item is installed
  # When action is "UNINSTALL", default to thinking the item is not installed
  bv_DefaultInstalledStatus="${2}"
  if [ -z "${bv_DefaultInstalledStatus}" ]
  then
    bv_DefaultInstalledStatus=${GLB_BC_TRUE}
  fi
  
  bv_ItemIsInstalled=${bv_DefaultInstalledStatus}
  bv_VersionIsCurrent=${bv_DefaultInstalledStatus}

  sv_ItemFileName="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:FileName")"

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemFileName '${sv_ItemFileName}'"

  if [ -z "${sv_ItemFileName}" ]
  then
    sv_ItemType="UNKNOWN"

  else
    sv_ItemType="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:Type")"
    if [ -z "${sv_ItemType}" ]
    then
      sv_ItemExt="$(echo ${sv_ItemFileName} | grep '\.' | sed 's|.*\.||' | tr [a-z] [A-Z] )"

      case ${sv_ItemExt} in

      APP)
        sv_ItemType="Application"
        ;;
        
      PKG)
        sv_ItemType="Package"
        ;;
        
      SH|PY|COMMAND)
        sv_ItemType="Executable"
        ;;
        
      *)
        sv_ItemType="File"
        ;;
        
      esac
    fi
  fi
  
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemType '${sv_ItemType}'"
    
  sv_TryMethod="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:TryMethod" | tr [a-z] [A-Z])"
  if [ -z "${sv_TryMethod}" ]
  then
    sv_TryMethod="ONCE"
  fi
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_TryMethod '${sv_TryMethod}'"

  case ${sv_TryMethod} in

  ALWAYS)
    # When action is "INSTALL", default to thinking the item is installed but out of date
    # When action is "UNINSTALL", default to thinking the item is not installed and out of date
    bv_ItemIsInstalled=${bv_DefaultInstalledStatus}
    bv_VersionIsCurrent=${GLB_BC_FALSE}
    ;;
    
  *)
    # Check if the item is installed - assume the default
    bv_ItemIsInstalled=${bv_DefaultInstalledStatus}
    bv_VersionIsCurrent=${bv_DefaultInstalledStatus}

    case ${sv_ItemType} in
              
    File)
      sv_ItemDstDir="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:DstDir")"
      if [ -z "${sv_ItemDstDir}" ]
      then
        sv_ItemDstDir="/"
      fi
      sv_ItemDstDir="$(echo "${sv_ItemDstDir}/" | tr -s "/")"

      sv_ItemDstPath="${sv_ItemDstDir}${sv_ItemFileName}"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemDstPath '${sv_ItemDstPath}'"
      if [ ! -e "${sv_ItemDstPath}" ]
      then
        bv_ItemIsInstalled=${GLB_BC_FALSE}
        bv_VersionIsCurrent=${GLB_BC_FALSE}
      
      else
        bv_ItemIsInstalled=${GLB_BC_TRUE}

        # Get the item md5 checksum
        sv_Itemmd5checksum="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:${sv_ItemType}:md5checksum")"
        if [ -z "${sv_Itemmd5checksum}" ]
        then
          sv_Itemmd5checksum=0
        fi
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_Itemmd5checksum '${sv_Itemmd5checksum}'"
        
        sv_Installedmd5checksum=$(md5 -q "${sv_ItemDstPath}")
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_Installedmd5checksum '${sv_Installedmd5checksum}'"

        if [ "${sv_Itemmd5checksum}" = "${sv_Installedmd5checksum}" ]
        then
          # Installed version is equal to the item version
          bv_VersionIsCurrent=${GLB_BC_TRUE}
        else
          bv_VersionIsCurrent=${GLB_BC_FALSE}
        fi

      fi
      ;;
    
    Application)
      # We have a valid application name, default to thinking the item is not installed
      sv_ItemDstDir="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:DstDir")"
      if [ -z "${sv_ItemDstDir}" ]
      then
        sv_ItemDstDir="/Applications"
      fi
      sv_ItemDstDir="$(echo "${sv_ItemDstDir}/" | tr -s "/")"

      sv_ItemDstPath="${sv_ItemDstDir}${sv_ItemFileName}"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemDstPath '${sv_ItemDstPath}'"
      if [ ! -e "${sv_ItemDstPath}" ]
      then
        bv_ItemIsInstalled=${GLB_BC_FALSE}
        bv_VersionIsCurrent=${GLB_BC_FALSE}
      
      else
        bv_ItemIsInstalled=${GLB_BC_TRUE}

        # Get the item version
        sv_VersionKey="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:${sv_ItemType}:VersionKey")"
        if [ -z "${sv_VersionKey}" ]
        then
          sv_VersionKey="CFBundleShortVersionString"
        fi
        
        sv_ItemVersion="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:${sv_ItemType}:${sv_VersionKey}")"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemVersion '${sv_ItemVersion}'"
        if [ -z "${sv_ItemVersion}" ]
        then
          sv_ItemVersion=0
        fi
        
        # Application is already installed, so get the installed version
        sv_InfoFile="${sv_ItemDstPath}/Contents/Info.plist"
        if [ ! -e "${sv_InfoFile}" ]
        then
          bv_VersionIsCurrent=${GLB_BC_FALSE}
        else
          sv_InstalledVersion=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print '${sv_VersionKey}'" "${sv_InfoFile}")
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_InstalledVersion '${sv_InstalledVersion}'"
          if [ -z "${sv_InstalledVersion}" ]
          then
            sv_InstalledVersion=0
          fi
          if [ "$(bf_VersionIsLater "${sv_ItemVersion}" "${sv_InstalledVersion}")" = "${GLB_BC_FALSE}" ]
          then
            # Installed version is greater or equal to the item version
            bv_VersionIsCurrent=${GLB_BC_TRUE}
          else
            bv_VersionIsCurrent=${GLB_BC_FALSE}
          fi
        fi
      fi
      ;;
    
    Package)
      sv_ItemID="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:${sv_ItemType}:ID")"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemID '${sv_ItemID}'"
      if [ -n "${sv_ItemID}" ]
      then
        # We have a valid package ID, check to see if the item is already installed
        
        # Get the installed version string
        sv_InstalledVersion="$(pkgutil --pkg-info ${sv_ItemID} | grep -i "version:" | cut -d" " -f2)"
        if test -z "${sv_InstalledVersion}"
        then
          sv_InstalledVersion="0"
          bv_ItemIsInstalled=${GLB_BC_FALSE}
        else
          bv_ItemIsInstalled=${GLB_BC_TRUE}
        fi

        sv_ItemVersion="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" "${sv_ItemRoot}:${sv_ItemType}:VersionString")"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "ItemInstallStatus: sv_ItemVersion '${sv_ItemVersion}'"
        if [ -z "${sv_ItemVersion}" ]
        then
          sv_ItemVersion=0
        fi

        if [ "$(bf_VersionIsLater "${sv_ItemVersion}" "${sv_InstalledVersion}")" = "${GLB_BC_FALSE}" ]
        then
          # Installed version is greater or equal to the item version
          bv_VersionIsCurrent=${GLB_BC_TRUE}
        else
          bv_VersionIsCurrent=${GLB_BC_FALSE}
        fi

      fi
      ;;
    
    Executable)
      # When action is "INSTALL", default to thinking the item is installed
      # When action is "UNINSTALL", default to thinking the item is not installed
      # To run an executable at "INSTALL", use TryMethod "ALWAYS"
      bv_ItemIsInstalled=${bv_DefaultInstalledStatus}
      bv_VersionIsCurrent=${bv_DefaultInstalledStatus}
      ;;
                
    *)
      # Assume default for unhandled item types
      bv_ItemIsInstalled=${bv_DefaultInstalledStatus}
      bv_VersionIsCurrent=${bv_DefaultInstalledStatus}
      ;;
              
    esac
   ;;
  
  esac
  
  echo "${bv_ItemIsInstalled}:${bv_VersionIsCurrent}"
}

bf_RunAction() # [install] | [uninstall] | [schedule]
{
  local sv_Action
  local sv_CallMethod
  local bv_ActionAborted
  local sv_Err
  local sv_ManifestURIPath
  local sv_ManifestURIFileName
  local sv_MinOS
  local sv_MaxOS
  local bv_ManifestInstalled
  local bv_ManifestFullyInstalled
  local iv_ItemCount
  local iv_ItemIndex
  local sv_ItemType
  local sv_ItemInstallStatus
  local sv_DmgMountPoint
  local sv_ManifestSrcPath
  local sv_ManifestSrcExt
  local sv_ItemType
  local sv_RemoveMethod
  local sv_TryMethod
  local sv_ItemSrcDir
  local sv_ItemDstDir
  local sv_ItemSrcPath
  local sv_ItemDstPath
  local sv_UnarchiveDirPath
  local sv_ItemExt
  local bv_ItemDoInstall
  local bv_DefaultInstalledStatus
  local bv_ItemInstalled
  local bv_ItemFullyInstalled
  local sv_LegacyManifestURI
  local iv_ManifestCount
  local iv_ManifestIndex
  local sv_ManifestRoot
  
  # Install or uninstall a manifest list
  sv_CallMethod=$(echo "${1}" | tr [a-z] [A-Z])
  if [ -z "${sv_CallMethod}" ]
  then
    sv_CallMethod="INSTALL"
  fi
    
  # Check for old config. We still want to support previous configs, where there was a single manifest and no array
  sv_LegacyManifestURI="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:ManifestURI")"
  if [ -n "${sv_LegacyManifestURI}" ]
  then
    iv_ManifestCount=1
  else
    iv_ManifestCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Manifest")"
  fi
  
  if [ ${iv_ManifestCount} -gt 0 ]
  then

    for (( iv_ManifestIndex=0; iv_ManifestIndex<${iv_ManifestCount}; iv_ManifestIndex++ ))
    do
      if [ -n "${sv_LegacyManifestURI}" ]
      then
        sv_ManifestRoot=""
        sv_ManifestURIPath="${sv_LegacyManifestURI}"
      else
        sv_ManifestRoot=":Manifest:${iv_ManifestIndex}"
        sv_ManifestURIPath="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:URI")"
      fi
      

  sv_ManifestURIFileName="$(basename "$(echo ${sv_ManifestURIPath} | grep -v '/$')")"
  
  sv_ManifestURIPath="$(echo "${sv_ManifestURIPath}" | sed "s|[/]*$||")"

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: sv_ManifestURIPath '${sv_ManifestURIPath}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: sv_ManifestURIFileName '${sv_ManifestURIFileName}'"

  sv_Action="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Action" | tr [a-z] [A-Z])"
  if [ -z "${sv_Action}" ]
  then
    sv_Action="INSTALL"
  fi

  if [ "${sv_Action}" = "AUTO" ]
  then
    sv_Action="${sv_CallMethod}"
  fi

  if [ "${sv_Action}" != "UNINSTALL" ]
  then
    sv_Action="INSTALL"
  fi

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: sv_Action '${sv_Action}'"
  
  # Grab lock - we only want to install when there are no other installs or uninstalls happening, wait up to 10 mins
  if [ $(GLB_BF_NAMEDLOCKGRAB "${GLB_SV_THISSCRIPTFILENAME}" 600 ${GLB_BC_TRUE}) = ${GLB_BC_FALSE} ]
  then
    bv_ActionAborted=${GLB_BC_TRUE}
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Software ${sv_Action} aborted - Cannot grab lock"

  else  
    GLB_NF_SETPLISTPROPERTY "${GLB_SV_POLICYPREFSFILEPATH}" ":${GLB_SV_CONFIGUUID}:Prefs:LastTryEpoch" "${GLB_IV_THISSCRIPTSTARTEPOCH}"

    bv_ActionAborted=${GLB_BC_FALSE}
    sv_Err=0

    sv_MinOS="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:MinOS")"
    if [ -n "${sv_MinOS}" ]
    then
      if [ "$(bf_VersionIsLater "${sv_MinOS}" "${GLB_SV_SYSTEMVERSIONSTAMPASSTRING}")" = "${GLB_BC_TRUE}" ]
      then
        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Manifest ${iv_ManifestIndex}: Software '${sv_Action}' '${sv_ManifestURIPath}' aborted - MinOS ${sv_MinOS} is later than the active OS ${GLB_SV_SYSTEMVERSIONSTAMPASSTRING}"
        bv_ActionAborted=${GLB_BC_TRUE}
        sv_Err=99
      fi
    fi
  
    sv_MaxOS="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:MaxOS")"
    if [ -n "${sv_MaxOS}" ]
    then
      if [ "$(bf_VersionIsLater "${GLB_SV_SYSTEMVERSIONSTAMPASSTRING}" "${sv_MaxOS}")" = "${GLB_BC_TRUE}" ]
      then
        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Manifest ${iv_ManifestIndex}: Software '${sv_Action}' '${sv_ManifestURIPath}' aborted - The active OS version ${GLB_SV_SYSTEMVERSIONSTAMPASSTRING} is later than MaxOS ${sv_MaxOS}"
        bv_ActionAborted=${GLB_BC_TRUE}
        sv_Err=99
      fi
    fi

    if [ "${bv_ActionAborted}" = "${GLB_BC_FALSE}" ]
    then
      if [ "${sv_Action}" = "INSTALL" ]
      then
        bv_DefaultInstalledStatus=${GLB_BC_TRUE}
      else
        bv_DefaultInstalledStatus=${GLB_BC_FALSE}
      fi

      iv_ItemCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item")"
      if [ ${iv_ItemCount} -gt 0 ]
      then

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: START check Manifest ${sv_Action} status"

        # ---
        # Run through the manifest items to check the installation status
        bv_ManifestInstalled="${GLB_BC_FALSE}"
        bv_ManifestFullyInstalled="${GLB_BC_TRUE}"
        for (( iv_ItemIndex=0; iv_ItemIndex<${iv_ItemCount}; iv_ItemIndex++ ))
        do
          sv_ItemInstallStatus=$(sf_ItemInstallStatus ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}" ${bv_DefaultInstalledStatus})
          if [ "${sv_ItemInstallStatus}" != "${GLB_BC_FALSE}:${GLB_BC_FALSE}" ]
          then
            bv_ManifestInstalled="${GLB_BC_TRUE}"
            if [ "${sv_ItemInstallStatus}" != "${GLB_BC_TRUE}:${GLB_BC_TRUE}" ]
            then
              bv_ManifestFullyInstalled="${GLB_BC_FALSE}"
            fi
          else
            bv_ManifestFullyInstalled="${GLB_BC_FALSE}"
          fi
        done
            
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: RESULT ManifestInstalled '${bv_ManifestInstalled}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: RESULT ManifestFullyInstalled '${bv_ManifestFullyInstalled}'"

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: END check Manifest ${sv_Action} status"
        # ---

        if [[ ( ( "${sv_Action}" = "INSTALL" ) && ( "${bv_ManifestFullyInstalled}" = "${GLB_BC_TRUE}" ) ) || ( ( "${sv_Action}" = "UNINSTALL" ) && ( "${bv_ManifestInstalled}" = "${GLB_BC_FALSE}" ) ) ]]
        then
          GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Manifest ${sv_Action} skipped - Already ${sv_Action}ed (${sv_ManifestURIPath})"
          sv_Err=0
              
        else
          sv_ManifestURILocalPath=""
          sv_ManifestSrcPath=""
          sv_DmgMountPoint=""
          
          # ---

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: About to run through Items to ${sv_Action}"

          # ---
          # Run through the manifest items
          for (( iv_ItemIndex=0; iv_ItemIndex<${iv_ItemCount}; iv_ItemIndex++ ))
          do
            sv_ItemFileName="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:FileName")"

            # if we didn't supply a filename, use the manifest file name
            if [ -z "${sv_ItemFileName}" ]
            then
              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - Item filename missing"
              break
            fi

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemFileName '${sv_ItemFileName}'"

            sv_ItemInstallStatus=$(sf_ItemInstallStatus ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}" ${bv_DefaultInstalledStatus})

            if [ "${sv_ItemInstallStatus}" = "${GLB_BC_FALSE}:${GLB_BC_FALSE}" ]
            then
              bv_ItemInstalled="${GLB_BC_FALSE}"
              bv_ItemFullyInstalled="${GLB_BC_FALSE}"
            else
              bv_ItemInstalled="${GLB_BC_TRUE}"
              if [ "${sv_ItemInstallStatus}" = "${GLB_BC_TRUE}:${GLB_BC_TRUE}" ]
              then
                bv_ItemFullyInstalled="${GLB_BC_TRUE}"
              else
                bv_ItemFullyInstalled="${GLB_BC_FALSE}"
              fi
            fi

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: ItemInstalled '${bv_ItemInstalled}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: ItemFullyInstalled '${bv_ItemFullyInstalled}'"

            sv_TryMethod="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:TryMethod" | tr [a-z] [A-Z])"
            if [ -z "${sv_TryMethod}" ]
            then
              sv_TryMethod="ONCE"
            fi
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_TryMethod '${sv_TryMethod}'"

# maybe Action, TryMethod - CHECK, FIX, ONCE, ALWAYS
       
            # ---
            # Check the TryMethod special cases
                  
            # DO an install, if 
            #  TryMethod != "CHECK" AND
            #  Action = "INSTALL" AND
            #  TryMethod = "FIX" AND manifest is not fully installed
            #  or TryMethod = "ONCE" AND item is either not installed or not up to date
            #  or TryMethod = "ALWAYS"

            # DO an uninstall, if 
            #  TryMethod != "CHECK" AND
            #  Action = "UNINSTALL" AND manifest item is installed
                  
            case ${sv_Action} in
            INSTALL)
              case ${sv_TryMethod} in
              CHECK|NEVER)
                bv_ItemFullyInstalled="${GLB_BC_TRUE}"
                ;;

              ALWAYS)
                bv_ItemFullyInstalled="${GLB_BC_FALSE}"
                ;;

              FIX)
                if [ "${bv_ManifestFullyInstalled}" = "${GLB_BC_FALSE}" ]
                then
                  bv_ItemFullyInstalled="${GLB_BC_FALSE}"
                fi
                ;;

              esac
              ;;

            UNINSTALL)
              case ${sv_TryMethod} in
              CHECK|NEVER)
                bv_ItemInstalled="${GLB_BC_FALSE}"
                ;;

              esac
              ;;

            esac
                  
            # ---
            # Do the install or uninstall
            if [[ ( ( "${sv_Action}" = "INSTALL" ) && ( "${bv_ItemFullyInstalled}" = "${GLB_BC_TRUE}" ) ) || ( ( "${sv_Action}" = "UNINSTALL" ) && ( "${bv_ItemInstalled}" = "${GLB_BC_FALSE}" ) ) ]]
            then
              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: ${sv_Action} skipped - Already ${sv_Action}ed (${sv_ItemFileName})"
              sv_Err=0
              
            else

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Begin ${sv_Action}"

              # ---
              # Work out the ItemType
              if [ -z "${sv_ItemFileName}" ]
              then
                sv_ItemType="UNKNOWN"

              else
                sv_ItemType="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:Type")"
                if [ -z "${sv_ItemType}" ]
                then
                  sv_ItemExt="$(echo ${sv_ItemFileName} | grep '\.' | sed 's|.*\.||' | tr [a-z] [A-Z] )"

                  case ${sv_ItemExt} in

                  APP)
                    sv_ItemType="Application"
                    ;;
        
                  PKG)
                    sv_ItemType="Package"
                    ;;
        
                  SH|PY|COMMAND)
                    sv_ItemType="Executable"
                    ;;
        
                  *)
                    sv_ItemType="File"
                    ;;
        
                  esac
                fi
              fi
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemType '${sv_ItemType}'"

              # ---
              # Work out the ItemSrcPath and ItemDstPath
              case ${sv_ItemType} in
              Executable|Package)
                sv_ItemSrcDir="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:SrcDir")"
                if [ -z "${sv_ItemSrcDir}" ]
                then
                  sv_ItemSrcDir="/"
                fi
                sv_ItemSrcDir="$(echo "${sv_ItemSrcDir}/" | tr -s "/")"
                  
                sv_ItemSrcPath="${sv_ItemSrcDir}${sv_ItemFileName}"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemSrcPath '${sv_ItemSrcPath}'"
                ;;
                  
              File|Application)
                sv_ItemSrcDir="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:SrcDir")"
                if [ -z "${sv_ItemSrcDir}" ]
                then
                  sv_ItemSrcDir="/"
                fi
                sv_ItemSrcDir="$(echo "${sv_ItemSrcDir}/" | tr -s "/")"

                sv_ItemDstDir="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:DstDir")"
                if [ -z "${sv_ItemDstDir}" ]
                then
                  sv_ItemDstDir="/Applications"
                fi
                sv_ItemDstDir="$(echo "${sv_ItemDstDir}/" | tr -s "/")"

                sv_ItemSrcPath="${sv_ItemSrcDir}${sv_ItemFileName}"
                sv_ItemDstPath="${sv_ItemDstDir}${sv_ItemFileName}"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemSrcPath '${sv_ItemSrcPath}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemDstPath '${sv_ItemDstPath}'"
                ;;
                    
              *)
                ;;
              esac
              
                            
              # ---
              # Kill anything running at the destination path
              if [ -n "${sv_ItemDstPath}" ]
              then
                # If necessary, kill the item process(es)
                while read sv_PID
                do
                  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Killing item PID ${sv_PID} of '${sv_ItemType}' '${sv_ItemDstPath}'"
                  kill ${sv_PID}
                done < <(ps -axo "pid, user, command" | grep -i "${sv_ItemDstPath}" | grep -v "grep" | sed "s|^[ ]*||" | cut -d" " -f1)
              fi

              # ---
              # Install/uninstall item
              if [ "${sv_TryMethod}" != "CHECK" ]
              then

                # ---
                # Download manifest, if appropriate
                # ---

                if [ -n "${sv_ManifestURIPath}" ]
                then
            
                  if [[ ( ( "${sv_Action}" = "INSTALL" ) || ( ( "${sv_Action}" = "UNINSTALL" ) && ( ( ${sv_ItemType} = "Executable" ) || ( ${sv_ItemType} = "Package" ) ) ) ) ]]
                  then
              
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: About to resolve the manifest file"



                    if [ -n "${sv_ManifestURIFileName}" ]
                    then
                      if [ -z "${sv_ManifestSrcPath}" ]
                      then
                        sv_ManifestURILocalPath=$(GLB_SF_RESOLVEFILEURITOPATH "${sv_ManifestURIPath}" "/usr/local/LabWarden/REPO")
                          
                        if [ -z "${sv_ManifestURILocalPath}" ]
                        then
                          GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - Manifest URI not resolvable ('${sv_ManifestURIPath}')"
                          break
                          
                        else

                          sv_ManifestSrcPath="${sv_ManifestURILocalPath}"
                                                
                          # ---
                          # Begin - check if manifest is an archive file (zip, tgz or dmg)
                          # If so, point the manifest source path to the unarchived or mounted directory

                          sv_ManifestSrcExt="$(echo ${sv_ManifestSrcPath} | grep '\.' | sed 's|.*\.||' | tr [a-z] [A-Z] )"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ManifestSrcExt '${sv_ManifestSrcExt}'"

                          case ${sv_ManifestSrcExt} in
                          ZIP)
                            # To unarchive:
                            #   cd SomeTempDirectory 
                            #   unzip ZIPFilePath

                            # Check if the source file is in the expected location
                            if [ -n "$(echo "${sv_ManifestSrcPath}" | grep "^/usr/local/LabWarden/REPO")" ]
                            then
                              sv_UnarchiveDirPath=$(dirname "${sv_ManifestSrcPath}")
                            else
                              sv_UnarchiveDirPath="$(mktemp -dq ${GLB_SV_THISSCRIPTTEMPDIRPATH}/XXXXXXXX)"
                              mkdir -p "${sv_UnarchiveDirPath}"
                            fi
                      
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Unarchiving ZIP Manifest ('${sv_ManifestURIPath}')"
                            cd "${sv_UnarchiveDirPath}"
                            unzip "${sv_ManifestSrcPath}"
                            sv_Err=$?
                            cd ~/
                            if [ ${sv_Err} -ne 0 ]
                            then
                              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - ZIP unarchive failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                              rm -fR "${sv_UnarchiveDirPath}"
                              break
                            fi
                      
                            # Check if we can remove the original source file
                            if [ -n "$(echo "${sv_ManifestSrcPath}" | grep "^/usr/local/LabWarden/REPO")" ]
                            then
                              rm -f "${sv_ManifestSrcPath}"
                            fi

                            sv_ManifestSrcPath="${sv_UnarchiveDirPath}"
                            ;;
                        
                          TGZ)
                            # Note, to create an archive:
                            #   cd SomedirectoryPath 
                            #   tar -c * | gzip -9 >"TGZFilePath"
                            # To unarchive:
                            #   cd SomeTempDirectory 
                            #   cat TGZFilePath | tar -xzf -
                  
                            # Check if the source file is in the expected location
                            if [ -n "$(echo "${sv_ManifestSrcPath}" | grep "^/usr/local/LabWarden/REPO")" ]
                            then
                              sv_UnarchiveDirPath=$(dirname "${sv_ManifestSrcPath}")
                            else
                              sv_UnarchiveDirPath="$(mktemp -dq ${GLB_SV_THISSCRIPTTEMPDIRPATH}/XXXXXXXX)"
                              mkdir -p "${sv_UnarchiveDirPath}"
                            fi
                      
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Unarchiving TGZ Manifest ('${sv_ManifestURIPath}')"
                            cd "${sv_UnarchiveDirPath}"
                            cat "${sv_ManifestSrcPath}" | tar -xzf -
                            sv_Err=$?
                            cd ~/
                            if [ ${sv_Err} -ne 0 ]
                            then
                              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - TGZ unarchive failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                              rm -fR "${sv_UnarchiveDirPath}"
                              break
                            fi
                      
                            # Check if we can remove the original source file
                            if [ -n "$(echo "${sv_ManifestSrcPath}" | grep "^/usr/local/LabWarden/REPO")" ]
                            then
                              rm -f "${sv_ManifestSrcPath}"
                            fi

                            sv_ManifestSrcPath="${sv_UnarchiveDirPath}"
                            ;;
                        
                          DMG)
                            if [ -z "${sv_DmgMountPoint}" ]
                            then
                              # Mount the DMG file
                              sv_DmgMountPoint="$(mktemp -dq ${GLB_SV_THISSCRIPTTEMPDIRPATH}/XXXXXXXX)"
                              sv_DmgSrcFilePath="${sv_ManifestSrcPath}"
                    
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Mounting DMG Manifest ('${sv_ManifestURIPath}')"
                              hdiutil attach "${sv_DmgSrcFilePath}" -mountpoint "${sv_DmgMountPoint}"
                              sv_Err=$?
                        
                              if [ ${sv_Err} -ne 0 ]
                              then
                                GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - Manifest DMG mount failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                                sv_DmgMountPoint=""
                                break
                              fi
                            fi
                            sv_ManifestSrcPath="${sv_DmgMountPoint}"
                            ;;
                            
                          *)
                            sv_ItemSrcPath="/$(basename "${sv_ManifestSrcPath}")"
                            sv_ManifestSrcPath=$(dirname "${sv_ManifestSrcPath}")
                            ;;
                    
                          esac
                  
                  
                          # End - check if manifest is an archive file (zip, tgz or dmg)
                          # ---
                          
                        fi

                      fi
                        
                    else
                      sv_ManifestURILocalPath=$(GLB_SF_RESOLVEFILEURITOPATH "${sv_ManifestURIPath}${sv_ItemSrcPath}" "/usr/local/LabWarden/REPO")

                      if [ -z "${sv_ManifestURILocalPath}" ]
                      then
                        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - Manifest URI not resolvable ('${sv_ManifestURIPath}${sv_ItemSrcPath}')"
                        break
                        
                      else
                        sv_ManifestSrcPath="${sv_ManifestURILocalPath}"

                        sv_ItemSrcPath="/$(basename "${sv_ManifestSrcPath}")"
                        sv_ManifestSrcPath=$(dirname "${sv_ManifestSrcPath}")
                      fi
                        
                    fi

GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ManifestURILocalPath '${sv_ManifestURILocalPath}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ManifestSrcPath '${sv_ManifestSrcPath}'"
GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: sv_ItemSrcPath '${sv_ItemSrcPath}'"

                    if [ ! -e "${sv_ManifestURILocalPath}" ]
                    then
                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Manifest ${sv_Action} aborted - Manifest file can not be found ('${sv_ManifestURIPath}')"
                      break
                    fi

                
                  fi
                fi
                  
                # ---
                # End download
                # ---
                 
                case ${sv_ItemType} in
              
                Package)
                  if [ ! -e "${sv_ManifestSrcPath}${sv_ItemSrcPath}" ]
                  then
                    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: ${sv_Action} aborted - Item ('${sv_ItemSrcPath}') not found in Manifest ('${sv_ManifestURIPath}')"
                    continue
                      
                  else
                    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action}ing '${sv_ItemSrcPath}'."
                    installer 2>&1 -pkg "${sv_ManifestSrcPath}${sv_ItemSrcPath}" -target / >> "${GLB_SV_LOGFILEPATH}"
                    sv_Err=$?
                    if [ ${sv_Err} -ne 0 ]
                    then
                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - '${sv_ItemType}' run failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                      continue
                    fi

                  fi
                  ;;
                
                Executable)
                  if [ ! -e "${sv_ManifestSrcPath}${sv_ItemSrcPath}" ]
                  then
                    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - Item ('${sv_ItemSrcPath}') not found in Manifest ('${sv_ManifestURIPath}')"
                    continue
                      
                  else
                    sv_ItemArgs="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:${sv_ItemType}:Args")"

                    # Do a software update
                    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Running ${sv_Action} executable ('${sv_ManifestSrcPath}${sv_ItemSrcPath}' ${sv_ItemArgs})"
                    eval "'${sv_ManifestSrcPath}${sv_ItemSrcPath}' ${sv_ItemArgs}"
                    sv_Err=$?
                    if [ ${sv_Err} -ne 0 ]
                    then
                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - '${sv_ItemType}' run failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                      continue
                    fi
                  fi
                  ;;
                    
                File|Application)
                  # Uninstall the item if it exists already
                  if [ -n "${sv_ItemDstPath}" ]
                  then
                    if [ -e "${sv_ItemDstPath}" ]
                    then
                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Removing '${sv_ItemType}' at '${sv_ItemDstPath}'"
                      if [ -d "${sv_ItemDstPath}" ]
                      then
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "rm -fR ${sv_ItemDstPath}"
                        rm -fR "${sv_ItemDstPath}"
                      else
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "rm -f ${sv_ItemDstPath}"
                        rm -f "${sv_ItemDstPath}"
                      fi
                    fi
                  fi

                  if [ "${sv_Action}" = "INSTALL" ]
                  then
                        
                    if [ ! -e "${sv_ManifestSrcPath}${sv_ItemSrcPath}" ]
                    then
                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - Item ('${sv_ItemSrcPath}') not found in Manifest ('${sv_ManifestURIPath}')"
                      continue
                  
                    else
                      sv_ItemOwner="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:${sv_ItemType}:Owner")"
                      if [ -z "${sv_ItemOwner}" ]
                      then
                        sv_ItemOwner="root"
                      fi
                      sv_ItemGroup="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:${sv_ItemType}:Group")"
                      if [ -z "${sv_ItemGroup}" ]
                      then
                        sv_ItemGroup="wheel"
                      fi
                      sv_ItemMode="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config${sv_ManifestRoot}:Item:${iv_ItemIndex}:${sv_ItemType}:Mode")"
                      if [ -z "${sv_ItemMode}" ]
                      then
                        sv_ItemMode="og-w"
                      fi

                      if [ ! -d "${sv_ItemDstDir}" ]
                      then
                        GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Creating destination dir '${sv_ItemDstDir}'"
                        # At some point, maybe think about setting permissions according to owner/group/mode above
                        mkdir -p "${sv_ItemDstDir}"
                      fi

                      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: ${sv_Action}ing '${sv_ItemType}' '${sv_ItemDstPath}'"

#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "cp -pR ${sv_ManifestSrcPath}${sv_ItemSrcPath} ${sv_ItemDstDir}"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "chown -R ${sv_ItemOwner}:${sv_ItemGroup} ${sv_ItemDstPath}"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELDEBUG} "chmod -R ${sv_ItemMode} ${sv_ItemDstPath}"

                      if [ -d "${sv_ManifestSrcPath}${sv_ItemSrcPath}" ]
                      then
                        cp -pR "${sv_ManifestSrcPath}${sv_ItemSrcPath}" "${sv_ItemDstDir}"
                        sv_Err=$?
                        if [ ${sv_Err} -ne 0 ]
                        then
                          GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - '${sv_ItemType}' copy failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                          # Tidy up after a failed copy
                          rm -fR "${sv_ItemDstPath}"
                          continue
                        fi
                        chown -R ${sv_ItemOwner}:${sv_ItemGroup} "${sv_ItemDstPath}"
                        chmod -R ${sv_ItemMode} "${sv_ItemDstPath}"
                        
                      else
                        cp -p "${sv_ManifestSrcPath}${sv_ItemSrcPath}" "${sv_ItemDstDir}"
                        sv_Err=$?
                        if [ ${sv_Err} -ne 0 ]
                        then
                          GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELERR} "Manifest ${iv_ManifestIndex}: Item ${iv_ItemIndex}: Item ${sv_Action} aborted - '${sv_ItemType}' copy failed with error ${sv_Err} ('${sv_ManifestURIPath}')"
                          # Tidy up after a failed copy
                          rm -f "${sv_ItemDstPath}"
                          continue
                        fi
                        chown ${sv_ItemOwner}:${sv_ItemGroup} "${sv_ItemDstPath}"
                        chmod ${sv_ItemMode} "${sv_ItemDstPath}"
                 
                      fi
                    fi
                  fi
                  ;;
                    
                esac
              fi
              
            fi

            # done running through the manifest items
          done
                
          # ---
          # Unmount if a DMG file is mounted
          if [ -n "${sv_DmgMountPoint}" ]
          then
            GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Unmounting DMG Manifest ('${sv_ManifestURIPath}')"
            hdiutil detach "${sv_DmgMountPoint}"
          fi

          # ---
          # Check if we should remove the manifest file
          if [ -n "$(echo "${sv_ManifestURILocalPath}" | grep "^/usr/local/LabWarden/REPO")" ]
          then
            if [ ${sv_Err} -eq 9999 ]
            then
              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Keeping Manifest in repository for later ('${sv_ManifestURILocalPath}')"
            else
              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Manifest ${iv_ManifestIndex}: Deleting Manifest from repository ('${sv_ManifestURILocalPath}')"
              rm -f "${sv_ManifestURILocalPath}"
              find /usr/local/LabWarden/REPO -depth 1 -empty -type d -delete
            fi
          fi


        fi
      fi
    fi
      
    # Release lock
    GLB_NF_NAMEDLOCKRELEASE "${GLB_SV_THISSCRIPTFILENAME}"
  fi

    done
    # done counting through the manifest list
    
  fi
}

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-PolicyUninstall)
  bf_RunAction "UNINSTALL"
  ;;
  
Sys-PolicyInstall)
  # bf_RunAction "INSTALL"
  ;;

Sys-Idle|Sys-LoginWindowIdle)
  bf_RunAction "INSTALL"
  ;;
  
Sys-ManualTrigger)
  # Manual install requested via /usr/local/LabWarden/bin/ManualSoftwareInstall
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Running a manual install."
  bf_RunAction "INSTALL"
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
