#!/bin/bash
#
# Short:    Sys Policy script - Will restart when woken from a long sleep
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Triggered by the following events:
#   Sys-WillSleep (as root)
#   Sys-WillWake  (as root)
#
# Called as follows:    
#   Sys-RestartAfterLongSleep <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" != "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.5"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

case ${GLB_SV_EVENTNAME} in
    
Sys-WillSleep)
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_POLICYPREFSFILEPATH}" ":${GLB_SV_CONFIGUUID}:Prefs:LastSleepEpoch" ${GLB_IV_THISSCRIPTSTARTEPOCH}
  ;;
  
Sys-WillWake)
  iv_LastSleepEpoch="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_POLICYPREFSFILEPATH}" ":${GLB_SV_CONFIGUUID}:Prefs:LastSleepEpoch")"
  if test -z "${iv_LastSleepEpoch}"
  then
    iv_LastSleepEpoch=0
  fi
  
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_POLICYPREFSFILEPATH}" ":${GLB_SV_CONFIGUUID}:Prefs:LastSleepEpoch" 0
  
  iv_LongSleepMins="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:LongSleepMins")"
  if test -n "${iv_LongSleepMins}"
  then
  
    if [ $((${GLB_IV_THISSCRIPTSTARTEPOCH}-${iv_LastSleepEpoch})) -gt $((${iv_LongSleepMins}*60)) ]
    then
      # Restart if we have just woken from a long sleep
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Just woken from a long sleep - we need to restart."
      GLB_NF_NAMEDFLAGCREATE "Restart"
    else
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Just woken from a short sleep."
    fi
  
  fi
  ;;

Sys-PolicyInstall|Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
