#!/bin/bash
#
# Short:    Usr Policy script - Enable or disable Spotlight on a users network home
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Usr-AtDesktop (as user)
#
# Called as follows:    
#   Usr-SpotlightSettingOnNetHome <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" = "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---


# ---

if [ "${GLB_BV_CONSOLEUSERISLOCAL}" = ${GLB_BC_TRUE} ]
then
  # Exit if user account is local
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Policy aborted - User account is local."
else
  if [ -z "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" ]
  then
    # Exit if the Network home is undefined or the share is unavailable
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Network home is undefined or the share is unavailable."
  else
    if [ ! -e "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" ]
    then
      # Exit if the Network home doesn't exist or is unavailable
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Network home doesn't exist or is unavailable."
    else
    
# ---

case ${GLB_SV_EVENTNAME} in
    
Usr-AtDesktop|Usr-PolicyInstall)
  bv_SpotlightEnabled="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:SpotlightEnabled")"
  
  if [ "${bv_SpotlightEnabled}" = ${GLB_BC_TRUE} ]
  then
    if [ "$(mdutil -s "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" | grep "Indexing" | tr -d "." | tr " " "\n" | tail -n1)" = "disabled" ]
    then
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Enabling Spotlight on network home."
  
      rm -f "${GLB_SV_CONSOLEUSERSHAREDIRPATH}/.metadata_never_index"

      # switch on spotlight for folder
      mdutil -i on "${GLB_SV_CONSOLEUSERSHAREDIRPATH}"

    else
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Spotlight is already enabled - there's nothing to do."

    fi
 
  else
    if [ "$(mdutil -s "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" | grep "Indexing" | tr -d "." | tr " " "\n" | tail -n1)" = "disabled" ]
    then
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Spotlight is already disabled - there's nothing to do."

    else
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Disabling Spotlight on network home."
  
      # tell the system never to index the folder
      touch "${GLB_SV_CONSOLEUSERSHAREDIRPATH}/.metadata_never_index"

      # switch off spotlight for folder
      mdutil -i off "${GLB_SV_CONSOLEUSERSHAREDIRPATH}"
    fi
    
    if [ -d "${GLB_SV_CONSOLEUSERSHAREDIRPATH}/.Spotlight-V100" ]
    then
      # remove redundant indexing data
      rm -fR "${GLB_SV_CONSOLEUSERSHAREDIRPATH}/.Spotlight-V100"
    fi
  fi
  ;;

Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac

# ---

    fi
  fi
fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
