#!/bin/bash
#
# Short:    Usr Policy script - Attempts to fix Keychain issues caused by password reset issues
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Usr-AtDesktop           (as user)
#
# Called as follows:    
#   Usr-KeychainFix <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" = "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

# Exit if the user home folder doesn't exist
if [ ! -e "${GLB_SV_CONSOLEUSERHOMEDIRPATH}" ]
then
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - home folder doesn't exist."
else

# ---

case ${GLB_SV_EVENTNAME} in
    
Usr-AtDesktop)
  # User home exists and is available
    
  # Fix for if you hit "Continue Log In" when you are asked to update your keychain password.
  # (When your Login password does not match your keychain password)

  # Needs to be done Usr-AtDesktop, because the keychain isn't unlocked until after login

  # Check if Keychain is unlocked.
  if test -z "$(security 2>&1 unlock-keychain -p "" "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Keychains/login.keychain")"
  then
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "The keychain is fine - there's nothing to do."
    
  else
    GLB_NF_SHOWNOTIFICATION ${GLB_IC_MSGLEVELNOTICE} "Creating new keychain and logging off. Please login again."
  
    # Keychain will not unlock, so delete known keychains and hope for the best
    # Not ideal really.
    rm -fR "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Keychains"

    # applescript to restart
    /usr/bin/osascript << EOF
ignoring application responses
tell application "System Events"
restart
end tell
end ignoring
EOF

  fi
  ;;

Usr-PolicyInstall|Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
