#!/bin/bash
#
# Short:    Usr Policy script - Checks if a users network drive is getting full
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Usr-Poll (as user)
#
# Called at regular intervals as follows:    
#   Usr-CheckQuotaOnNetHome <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" = "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

if [ "${GLB_BV_CONSOLEUSERISLOCAL}" = ${GLB_BC_TRUE} ]
then
  # Exit if user account is local
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "Policy aborted - User account is local."
else
  if [ -z "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" ]
  then
    # Exit if the user home is undefined or the share is unavailable
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Network home is undefined or the share is unavailable."
  else
    if [ ! -e "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" ]
    then
      # Exit if the Network home doesn't exist or is unavailable
      GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Network home doesn't exist or is unavailable."
    else
    
# ---

case ${GLB_SV_EVENTNAME} in
    
Usr-Poll)
  iv_QuotaMegs=$(df -hm "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" | awk 'NR==2 {print $2}')
  iv_FreeMegs=$(df -hm "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" | awk 'NR==2 {print $4}')

  if [ ${iv_FreeMegs} -lt 100 ]
  then
    GLB_NF_SHOWNOTIFICATION ${GLB_IC_MSGLEVELWARN} "Your network space is low. You have ${iv_FreeMegs} MB left out of ${iv_QuotaMegs} MB."
  else
    GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "User Network Home storage is fine - nothing to do. ${iv_FreeMegs} MB left out of ${iv_QuotaMegs} MB."
  fi
  ;;

Usr-PolicyInstall|Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---
    
    fi
  fi
fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
