#!/bin/bash
#
# Short:    App Policy script - Shows a hint when a specified application opened
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Triggered by the following events:
#   Usr-AppDidLaunch (as user)
#
# Called as follows:    
#   Usr-AppShowHints <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" = "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.2.5"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.
# Look at '/inc-sh/Common.sh' for a complete list.

# ---

case ${GLB_SV_EVENTNAME} in
    
Usr-AppDidLaunch)
  sv_ApplicationBundleIdentifier="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:ApplicationBundleIdentifier")"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "sv_ApplicationBundleIdentifier '${sv_ApplicationBundleIdentifier}'"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER '${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}'"
  if [ "${sv_ApplicationBundleIdentifier}" = "${GLB_SV_LAUNCHEDAPPBUNDLEIDENTIFIER}" ]
  then
    iv_HintCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHints")"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "iv_HintCount '${iv_HintCount}'"
    if [ ${iv_HintCount} -gt 0 ]
    then
      iv_HintIndex=$(jot -r 1 0 $((${iv_HintCount}-1)))
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "iv_HintIndex '${iv_HintIndex}'"

      # Get message content
      sv_HintContent="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:AppHints:${iv_HintIndex}")"
#GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELINFO} "sv_HintContent '${sv_HintContent}'"

      if test -n "${sv_HintContent}"
      then
        GLB_NF_SHOWNOTIFICATION ${GLB_IC_MSGLEVELNOTICE} "${sv_HintContent}"
      fi

    fi
  fi
  ;;

Usr-PolicyInstall|Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
