#!/bin/bash
#
# Short:    Usr Policy script - Creates folders in the users home folder
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Triggered by the following events:
#   Usr-ConsoleUserLoggedIn (as user)
#   Usr-AtDesktop           (as user)
#
# Called as follows:    
#   Usr-CreateFolder <PolicyName> <EventName> <OptionalParam> <ConsoleUserInfo> <ConfigUUID> <ConfigFilePath> <PolicyPrefsFilePath> <SharedPrefsFilePath> <SysDefaultsConfigFilePath> <LogInfo>

# ---

if [ "$(whoami)" = "root" ]
then
  exit 0
fi

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# Define the policy code version
GLB_SV_CODEVERSION="3.3.0"

# Define a list of policies that replace this one
GLB_SV_DEPRECATEDBYPOLICYLIST=""

# ---

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyHeader.sh

# By the time we get here, quite a few global variables have been set up.

# ---

# Exit if the user home folder doesn't exist
if [ ! -e "${GLB_SV_CONSOLEUSERHOMEDIRPATH}" ]
then
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - home folder doesn't exist."
else

# ---

case ${GLB_SV_EVENTNAME} in
    
Usr-ConsoleUserLoggedIn|Usr-PolicyInstall)
  # Create Required folders where necessary
  iv_ObjectCount="$(GLB_IF_GETPLISTARRAYSIZE "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Path")"

  for (( iv_LoopCount=0; iv_LoopCount<${iv_ObjectCount}; iv_LoopCount++ ))
  do
    sv_ReqdObjectFilePath="$(GLB_SF_GETPLISTPROPERTY "${GLB_SV_CONFIGFILEPATH}" ":${GLB_SV_CONFIGUUID}:Config:Path:${iv_LoopCount}")"

    # Sanitise the Entry
    sv_ReqdObjectFilePath=$(echo "${sv_ReqdObjectFilePath}" | sed "s|^|/|;s|^/[/]*|/|;s|[/]*$||")

    if test -n "${sv_ReqdObjectFilePath}"
    then

# ----------
# BEGIN LEGACY CONFIG SUPPORT (PRE 3.X)

      # Remove network home link that the previous version of the code used to create
      if test -n "$(echo "${sv_ReqdObjectFilePath}" | grep -E "/NETWORKHOME$")"
      then
        if test -n "${GLB_SV_CONSOLEUSERSHAREDIRPATH}"
        then
          if [ "${GLB_SV_CONSOLEUSERSHAREDIRPATH}" != "${GLB_SV_CONSOLEUSERHOMEDIRPATH}" ]
          then
            if [ -L "${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}" ]
            then
              GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Deleting link ${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}"
              rm -f "${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}"
            fi
          fi
        fi
      else
      
# END LEGACY CONFIG SUPPORT (PRE 3.X) 
# ----------

        # Only create the folder if it doesn't already exist
        if ! test -e "${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}"
        then
          GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELNOTICE} "Creating folder ${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}"
          /bin/mkdir -p "${GLB_SV_CONSOLEUSERHOMEDIRPATH}${sv_ReqdObjectFilePath}"
        fi
        
# ----------
# BEGIN LEGACY CONFIG SUPPORT (PRE 3.X)

      fi
      
# END LEGACY CONFIG SUPPORT (PRE 3.X) 
# ----------
      
    fi
  done

  # Update Sys-LoginWindow.plist file
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Preferences/loginwindow.plist" ":BuildVersionStampAsNumber" "${GLB_IV_BUILDVERSIONSTAMPASNUMBER}"
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Preferences/loginwindow.plist" ":BuildVersionStampAsString" "${GLB_SV_BUILDVERSIONSTAMPASSTRING}"
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Preferences/loginwindow.plist" ":SystemVersionStampAsNumber" "${GLB_IV_SYSTEMVERSIONSTAMPASNUMBER}"
  GLB_NF_SETPLISTPROPERTY "${GLB_SV_CONSOLEUSERHOMEDIRPATH}/Library/Preferences/loginwindow.plist" ":SystemVersionStampAsString" "${GLB_SV_SYSTEMVERSIONSTAMPASSTRING}"
  ;;

Usr-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_NF_LOGMESSAGE ${GLB_IC_MSGLEVELWARN} "Policy aborted - Trigger '${GLB_SV_EVENTNAME}' is not supported."
  ;;

esac
  
# ---

fi

# ---

# Tidy up

. "${GLB_SV_PROJECTDIRPATH}"/inc-sh/PolicyFooter.sh

# ---
