#!/bin/bash
#
# Short:    Utility Script - Perform a Group Policy update
# Author:   Mark J Swift
# Version:  2.0.13
# Modified: 12-Jun-2017
#
# Called as follows:    
#   gpupdate [-force|-quick] [<user>]
#
# Without a user specified, updates the group policies for the workstation.
# With a user, updates the group policies for the specified user.

# ---

sv_CodeVersion="2.0.13"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Common.sh
fi

# ---

sv_GPoption="$(echo ${1} | tr [A-Z] [a-z])"

case "${sv_GPoption}" in
-force|-quick|-default)
  sv_GPOuser=${2}
  ;;

*)
  sv_GPoption="-default"
  sv_GPOuser=${1}
  ;;
    
esac

# ---

if [ "${GLB_sv_ThisUserName}" = "root" ]
then
  # If a config has never been set up for this workstation, create base folders and set access rights
  if ! test -e "${GLB_sv_ProjectConfigDirPath}/Cache"
  then
    # Create base folders
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/Users"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/Users"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Active/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Active/Users"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/Users"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/Users"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Config/Global"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Config/Computers"
    mkdir -p "${GLB_sv_ProjectConfigDirPath}/Config/Users"
    
    # Set access rights
    chown -R root:wheel "${GLB_sv_ProjectConfigDirPath}"
    chmod -R 755 "${GLB_sv_ProjectConfigDirPath}"
    
    # Force gpupdate
    sv_GPoption="-force"
  fi
fi

# ---

case "${sv_GPoption}" in
-force)
  # Update if policy doesn't exist or is older than this (1 minute)
  iv_GPCacheMaxAgeMinutes=${GLB_iv_GPforceAgeMinutes}
  ;;

-quick)
  # Update if policy doesn't exist or is older than this (180 days)
  iv_GPCacheMaxAgeMinutes=${GLB_iv_GPquickAgeMinutes}
  ;;
    
*)
  # Update if policy doesn't exist or is older than this (1 day old)
  iv_GPCacheMaxAgeMinutes=${GLB_iv_GPdefaultAgeMinutes}
  ;;
    
esac

# ---

if [ "${GLB_sv_ThisUserName}" = "root" ]
then
  if test -z "${sv_GPOuser}"
  then
    # If we are root and we didn't supply a user, Update/apply user policies (as root) for all users who are logged in
    who -q | grep -Ev "^#" | tr " " "\n" | sort -u | grep -Ev "^$" | grep -Ev "^root$" | while read sv_GPOuser
    do
      "${0}" "${sv_GPoption}" "${sv_GPOuser}"
    done
    
    sv_GPOuser=""
  fi

else
  # If we are not root, we can only update policies for ourself
  sv_GPOuser="${GLB_sv_ThisUserName}"
  
fi

# ---

sf_BuildGroupMembershipCache() # <Context> <ObjectName> - List object membership. Context can be Users, Computers or Groups.
{
  local sv_ObjectContext
  local sv_ObjectName
  local sv_NameDelim
  local sv_GroupName
  local sv_SubGroupName
  local iv_CacheEpoch
  local sv_Temp1FilePath
  local sv_Attr
  local sv_Value
  local iv_Err

  sv_ObjectContext=${1}
  sv_ObjectName=${2}
  
  case "${sv_ObjectContext}" in
  Computers)
    sv_NameDelim="$"
    ;;

  Users|Groups)
    sv_NameDelim=""
    ;;
    
  *)
    exit 0
    ;;
    
  esac
  
  iv_CacheEpoch=0
  if test -e "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"
  then
    iv_CacheEpoch=$(stat -f "%m" "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt")
  fi
  
  if [ $((${GLB_iv_ThisScriptStartEpoch}-${iv_CacheEpoch})) -lt $((${iv_GPCacheMaxAgeMinutes}*60)) ]
  then
    cat "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"

  else
    sv_Temp0FilePath=$(mktemp "${GLB_sv_ThisScriptTempDirPath}/XXXXXXXX")
    
    # Get the memberOf field from AD 
    #dscl 2>/dev/null localhost -read "/Search/${sv_ObjectContext}/${sv_ObjectName}${sv_NameDelim}" memberOf > "${sv_Temp0FilePath}"
    
    sv_Attr="memberOf";sv_Value="$(dscl 2>/dev/null localhost -read "/Search/${sv_ObjectContext}/${sv_ObjectName}${sv_NameDelim}" ${sv_Attr})";iv_Err=$?;sv_Value="$(echo "${sv_Value}" | sed "s|^[^:]*:${sv_Attr}:| ${sv_Attr}: |" | tr -d "\r" | tr "\n" "\r" | sed 's| '${sv_Attr}': |\
|'g | tail -n1 | tr "\r" "\n" | sed '/^\s*$/d')";echo "${sv_Value}" > "${sv_Temp0FilePath}"

    if [ ${iv_Err} -ne 0 ]
    then
      GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Cannot get ${sv_ObjectContext} ${sv_ObjectName} 'memberOf' field from AD."
      if test -e "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"
      then
        GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} " using cached ${sv_ObjectContext} ${sv_ObjectName} 'memberOf' field."
        cat "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"
      fi
      
    else
      GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Just read ${sv_ObjectContext} ${sv_ObjectName} 'memberOf' field from AD."
    
      sv_Temp1FilePath=$(mktemp "${GLB_sv_ThisScriptTempDirPath}/XXXXXXXX")
      touch "${sv_Temp1FilePath}"

      cat "${sv_Temp0FilePath}" | tr -d "\n" | sed "s|dsAttrTypeNative:memberOf:||g;s| CN=|:|g;s|^:||" | tr ":" "\n" | cut -d"," -f1 | sort -u | while read sv_GroupName
      do
        echo "${sv_GroupName}"
        echo "${sv_GroupName}">>"${sv_Temp1FilePath}"
        sf_BuildGroupMembershipCache "Groups" "${sv_GroupName}" | while read sv_SubGroupName
        do
          if [ "${sv_SubGroupName}" = "${sv_ObjectName}" ]
          then
            break
          
          else
            echo "${sv_SubGroupName}"
            echo "${sv_SubGroupName}">>"${sv_Temp1FilePath}"
          
          fi
        done
      done
      rm -f "${sv_Temp0FilePath}"
    
      sv_Temp2FilePath=$(mktemp "${GLB_sv_ThisScriptTempDirPath}/XXXXXXXX")
      chmod 644 "${sv_Temp2FilePath}"
    
      cat "${sv_Temp1FilePath}" | sort -u >"${sv_Temp2FilePath}"
      rm -f "${sv_Temp1FilePath}"

      mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}"
      chmod 755 "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}"
    
      ln -fh "${sv_Temp2FilePath}" "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"
      rm -f "${sv_Temp2FilePath}"
      
      if [ "${sv_ObjectContext}" = "Groups" ]
      then
        # Get the Info (Notes) field from AD 
#        dscl 2>/dev/null localhost -read "/Search/${sv_ObjectContext}/${sv_ObjectName}${sv_NameDelim}" info | sed "s|dsAttrTypeNative:info:||" | sed "s|^[ ]*||" | sed "s|[ ]*$||" | tr -s "\n" > "${sv_Temp1FilePath}"

        sv_Attr="info";sv_Value="$(dscl 2>/dev/null localhost -read "/Search/${sv_ObjectContext}/${sv_ObjectName}${sv_NameDelim}" ${sv_Attr})";iv_Err=$?;sv_Value="$(echo "${sv_Value}" | sed "s|^[^:]*:${sv_Attr}:| ${sv_Attr}: |" | tr -d "\r" | tr "\n" "\r" | sed 's| '${sv_Attr}': |\
|'g | tail -n1 | tr "\r" "\n" | sed '/^\s*$/d')";echo "${sv_Value}" > "${sv_Temp1FilePath}"

        if [ ${iv_Err} -ne 0 ]
        then
          GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Cannot get ${sv_ObjectContext} ${sv_ObjectName} 'info' (Notes) field from AD (maybe it hasn't connected yet)."
          
        else
          GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Just read ${sv_ObjectContext} ${sv_ObjectName} 'info' (Notes) field from AD."
          
          # Keep the file if the Info field is not empty
          if test -s "${sv_Temp1FilePath}"
          then
            touch -t $(date -r ${GLB_iv_ThisScriptStartEpoch} "+%Y%m%d%H%M.%S") "${sv_Temp1FilePath}"
            chmod 644 "${sv_Temp1FilePath}"
            mkdir -p "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/${sv_ObjectContext}"
            chmod 755 "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/${sv_ObjectContext}"
#            ln -fh "${sv_Temp1FilePath}" "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/${sv_ObjectContext}/${sv_ObjectName}.txt"
            mv -f "${sv_Temp1FilePath}" "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/${sv_ObjectContext}/${sv_ObjectName}.txt"
          fi
        fi
        rm -f "${sv_Temp1FilePath}"
        
      fi

    fi

  fi
  
}

sf_ListGroups() # <Context> <ObjectName> - List object membership. Context can be Users, Computers or Groups.
{
  local sv_ObjectContext
  local sv_ObjectName

  sv_ObjectContext=${1}
  sv_ObjectName=${2}

  sf_BuildGroupMembershipCache "${sv_ObjectContext}" "${sv_ObjectName}" | sort -u
  
}

# ---

# Here we start for real

# ---

if test -z "${sv_GPOuser}"
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "${GLB_sv_ThisScriptFileName} ${sv_GPoption}  (version ${sv_CodeVersion})"
else
  GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "${GLB_sv_ThisScriptFileName} ${sv_GPoption} '${sv_GPOuser}'  (version ${sv_CodeVersion})"
fi

# ---

if test -n "${sv_GPOuser}"
then
  sv_ObjectContext="Users"
  sv_ObjectName="${sv_GPOuser}"

else
  sv_ObjectContext="Computers"
  sv_ObjectName="${GLB_sv_Hostname}"
  
fi

case "${sv_ObjectContext}" in
Computers)
  sv_NameDelim="$"
  ;;

Users|Groups)
  sv_NameDelim=""
  ;;
    
*)
  exit 0
  ;;
    
esac
 
sv_ConfigDirPath="${GLB_sv_ProjectConfigDirPath}/Config/${sv_ObjectContext}/${sv_ObjectName}"

if [ "${GLB_sv_ThisUserName}" = "root" ]
then

  if ! test -e "${sv_ConfigDirPath}"
  then
    mkdir -p "${sv_ConfigDirPath}"
    chown -R root:wheel "${sv_ConfigDirPath}"
    chmod -R 755 "${sv_ConfigDirPath}"
#    GLB_nf_SetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":LabWarden:LocalPrefs:InstallEpoch" "${GLB_iv_ThisScriptStartEpoch}"
  fi

  # --- check if we should update payloads from AD

  if test -z "${GLB_sv_ADDomainNameDNS}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Not updating payloads from AD - this workstation may not be bound to an AD domain"
    
  else
  
    if [ "${GLB_bv_LoadConfigsFromADnotes}" = "false" ]
    then
      GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Not updating payloads from AD - workstation defaults specify not to"
      
    else
    
      mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}"
      chmod 755 "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}"

      mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/UnInstall/${sv_ObjectContext}/${sv_ObjectName}"
      chmod 755 "${GLB_sv_ProjectConfigDirPath}/Policies/UnInstall/${sv_ObjectContext}/${sv_ObjectName}"

      mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}"
      chmod 755 "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}"

      mkdir -p "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}"
      chmod 755 "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}"

      # ---

      bv_UpdatePoliciesFromAD="false"
    
      iv_ObjectEpoch=0
      if test -e "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt"
      then
        iv_ObjectEpoch=$(stat -f "%m" "${GLB_sv_ProjectConfigDirPath}/Cache/MemberOf/${sv_ObjectContext}/${sv_ObjectName}.txt")
      fi
  
      if [ $((${GLB_iv_ThisScriptStartEpoch}-${iv_ObjectEpoch})) -gt $((${iv_GPCacheMaxAgeMinutes}*60)) ]
      then
        # The cache has aged out - so lets look to see if we can update the object from AD
        if test -z "${GLB_sv_IPv4PrimaryService}"
        then
          # we need a network
          GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "No network - not updating payloads from AD"
      
        else
          if [ "${GLB_sv_ADDomainNameDNS}" != "${GLB_sv_NetworkServiceDHCPOption15}" ]
          then
            # we need to be on the domains network
            GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Not on ${GLB_sv_ADDomainNameFlat} network - not updating payloads from AD"
        
          else
            bv_UpdatePoliciesFromAD="true"

          fi
        fi
      fi
        
      if [ "${bv_UpdatePoliciesFromAD}" = "false" ]
      then
        # --- Lets just verify if the already installed AD payloads are still active

        # First check if we have already recently done this
        iv_LastCheckEpoch=0
        if test -e "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}"
        then
          iv_LastCheckEpoch=$(stat -f "%m" "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}")
        fi

        if [ $((${GLB_iv_ThisScriptStartEpoch}-${iv_LastCheckEpoch})) -gt $((${iv_GPCacheMaxAgeMinutes}*60)) ]
        then
          # Get the dst (existing) payload
          ls -1 "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}" > "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt"

          # Update list of policies to verify as still active
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt" | while read sv_PayloadFileName
          do
            ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
          done
      
          # Delete temporary file
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt"
      
        fi
      
      else
        # --- Lets try to update the payloads from AD
      
        dscl >/dev/null 2>&1 localhost -read /Search/${sv_ObjectContext}/${sv_ObjectName}${sv_NameDelim} name
        if [ $? -ne 0 ]
        then
          # the object needs to exist in AD
          GLB_nf_logmessage ${GLB_iv_MsgLevelWarn} "Cannot find ${sv_ObjectContext} ${sv_ObjectName} in AD. Might be too soon after restart."
                    
        else
          # Fill a directory with the objects info payload(s)
          GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Filling a directory with the objects info payload(s)"
          
          sv_UpdatedInfoPayloadDirPath=$(mktemp -d "${GLB_sv_ThisScriptTempDirPath}/XXXXXXXX")

          sf_ListGroups "${sv_ObjectContext}" "${sv_ObjectName}" | while read sv_ObjectGroup
          do
            if test -e "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/Groups/${sv_ObjectGroup}.txt"
            then
          
#              mv -f "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/Groups/${sv_ObjectGroup}.txt" "${sv_UpdatedInfoPayloadDirPath}/${sv_ObjectGroup}.txt"
          
              ln -fh "${GLB_sv_ProjectConfigDirPath}/Cache/Notes/Groups/${sv_ObjectGroup}.txt" "${sv_UpdatedInfoPayloadDirPath}/${sv_ObjectGroup}.txt"
            fi
          done

          # Join split info payloads into a single file - if the joined file already exists, it will be overwritten
          GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Joining split info payloads into a new file"
          cd "${sv_UpdatedInfoPayloadDirPath}"
          ls -1 "${sv_UpdatedInfoPayloadDirPath}" | grep -E "\-[0-9]{1}.txt$" | sed -E "s|(.*)(-[0-9]{1}.txt$)|\1|" | sort -u | while read sv_GroupName
          do
            # If the joined file doesn't exist, create a new file from the split parts
#            if ! test -e "${sv_UpdatedInfoPayloadDirPath}/${sv_GroupName}.txt"
#            then
              cat $(ls -1 "${sv_UpdatedInfoPayloadDirPath}" | grep -E "${sv_GroupName}-[0-9]{1}.txt$" | sort) > "${sv_UpdatedInfoPayloadDirPath}/${sv_GroupName}.txt"
              touch -t $(date -r ${GLB_iv_ThisScriptStartEpoch} "+%Y%m%d%H%M.%S") "${sv_UpdatedInfoPayloadDirPath}/${sv_GroupName}.txt"
#            fi
          done

          # Delete split payloads
          GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Deleting remaining split payloads"
          find "${sv_UpdatedInfoPayloadDirPath}" -iregex '.*\-[0-9]\{1\}.txt$' -exec rm -f "{}" \;

          # Unpack the info payload content
          GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Unpacking the info payload content"
          sv_UpdatedPayloadContentDirPath=$(mktemp -d "${GLB_sv_ThisScriptTempDirPath}/XXXXXXXX")

          cd "${sv_UpdatedPayloadContentDirPath}"
          ls -1 "${sv_UpdatedInfoPayloadDirPath}" | while read sv_InfoPayloadName
          do
            cat "${sv_UpdatedInfoPayloadDirPath}/${sv_InfoPayloadName}" | base64 2>/dev/null -D | tar 2>/dev/null -xvzf -
          done
          chown -R root:wheel "${sv_UpdatedPayloadContentDirPath}"

          # Installing/uninstalling mobileconfigs for other users, is not supported prior to 10.11
          # so normal users will have to be able to uninstall.
          if [ "${sv_ObjectContext}" = "Users" ]
          then
            if [ ${GLB_iv_SystemVersionStampAsNumber} -lt 168493056 ]
            then
              GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Modifying mobileconfigs to allow pre MacOS 10.11 users uninstall rights"
              ls -1 "${sv_UpdatedPayloadContentDirPath}" | grep -E ".*\.mobileconfig" | while read sv_PayloadContentName
              do
                iv_PayloadContentEpoch=$(stat -f "%m" "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadContentName}")
                /usr/libexec/PlistBuddy -c "Delete ':PayloadRemovalDisallowed'" "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadContentName}"
                touch -t $(date -r ${iv_PayloadContentEpoch} "+%Y%m%d%H%M.%S") "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadContentName}"
              done
            fi
          fi

          # ---


          # Here we decide what needs to be installed, uninstalled, and verified

          cd "${GLB_sv_ThisScriptTempDirPath}"

          # Get the src payload
          ls -1 "${sv_UpdatedPayloadContentDirPath}" > "${GLB_sv_ThisScriptTempDirPath}/Policies-src.txt"

          # Get the dst (existing) payload
          ls -1 "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}" > "${GLB_sv_ThisScriptTempDirPath}/Policies-dst.txt"

          # Build a list of payloads that are in src or dst, but not in both
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-src.txt" "${GLB_sv_ThisScriptTempDirPath}/Policies-dst.txt" | sort | uniq -u > "${GLB_sv_ThisScriptTempDirPath}/Policies-uniq.txt"

          # Build a list of payloads unique to the dst (need to be uninstalled)
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-uniq.txt" "${GLB_sv_ThisScriptTempDirPath}/Policies-dst.txt" | sort | uniq -d > "${GLB_sv_ThisScriptTempDirPath}/Policies-uninstall.txt"

          # Build a list of payloads unique to the src (need to be installed)
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-uniq.txt" "${GLB_sv_ThisScriptTempDirPath}/Policies-src.txt" | sort | uniq -d > "${GLB_sv_ThisScriptTempDirPath}/Policies-install.txt"

          # Build a list of payloads that are in src and dst (need to check if updated, and possibly need to be uninstalled or verified)
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-src.txt" "${GLB_sv_ThisScriptTempDirPath}/Policies-dst.txt" | sort | uniq -d > "${GLB_sv_ThisScriptTempDirPath}/Policies-check.txt"

          # Check if payload is same (verify) or updated (uninstall/install)
          touch "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt"
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-check.txt" | while read sv_PayloadFileName
          do
            sv_ActivePayloadShaSum="$(shasum -a 256 "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" | cut -d" " -f1)"
            sv_UpdatedPayloadShaSum="$(shasum -a 256 "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadFileName}" | cut -d" " -f1)"
            if [ "${sv_ActivePayloadShaSum}" = "${sv_UpdatedPayloadShaSum}" ]
            then
              # Payload has not been updated, so just needs to be verified as still active
              echo "${sv_PayloadFileName}" >> "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt"
              
            else
              # Payload has not updated, so needs to be uninstalled and re-installed
              echo "${sv_PayloadFileName}" >> "${GLB_sv_ThisScriptTempDirPath}/Policies-uninstall.txt"
              echo "${sv_PayloadFileName}" >> "${GLB_sv_ThisScriptTempDirPath}/Policies-install.txt"
              
            fi
          done


          # Update list of policies to uninstall (they still need to be actually uninstalled)
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-uninstall.txt" | while read sv_PayloadFileName
          do
#            ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/UnInstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
#            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
#            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/UnInstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
            mv -f "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/UnInstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
          done

          # Update list of policies to verify as still active
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt" | while read sv_PayloadFileName
          do
#            ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
#            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
#            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
            mv -f "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
          done
    
          # Update list of policies to install
          cat "${GLB_sv_ThisScriptTempDirPath}/Policies-install.txt" | while read sv_PayloadFileName
          do
#            ln -fh "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
#            rm -f "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadFileName}"
#            rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
            mv -f "${sv_UpdatedPayloadContentDirPath}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
          done
    
#            GLB_nf_SetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":LabWarden:LocalPrefs:Version" "${GLB_sv_ProjectVersion}"
#            GLB_nf_SetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":LabWarden:LocalPrefs:LastUpdateEpoch" "${GLB_iv_ThisScriptStartEpoch}"


          # Remove temp files
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-install.txt"
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-verify.txt"
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-uninstall.txt"

          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-check.txt"

          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-src.txt"
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-dst.txt"
          rm -f "${GLB_sv_ThisScriptTempDirPath}/Policies-uniq.txt"

        fi      
      
      fi
    
    fi
  
  fi
  
fi

# This bit can be run as root or user

# Set the CWD to somewhere anyone can access
cd /tmp

# --- install, uninstall or verify the downloaded or existing AD payloads (which are usually mobileconfig files)

if test -e "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/${sv_ObjectContext}/${sv_ObjectName}"
then
  # uninstall payloads
  ls -1 "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/${sv_ObjectContext}/${sv_ObjectName}" | while read sv_PayloadFileName
  do
    if [ "$(echo ${sv_PayloadFileName} | tr "[A-Z]" "[a-z]")" = "policybanner.rtf" ]
    then
      sv_PayloadFileExt="PolicyBanner-rtf"
    
    else
      sv_PayloadFileExt=$(echo "${sv_PayloadFileName}" | sed 's|^[^\.]*\.||;s|\.|-|' | tr [A-Z] [a-z])
      
    fi
    
    sv_HandlerFilePath="/usr/local/LabWarden/Custom-PayloadHandlers/${sv_PayloadFileExt}-uninstall"
    if ! test -e "${sv_HandlerFilePath}"
    then
      sv_HandlerFilePath="/usr/local/LabWarden/PayloadHandlers/${sv_PayloadFileExt}-uninstall"
      if ! test -e "${sv_HandlerFilePath}"
      then
        sv_HandlerFilePath=""
      fi
    fi

    if test -z "${sv_HandlerFilePath}"
    then
      GLB_nf_logmessage ${GLB_iv_MsgLevelWarn} "There's no handler to uninstall ${sv_PayloadFileName}"
      rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
    else
      GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Uninstalling ${sv_PayloadFileName}"
      "${sv_HandlerFilePath}" "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${sv_GPOuser}"
      sv_Error=$?
      if [ ${sv_Error} -eq 0 ]
      then
        rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Uninstall/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        
      else
        GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Failed to uninstall ${sv_PayloadFileName} (${sv_Error})"
        
      fi
    fi
  done
fi

if test -e "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}"
then
  # Verify payloads
  ls -1 "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}" | while read sv_PayloadFileName
  do
    if [ "$(echo ${sv_PayloadFileName} | tr "[A-Z]" "[a-z]")" = "policybanner.rtf" ]
    then
      sv_PayloadFileExt="PolicyBanner-rtf"
    
    else
      sv_PayloadFileExt=$(echo "${sv_PayloadFileName}" | sed 's|^[^\.]*\.||;s|\.|-|' | tr [A-Z] [a-z])
      
    fi
    
    sv_HandlerFilePath="/usr/local/LabWarden/Custom-PayloadHandlers/${sv_PayloadFileExt}-verify"
    if ! test -e "${sv_HandlerFilePath}"
    then
      sv_HandlerFilePath="/usr/local/LabWarden/PayloadHandlers/${sv_PayloadFileExt}-verify"
      if ! test -e "${sv_HandlerFilePath}"
      then
        sv_HandlerFilePath=""
      fi
    fi

    if test -z "${sv_HandlerFilePath}"
    then
      GLB_nf_logmessage ${GLB_iv_MsgLevelWarn} "There's no handler to verify ${sv_PayloadFileName}"
      rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
    else
      GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Verifying ${sv_PayloadFileName}"
      "${sv_HandlerFilePath}" "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${sv_GPOuser}"
      if [ $? -eq 0 ]
      then
        # No errors when verifying - flag it as active
        ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        touch -t $(date -r ${GLB_iv_ThisScriptStartEpoch} "+%Y%m%d%H%M.%S") "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}"

      else
        # Errors when verifying - we should install
        ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Verify/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"

      fi
    fi
  done
fi

if test -e "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}"
then
  # Install payloads
  ls -1 "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}" | while read sv_PayloadFileName
  do
    if [ "$(echo ${sv_PayloadFileName} | tr "[A-Z]" "[a-z]")" = "policybanner.rtf" ]
    then
      sv_PayloadFileExt="PolicyBanner-rtf"
    
    else
      sv_PayloadFileExt=$(echo "${sv_PayloadFileName}" | sed 's|^[^\.]*\.||;s|\.|-|' | tr [A-Z] [a-z])
      
    fi
    
    sv_HandlerFilePath="/usr/local/LabWarden/Custom-PayloadHandlers/${sv_PayloadFileExt}-install"
    if ! test -e "${sv_HandlerFilePath}"
    then
      sv_HandlerFilePath="/usr/local/LabWarden/PayloadHandlers/${sv_PayloadFileExt}-install"
      if ! test -e "${sv_HandlerFilePath}"
      then
        sv_HandlerFilePath=""
      fi
    fi

    if test -z "${sv_HandlerFilePath}"
    then
      GLB_nf_logmessage ${GLB_iv_MsgLevelWarn} "There's no handler to install ${sv_PayloadFileName}"
      rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
    else
      GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Installing ${sv_PayloadFileName}"
      "${sv_HandlerFilePath}" "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${sv_GPOuser}"
      sv_Error=$?
      if [ ${sv_Error} -eq 0 ]
      then
        ln -fh "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}" "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        rm -f "${GLB_sv_ProjectConfigDirPath}/Policies/Install/${sv_ObjectContext}/${sv_ObjectName}/${sv_PayloadFileName}"
        touch -t $(date -r ${GLB_iv_ThisScriptStartEpoch} "+%Y%m%d%H%M.%S") "${GLB_sv_ProjectConfigDirPath}/Policies/Active/${sv_ObjectContext}/${sv_ObjectName}"

      else
        GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Failed to install ${sv_PayloadFileName} (${sv_Error})"
        
      fi
    fi
  done
fi

# --- now strip the configs from the installed mobileconfigs
# (code moved to configupdate which is launched via a watchpath LaunchDaemon)

# ---

# Remove temporary files
rm -fPR "${GLB_sv_ThisScriptTempDirPath}"

exit 0
