#!/bin/bash
#
# Short:    Perform a manual update
# Author:   Mark J Swift
# Version:  2.0.6
# Modified: 27-May-2017
#
# Call from a shell as follows:    
#   /usr/local/LabWarden/util/Update

# ---

# -- Trigger the Sys-ManualUpdate event --

/usr/local/LabWarden/lib/Trigger "Sys-ManualUpdate" "$(whoami)"
