#!/bin/bash
#
# Short:    Perform a manual update
# Author:   Mark J Swift
# Version:  1.0.101
# Modified: 09-Dec-2016
#
# Call from a shell as follows:    
#   /usr/local/LabWarden/util/Update

# ---

# -- Trigger the ManualUpdate event --

/usr/local/LabWarden/lib/Trigger "ManualUpdate" "$(whoami)"
