#!/bin/bash
#
# Short:    Constants
# Author:   Mark J Swift
# Version:  1.0.100
# Modified: 27-Oct-2016
#
# 'Constants' should be included into scripts as follows:
#   . /usr/local/LabWarden/lib/Constants
#

# Only run the code if it hasn't already been run
if test -z "${LW_sv_LabWardenSignature}"
then

# 'Constants' sets the following LabWarden globals:
#
#  LW_sv_LabWardenVersion                - Main code version
#  LW_sv_LabWardenSignature              - LabWarden signature (com.github.execriez.LabWarden)
#
#  LW_iv_LogMaxLength                    - Maximum length of LabWarden log(s)
#  LW_bv_LogIsActiveDefault              - Whether we should log by default (true/false)
#
#  LW_sv_BinDirPath                      - Path to binaries such as rsync or CocoaDialog
#  LW_sv_SettingsDirPath                 - Path to main LabWarden settings files
#
# 
#  LW_iv_UserPollTriggerSecs             - The point at which we trigger a UserPoll event
#  LW_iv_SystemPollTriggerSecs           - The point at which we trigger a SystemPoll event
#  LW_iv_LoginWindowPollTriggerSecs      - The point at which we trigger a LoginWindowPoll event
#  LW_iv_IdleTriggerSecs                 - The point at which we trigger a UserIdle, SystemIdle and LoginWindowIdle event
#
#  LW_iv_GPforceAgeMinutes               - How old the policies need to be for gpupdate -force to do updates
#  LW_iv_GPquickAgeMinutes               - How old the policies need to be for gpupdate -quick to do updates
#  LW_iv_GPdefaultAgeMinutes             - How old the policies need to be for gpupdate to do updates

#  Key:
#    LW_ - LabWarden global variable
#
#    bv_ - string variable with the values "true" or "false"
#    iv_ - integer variable
#    sv_ - string variable
#
#    nf_ - null function    (doesn't return a value)
#    bf_ - boolean function (returns string values "true" or "false"
#    if_ - integer function (returns an integer value)
#    sf_ - string function  (returns a string value)

# ---

LW_sv_LabWardenSignature="com.github.execriez.LabWarden"
LW_sv_LabWardenVersion="1.0.100"

# ---

LW_iv_LogMaxLength=250000
LW_bv_LogIsActiveDefault="true"

# ---

# Path to useful binaries
LW_sv_BinDirPath=/usr/local/LabWarden/bin

# Decide where the config/pref files go
LW_sv_SettingsDirPath="/Library/Preferences/SystemConfiguration/${LW_sv_LabWardenSignature}"

# ---

# The point at which we trigger a UserPoll event (3 minutes)
LW_iv_UserPollTriggerSecs=181

# The point at which we trigger a SystemPoll event (4 minutes)
LW_iv_SystemPollTriggerSecs=241

# The point at which we trigger a LoginWindowPoll event (5 minutes)
LW_iv_LoginWindowPollTriggerSecs=307

# The point at which we trigger a UserIdle, SystemIdle and LoginWindowIdle event (7 minutes)
LW_iv_IdleTriggerSecs=421

# ---

# gpupdate -force updates when policies are older than 1 minute
LW_iv_GPforceAgeMinutes=1

# gpupdate -quick updates when policies are older than 180 days
LW_iv_GPquickAgeMinutes=259200

# gpupdate defaults to update policies when they are older than 1 day old
LW_iv_GPdefaultAgeMinutes=1440

fi