#!/bin/bash
#
# Short:    Trigger an escalated event (initiated by a normal user) 
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Called as root when a user modifies the watch folder contents:    

# ---

sv_WatchDirPath="/usr/local/LabWarden/Escalated"

while read sv_FileName
do
  sv_UserName="$(stat -f "%Su" "${sv_WatchDirPath}/${sv_FileName}")"
  sv_EventName="$(echo "${sv_FileName}" | tr -dc [:alpha:])"
  rm -f "${sv_WatchDirPath}/${sv_FileName}"
done < <(ls -1 "${sv_WatchDirPath}")

if test -n "${sv_UserName}"
then
  /usr/local/LabWarden/lib/Trigger "${sv_EventName}Escalated" "${sv_UserName}"
fi
