#!/bin/bash
#
# Short:    When a user logs in - call the LOGIN trigger(s)
# Author:   Mark J Swift
# Version:  2.0.6
# Modified: 27-May-2017
#
# Called as root at user login as follows:    
#   LoginHook username
#
# Executes the following Triggers
#   Sys-Login <user> (as root)
#   Usr-Login <user>  (as user)

# ---

# Check we have the correct number of parameters
if [ $# -lt 1 ]
then
  exit 0
fi

# -- Login/Logout hooks run as root and pass the user as first parameter --

# Get user name
GLB_sv_ThisUserName="${1}"

# We are assuming that we never log in as root.
if [ "${GLB_sv_ThisUserName}" = "root" ]
then
  exit 0
fi
  
# If necessary, create the local user folder
if ! test -e "/Users/${GLB_sv_ThisUserName}"
then
  /bin/mkdir -p "/Users/${GLB_sv_ThisUserName}"
  /bin/chmod 750 "/Users/${GLB_sv_ThisUserName}"
  /usr/sbin/chown ${GLB_sv_ThisUserName}:wheel "/Users/${GLB_sv_ThisUserName}"
fi

# -- The following is executed as root --

/usr/local/LabWarden/lib/Trigger "Sys-Login" "$(whoami)" "${GLB_sv_ThisUserName}"

# -- The following is executed as the user who is logging in --

# 'HEREDOC' is quoted to prevent variable expansion.
# This means that variables outside are not available.
 
/usr/bin/su ${GLB_sv_ThisUserName} <<'HEREDOC'

/usr/local/LabWarden/lib/Trigger "Usr-Login"

HEREDOC

# -- We are back as the root user.
