#!/bin/bash
#
# Short:    When a user logs in - call the LOGIN trigger(s)
# Author:   Mark J Swift
# Version:  1.0.82
# Modified: 27-May-2016
#
# Called as root at user login as follows:    
#   LoginHook username
#
# Executes the following Triggers
#   LoginBegin <user> (as root)
#   UserLogin <user>  (as user)

# ---

# Check we have the correct number of parameters
if [ $# -lt 1 ]
then
  exit 0
fi

# -- Login/Logout hooks run as root and pass the user as first parameter --

# Get user name
GLB_ThisUserName="${1}"

# We are assuming that we never log in as root.
if [ "${GLB_ThisUserName}" = "root" ]
then
  exit 0
fi
  
# If necessary, create the local user folder
if ! test -e "/Users/${GLB_ThisUserName}"
then
  /bin/mkdir -p "/Users/${GLB_ThisUserName}"
  /bin/chmod 750 "/Users/${GLB_ThisUserName}"
  /usr/sbin/chown ${LCL_UserName}:wheel "/Users/${GLB_ThisUserName}"
fi

# -- The following is executed as root --

/usr/local/LabWarden/lib/Trigger "LoginBegin" "${GLB_ThisUserName}"

# -- The following is executed as the user who is logging in --

# 'HEREDOC' is quoted to prevent variable expansion.
# This means that variables outside are not available.
 
/usr/bin/su ${GLB_ThisUserName} <<'HEREDOC'

/usr/local/LabWarden/lib/Trigger "UserLogin" "$(whoami)"

HEREDOC

# -- We are back as the root user.
