#!/bin/bash
#
# Short:    Perform managed prefs checks
# Author:   Mark J Swift
# Version:  2.0.13
# Modified: 28-Jul-2017
#
#
# Called as follows (by watchpath as root):    
#   ManagedPrefs

# ---

if [ "$(whoami)" = "root" ]
then
  # Update workstation configs
  /usr/local/LabWarden/util/configupdate
  
  # Update user configs for all users who are logged in
  who -q | grep -Ev "^#" | tr " " "\n" | sort -u | grep -Ev "^$" | grep -Ev "^root$" | while read sv_UserName
  do
    /usr/local/LabWarden/util/configupdate "${sv_UserName}"
  done
fi

# Debug
#say "Managed Prefs "$(whoami)

exit 0

