#!/bin/bash
#
# Short:    Handle a Poll Trigger
# Author:   Mark J Swift
# Version:  1.0.96
# Modified: 05-Sep-2016
#
# Called as follows:    
#   Poll "System|LoginWindow|User"
#

# ---

# Get poll
sv_PollName="${1}"

if test -z "${sv_PollName}"
then
  # We need something to work with
  exit 0
fi

# ---

# Trigger the Poll event
/usr/local/LabWarden/lib/Trigger "${sv_PollName}Poll" &

# ---

# Load the contants, only if they are not already loaded
if test -z "${LW_sv_LabWardenSignature}"
then
  . /usr/local/LabWarden/lib/Constants
fi

# ---

# Get seconds that mac mouse/keyboard is idle - thanks to https://github.com/CLCMacTeam/IdleLogout
LW_if_UserInteractionIdleSecs()
{
  echo $(($(ioreg -c IOHIDSystem | sed -e '/HIDIdleTime/ !{ d' -e 't' -e '}' -e 's/.* = //g' -e 'q') / 1000000000))
}

# If there has been no recent input, trigger an idle event 
# If there continues to be no input, the idle event will continue to be triggered with every subsequent poll event
iv_IdleSecs=$(LW_if_UserInteractionIdleSecs)
if [ ${iv_IdleSecs} -gt ${LW_iv_IdleTriggerSecs} ]
then
  # Trigger an Idle event
  /usr/local/LabWarden/lib/Trigger "${sv_PollName}Idle" &
fi

# ---

# We dont want to quit until the background scripts are finished or they might terminate early
while [ -n "$(jobs -r)" ]
do
  # we don't want to hog the CPU - so lets sleep a while
  sleep 1
done
