#!/bin/bash
#
# Short:    Simple Radmind update script
# Author:   Mark J Swift
# Version:  2.0.20
# Modified: 29-Oct-2017
#
# Called as follows:    
#   RadmindUpdate "radmindserver,Cksum,AuthLevel,CaseSwitch,MaxDeletes" [<NotifyURI>]
# eg: RadmindUpdate "172.18.1.24,sha1,0,-I,15000"
#
# The optional NotifyURI is a server web URI that notifies the deployment server that an update is
# about to happen. The server should do what it needs to in order to prep the future update.
#
# During a notification, NotifyURI is passed the following info: 'os', 'loglevelstr', 'logtextstr'.

# ---

sv_CodeVersion="2.0.20"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get filename of this script
sv_ThisScriptFileName="$(basename "${0}")"

# Get dir of this script
sv_ThisScriptDirPath="$(dirname "${0}")"

# Get Process ID of this script
iv_ThisScriptPID=$$

# ---

# Get user name
sv_ThisUserName="$(whoami)"

if [ "${sv_ThisUserName}" != "root" ]
then
  # we only like root
  exit 0
fi

# ---

# Load the contants, only if they are not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Constants.sh
fi

# ---

# If no-one is logged in (even remotely), and iHook is available - then use it
if test -z "$(who -q | grep '# users = 0')"
then
  if test -e "/usr/local/${GLB_sv_ProjectName}/bin/iHook.app/Contents/MacOS/iHook"
  then
    iv_MyParentProcess="$(ps -o comm= $PPID | tr "/" "\n" | tail -n1)"
    if [ "${iv_MyParentProcess}" != "iHook" ]
    then
      /usr/local/${GLB_sv_ProjectName}/bin/iHook.app/Contents/MacOS/iHook --no-titlebar --script="${0}" "${1}" "${2}" "${3}" "${4}"
      exit 0
    else
      echo "%WINDOWSIZE 640 456"
      echo "%TEXTCOLOR BLACK"
      if test -f "/usr/local/${GLB_sv_ProjectName}/images/${sv_ThisScriptFileName}.jpg"
      then
        echo "%BACKGROUND /usr/local/${GLB_sv_ProjectName}/images/${sv_ThisScriptFileName}.jpg"
      else
        if test -f "/usr/local/${GLB_sv_ProjectName}/images/SplashScreenLight.jpg"
        then
          echo "%BACKGROUND /usr/local/${GLB_sv_ProjectName}/images/SplashScreenLight.jpg"
        fi
      fi
      echo "%UIMODE AUTOCRATIC"
      echo "%WINDOWZOOM DISABLE"
      echo "%SHOWTIMER"
      echo "%TITLE ${sv_ThisScriptFileName}"
      echo "%LOG APPEND /Library/Logs/${GLB_sv_ProjectSignature}.log"
    fi
  fi
fi

# ---

# Get parameter(s)
sv_Param="${1}"
if test -z "${sv_Param}"
then
  # We need something to work with
  exit 0
fi

sv_NotifyURI="${2}"

# ---

# Parse the 1st parameter

# Get Radmind server address
sv_RadServer=$(echo "${sv_Param}" | cut -d"," -f1)

# Checksum eg sha1
sv_RadCksum=$(echo "${sv_Param}" | cut -d"," -f2)

# TLS auth level. 0: None; 1: Verify Server; 2: Verify Server & Client
iv_RadAuthLevel=$(echo "${sv_Param}" | cut -d"," -f3)

# Get transcript case. -I means ignore case in filenames
sv_CaseSwitch=$(echo "${sv_Param}" | cut -d"," -f4)

# Get Maximum negative changes
iv_MaxDeletes=$(echo "${sv_Param}" | cut -d"," -f5)

# ---

# urlencode/urldecode functions - thanks to https://gist.github.com/cdown/1163649
sf_urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}

# Convert log level integer into log level text
sf_LogLevel()   # loglevel
{  
  local iv_LogLevel
  local sv_LogLevel

  iv_LogLevel=${1}

  case ${iv_LogLevel} in
  ${GLB_iv_MsgLevelEmerg})
    sv_LogLevel="Emergency"
    ;;

  ${GLB_iv_MsgLevelAlert})
    sv_LogLevel="Alert"
    ;;

  ${GLB_iv_MsgLevelCrit})
    sv_LogLevel="Critical"
    ;;

  ${GLB_iv_MsgLevelErr})
    sv_LogLevel="Error"
    ;;
  
  ${GLB_iv_MsgLevelWarn})
    sv_LogLevel="Warning"
    ;;

  ${GLB_iv_MsgLevelNotice})
    sv_LogLevel="Notice"
    ;;

  ${GLB_iv_MsgLevelInfo})
    sv_LogLevel="Information"
    ;;

  ${GLB_iv_MsgLevelDebug})
    sv_LogLevel="Debug"
    ;;

  *)
    sv_LogLevel="Unknown"
    ;;

  esac
  
  echo ${sv_LogLevel}
}
  
# Save a message to the log file
nf_showmessage()   # intloglevel strmessage 
{
  local iv_LogLevel
  local sv_Message
  local sv_LogLevel
  
  iv_LogLevel=${1}
  sv_LogText="${2}"
  
  if [ -n "${sv_LogText}" ]
  then
    sv_LogLevel="$(sf_LogLevel ${iv_LogLevel})"

    echo "$(date '+%d %b %Y %H:%M:%S %Z') ${sv_ThisScriptFileName}[${iv_ThisScriptPID}]${sv_CodeVersion}: ${sv_LogLevel}: ${sv_LogText}"
    sleep 2
  fi
}

nf_notifyserver()   # intloglevel strmessage
{
  local iv_LogLevel
  local sv_Message
  local sv_LogLevel
  
  iv_LogLevel=${1}
  sv_LogText="${2}"

  nf_showmessage "${iv_LogLevel}" "${sv_LogText}"

  if test -n "${sv_NotifyURI}"
  then
    sv_LogLevel="$(sf_LogLevel ${iv_LogLevel})"
    
    CURL --max-time 120 --connect-timeout 10 -s -S -d os=$(sf_urlencode "${sv_SystemVersionStampAsString}") -d loglevelstr=$(sf_urlencode "${sv_LogLevel}") -d logtextstr=$(sf_urlencode "${sv_LogText}") "${sv_NotifyURI}"
    if [ $? != "0" ]
    then
      # Some kind of error occurred
      nf_showmessage ${GLB_iv_MsgLevelErr} "Cannot connect to '${sv_NotifyURI}'"
    fi
  fi
}

# ---

sv_SystemVersionStampAsString="$(sw_vers -productVersion)"

# ---

# RADMIND UPDATE HERE - ktcheck/fsdiff/lapply

sv_fsdiffCompareSysPath="/"
sv_fsdiffOutputFilePath="/tmp/diff.T.$$"

nf_notifyserver ${GLB_iv_MsgLevelInfo} "Checking server ${sv_RadServer} for transcript changes"

/usr/local/bin/ktcheck 2>&1 -i -c${sv_RadCksum} -w${iv_RadAuthLevel} -h${sv_RadServer}
iv_ErrCode="$?"

# Check exit status of ktcheck. If > 1, an error occurred.
case "${iv_ErrCode}" in
0)
  nf_showmessage ${GLB_iv_MsgLevelInfo} "No transcript changes found - no need to update"
  exit 0
  ;;
1)
  nf_showmessage ${GLB_iv_MsgLevelNotice} "Transcript changes found"
  ;;
*)
  nf_notifyserver ${GLB_iv_MsgLevelErr} "Update aborted - ktcheck failed (${iv_ErrCode})"
  exit 0
  ;;
esac

nf_showmessage ${GLB_iv_MsgLevelInfo} "Examining the filesystem for differences..."

# run fsdiff, redirecting output to a file.
rm -f ${sv_fsdiffOutputFilePath}
/usr/local/bin/fsdiff ${sv_CaseSwitch} -A -o${sv_fsdiffOutputFilePath} -% ${sv_fsdiffCompareSysPath}
iv_ErrCode="$?"

case "${iv_ErrCode}" in
0)
  ;;
*)
  # try opposite case
  if test -z "${sv_CaseSwitch}"
  then
    sv_CaseSwitch="-I"
  else
    sv_CaseSwitch=""
  fi
        
  # run fsdiff, redirecting output to a file.
  rm -f ${sv_fsdiffOutputFilePath}
  /usr/local/bin/fsdiff ${sv_CaseSwitch} -A -o${sv_fsdiffOutputFilePath} -% ${sv_fsdiffCompareSysPath}
  iv_ErrCode="$?"

  case "$iv_ErrCode" in
  0)
    ;;
  *)
    rm -f ${sv_fsdiffOutputFilePath}
    nf_notifyserver ${GLB_iv_MsgLevelErr} "Update aborted - fsdiff failed (${iv_ErrCode})"
    exit 0
    ;;
  esac
  ;;
esac

# Fix for SIP on 10.11
nf_showmessage ${GLB_iv_MsgLevelNotice} "Removing SIP protected entries from transcript"
/usr/local/${GLB_sv_ProjectName}/bin/RadmindTfix4SIP ${sv_fsdiffOutputFilePath}

# Check we aren't deleting more than we would reasonably expect to (optional simple safeguard)
if test -n "${iv_MaxDeletes}"
then
  iv_Additions=$(cat ${sv_fsdiffOutputFilePath} | grep "^+" | wc | tr -s " " | cut -d" " -f2)
  iv_Removals=$(cat ${sv_fsdiffOutputFilePath} | grep "^-" | wc | tr -s " " | cut -d" " -f2)
  iv_NegChanges=$((${iv_Removals} - ${iv_Additions}))
  if [ ${iv_NegChanges} -gt 0 ]
  then
    if [ ${iv_NegChanges} -gt ${iv_MaxDeletes} ]
    then
      rm -f ${sv_fsdiffOutputFilePath}
      nf_notifyserver ${GLB_iv_MsgLevelErr} "Update aborted - too many deletes (${iv_NegChanges} -gt ${iv_MaxDeletes})"
      exit 0
    fi
  fi
fi

# Apply the changes
launchctl stop org.cups.cupsd

nf_showmessage ${GLB_iv_MsgLevelNotice} "Applying $((${iv_Additions} - ${iv_Removals})) changes…(+$iv_Additions -$iv_Removals)"
/usr/local/bin/lapply 2>&1 ${sv_CaseSwitch} -i -F -% -c${sv_RadCksum} -w${iv_RadAuthLevel} -h${sv_RadServer} ${sv_fsdiffOutputFilePath}
iv_ErrCode="$?"

launchctl stop org.cups.cupsd

launchctl start org.cups.cupsd

case "${iv_ErrCode}" in
0)
  # Restart after a successful update
  nf_notifyserver ${GLB_iv_MsgLevelNotice} "Apply successful - we should restart."
  exit 0
  ;;
1)
  nf_notifyserver ${GLB_iv_MsgLevelErr} "Apply failed - no changes made"
  rm -f /private/var/radmind/client/error.T
  mv "${sv_fsdiffOutputFilePath}" /private/var/radmind/client/error.T
  exit 0
  ;;
2)
  nf_notifyserver ${GLB_iv_MsgLevelErr} "Apply failed - changes made"
  rm -f /private/var/radmind/client/error.T
  mv "${sv_fsdiffOutputFilePath}" /private/var/radmind/client/error.T
  exit 0
  ;;
esac
