#!/bin/bash
#
# Short:    Simple Radmind update script
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Called as follows:    
#   RadmindUpdate "radmindserver,Cksum,AuthLevel,CaseSwitch,MaxDeletes" [<NotifyURI>] [<SuccessURI>] [<FailURI>]
# eg: Radmind "172.18.1.24,sha1,0,-I,15000"
#
# The optional NotifyURI is a server web URI that notifies the deployment server that an update is
# about to happen. The server should do what it needs to in order to process the future update.
# Ideally, the server should query AD and build a new set of manifests and catalogues based on 
# workstation AD group memberships and the OS version (which is passed to the URI).
#
# The optional SuccessURI is a server web URI that notifies the server that the update was a success.
#
# The optional FailURI is a server web URI that notifies the server that the update failed.

# ---

# Get filename of this script
sv_ThisScriptFileName="$(basename "${0}")"

# Get dir of this script
sv_ThisScriptDirPath="$(dirname "${0}")"

# Get Process ID of this script
iv_ThisScriptPID=$$

# ---

# Get user name
sv_ThisUserName="$(whoami)"

if [ "${sv_ThisUserName}" != "root" ]
then
  # we only like root
  exit 0
fi

# ---

# Get parameter(s)
sv_Param="${1}"
if test -z "${sv_Param}"
then
  # We need something to work with
  exit 0
fi

sv_NotifyURI="${2}"
sv_SuccessURI="${3}"
sv_FailURI="${4}"

# ---

# Parse the 1st parameter

# Get Radmind server address
sv_RadServer=$(echo "${sv_Param}" | cut -d"," -f1)

# Checksum eg sha1
sv_RadCksum=$(echo "${sv_Param}" | cut -d"," -f2)

# TLS auth level. 0: None; 1: Verify Server; 2: Verify Server & Client
iv_RadAuthLevel=$(echo "${sv_Param}" | cut -d"," -f3)

# Get transcript case. -I means ignore case in filenames
sv_CaseSwitch=$(echo "${sv_Param}" | cut -d"," -f4)

# Get Maximum negative changes
iv_MaxDeletes=$(echo "${sv_Param}" | cut -d"," -f5)

# ---

# urlencode/urldecode functions - thanks to https://gist.github.com/cdown/1163649
Sf_urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}

# Save a message to the log file
Nf_showmessage()   # messagetxt
{
  echo "$(date '+%d %b %Y %H:%M:%S') ${sv_ThisScriptFileName}[${iv_ThisScriptPID}]: ${1}"
}

Nf_showerror()   # messagetxt
{
  Nf_showmessage "${1}"

  # Update the RemoteDesktop Computer Info Fields #4
  /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -computerinfo -set4 -4 "${1}"

  if test -n "${sv_FailURI}"
  then
    CURL --max-time 120 --connect-timeout 10 -s -S -d msg=$(Sf_urlencode "${1}") "${sv_FailURI}"
    if [ $? != "0" ]
    then
      # Some kind of error occurred
      Nf_showmessage "NOTE, cannot connect to ${sv_FailURI}"
    fi
  fi
}

Nf_showsuccess()   # messagetxt
{
  Nf_showmessage "${1}"

  # Update the RemoteDesktop Computer Info Fields #4
  /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -computerinfo -set4 -4 ""

  if test -n "${sv_SuccessURI}"
  then
    CURL --max-time 120 --connect-timeout 10 -s -S -d msg=$(Sf_urlencode "") "${sv_SuccessURI}"
    if [ $? != "0" ]
    then
      # Some kind of error occurred
      Nf_showmessage "NOTE, cannot connect to ${sv_SuccessURI}"
    fi
  fi
}

# ---

sv_SystemVersionStampAsString="$(sw_vers -productVersion)"

# ---

if test -n "${sv_NotifyURI}"
then
  CURL --max-time 120 --connect-timeout 10 -s -S -d os=$(Sf_urlencode "${sv_SystemVersionStampAsString}") "${sv_NotifyURI}"
  if [ $? != "0" ]
  then
    # Some kind of error occurred
    Nf_showerror "ERROR, cannot connect to ${sv_NotifyURI}"
    exit 0
  fi
fi

# ---

# RADMIND UPDATE HERE - ktcheck/fsdiff/lapply

sv_fsdiffCompareSysPath="/"
sv_fsdiffOutputFilePath="/tmp/diff.T.$$"

Nf_showmessage "NOTE, checking server $sv_RadServer for transcript changes"

/usr/local/bin/ktcheck 2>&1 -i -c${sv_RadCksum} -w${iv_RadAuthLevel} -h${sv_RadServer}
iv_ErrCode="$?"

# Check exit status of ktcheck. If > 1, an error occurred.
case "${iv_ErrCode}" in
0)
  Nf_showmessage "NOTE, no transcript changes found - no need to update"
  exit 0
  ;;
1)
  Nf_showmessage "NOTE, Transcript changes found"
  ;;
*)
  Nf_showerror "ERROR, update aborted - ktcheck failed (${iv_ErrCode})"
  exit 0
  ;;
esac

Nf_showmessage "NOTE, Examining the filesystem for differences..."

# run fsdiff, redirecting output to a file.
rm -f ${sv_fsdiffOutputFilePath}
/usr/local/bin/fsdiff ${sv_CaseSwitch} -A -o${sv_fsdiffOutputFilePath} -% ${sv_fsdiffCompareSysPath}
iv_ErrCode="$?"

case "${iv_ErrCode}" in
0)
  ;;
*)
  # try opposite case
  if test -z "${sv_CaseSwitch}"
  then
    sv_CaseSwitch="-I"
  else
    sv_CaseSwitch=""
  fi
        
  # run fsdiff, redirecting output to a file.
  rm -f ${sv_fsdiffOutputFilePath}
  /usr/local/bin/fsdiff ${sv_CaseSwitch} -A -o${sv_fsdiffOutputFilePath} -% ${sv_fsdiffCompareSysPath}
  iv_ErrCode="$?"

  case "$iv_ErrCode" in
  0)
    ;;
  *)
    rm -f ${sv_fsdiffOutputFilePath}
    Nf_showerror "ERROR, update aborted - fsdiff failed (${iv_ErrCode})"
    exit 0
    ;;
  esac
  ;;
esac

# Fix for SIP on 10.11
Nf_showmessage "NOTE, Removing SIP protected entries from transcript"
/usr/local/LabWarden/bin/RadmindTfix4SIP ${sv_fsdiffOutputFilePath}

# Check we aren't deleting more than we would reasonably expect to (optional simple safeguard)
if test -n "${iv_MaxDeletes}"
then
  iv_Additions=$(cat ${sv_fsdiffOutputFilePath} | grep "^+" | wc | tr -s " " | cut -d" " -f2)
  iv_Removals=$(cat ${sv_fsdiffOutputFilePath} | grep "^-" | wc | tr -s " " | cut -d" " -f2)
  iv_NegChanges=$((${iv_Removals} - ${iv_Additions}))
  if [ ${iv_NegChanges} -gt 0 ]
  then
    if [ ${iv_NegChanges} -gt ${iv_MaxDeletes} ]
    then
      rm -f ${sv_fsdiffOutputFilePath}
      Nf_showerror "ERROR, update aborted - too many deletes (${iv_NegChanges} -gt ${iv_MaxDeletes})"
      exit 0
    fi
  fi
fi

# Apply the changes
launchctl stop org.cups.cupsd

Nf_showmessage "NOTE, Applying $((${iv_Additions} - ${iv_Removals})) changes…(+$iv_Additions -$iv_Removals)"
/usr/local/bin/lapply 2>&1 ${sv_CaseSwitch} -i -F -% -c${sv_RadCksum} -w${iv_RadAuthLevel} -h${sv_RadServer} ${sv_fsdiffOutputFilePath}
iv_ErrCode="$?"

launchctl start org.cups.cupsd

case "${iv_ErrCode}" in
0)
  # Restart after a successful update
  Nf_showsuccess "ATTENTION, apply successful - we should reboot."
  exit 0
  ;;
1)
  Nf_showerror "ERROR, apply failed - no changes made"
  #cat "${sv_fsdiffOutputFilePath}"
  rm -f $sv_fsdiffOutputFilePath
  exit 0
  ;;
2)
  Nf_showerror "ERROR, apply failed - changes made"
  #cat "${sv_fsdiffOutputFilePath}"
  rm -f $sv_fsdiffOutputFilePath
  exit 0
  ;;
esac
