#!/bin/bash
#
# Short:    Do something when the Active Directory connects or disconnects
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Called by LaunchDaemon as follows:    
#   ADWarden
#

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# ---

# Get user name
GLB_SV_RUNUSERNAME="$(whoami)"

if [ "${GLB_SV_RUNUSERNAME}" != "root" ]
then
  exit 0
fi

# ---

sv_TempDir="/tmp/root"

if ! test -d "${sv_TempDir}"
then
  mkdir -p "${sv_TempDir}"
  chown root:admin "${sv_TempDir}"
  chmod 770 "${sv_TempDir}"
fi

if test -f "${sv_TempDir}/Sys-ActiveDirectoryUp"
then
  bv_LastActiveDirectoryUp="true"

else
  bv_LastActiveDirectoryUp="false"

fi

dscl 2>&1 localhost -read /Search/Computers/$(hostname -s)$ name
if [ $? -ne 0 ]
then
  if [ "${bv_LastActiveDirectoryUp}" = "true" ]
  then
    rm -f "${sv_TempDir}/Sys-ActiveDirectoryUp"
    sv_event="Sys-ActiveDirectoryDown"
  fi

else
  if [ "${bv_LastActiveDirectoryUp}" = "false" ]
  then
    touch "${sv_TempDir}/Sys-ActiveDirectoryUp"
    sv_event="Sys-ActiveDirectoryUp"
  fi

fi

if test -n "${sv_event}"
then
  "${GLB_SV_PROJECTDIRPATH}"/bin/Trigger "${sv_event}"
fi
