#!/bin/bash
#
# Short:    Do something when a volume is mounted
# Author:   Mark J Swift
# Version:  3.3.0
# Modified: 22-May-2022
#
# Called by MountWarden as user like this:
#   MountWarden-DidUnmount "DidUnmount:Epoch:VolumePath"
# i.e.
#   MountWarden-DidUnmount "DidUnmount:1538163950:/Volumes/MYFATDISK"

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# ---

# Get user name
GLB_SV_RUNUSERNAME="$(whoami)"

if [ "${GLB_SV_RUNUSERNAME}" != "root" ]
then
  exit 0
fi

# ---

# Check we have the correct number of parameters
if [ $# -lt 1 ]
then
  exit 0
fi

# -- Trigger the VolDidUnmount policy (and pass it the volume path) --

# Get user name
GLB_SV_RUNUSERNAME="$(whoami)"

# Get volume path
GLB_SV_MOUNTEDVOLUMEDIRPATH="$(echo ${1} | cut -d":" -f3)"

"${GLB_SV_PROJECTDIRPATH}"/bin/Trigger "Sys-VolDidUnmount" "${GLB_SV_MOUNTEDVOLUMEDIRPATH}" &

# Call Usr-VolDidUnmount for all users who are logged in
who -q | grep -Ev "^#" | tr " " "\n" | sort -u | grep -Ev "^$" | grep -Ev "^root$" | while read sv_UserName
do

# HEREDOC is not quoted, so variables are expanded before entry.
# This means that new variables cannot be created inside.
 
/usr/bin/su ${sv_UserName} <<HEREDOC

"${GLB_SV_PROJECTDIRPATH}"/bin/Trigger "Usr-VolDidUnmount" "${GLB_SV_MOUNTEDVOLUMEDIRPATH}" &

HEREDOC

  # -- We are back as the root user.

done

# ---

# We dont want to quit until all sub tasks are finished
while [ -n "$(jobs -r)" ]
do
  # We don't want to hog the CPU - so lets sleep a while
  sleep 1
done
