#!/bin/bash
#
# Short:    Do something when an app is Terminated
# Author:   Mark J Swift
# Version:  3.2.5
# Modified: 30-Dec-2020
#
# Called by appwarden as follows:    
#   appwarden-DidTerminate "DidTerminate:Epoch:ApplicationBundleIdentifier:ApplicationName:ApplicationPath:ApplicationProcessIdentifier"

# ---
  
# Assume that all code is run from a subdirectory of the main project directory
GLB_SV_PROJECTDIRPATH="$(dirname $(dirname ${0}))"

# ---

# Get user name
GLB_SV_RUNUSERNAME="$(whoami)"

if [ "${GLB_SV_RUNUSERNAME}" = "root" ]
then
  exit 0
fi

# ---

# Check we have the correct number of parameters
if [ $# -lt 1 ]
then
  exit 0
fi

# -- Trigger the App-DidLaunch policy (and pass it the app info) --

"${GLB_SV_PROJECTDIRPATH}"/bin/Trigger "Usr-AppDidTerminate" "${1}" &

# ---

# We dont want to quit until all sub tasks are finished
while [ -n "$(jobs -r)" ]
do
  # We don't want to hog the CPU - so lets sleep a while
  sleep 1
done
