#!/bin/bash
#
# Short:    Policy script - Write Debug info to the LabWarden config
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   All events (as user or root)
#
# Called as follows:    
#   Debug <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

case ${sv_EventName} in
    
*)
  # -- BEGIN POLICY --

  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptStartEpoch" "${LW_sv_ThisScriptStartEpoch}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LabWardenVersion" "${LW_sv_LabWardenVersion}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LabWardenSignature" "${LW_sv_LabWardenSignature}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_LogMaxLength" "${LW_iv_LogMaxLength}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LogIsActiveDefault" "${LW_bv_LogIsActiveDefault}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LogIsActiveStatus" "${LW_bv_LogIsActiveStatus}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_BinDirPath" "${LW_sv_BinDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ConfigDirPath" "${LW_sv_ConfigDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptFilePath" "${LW_sv_ThisScriptFilePath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptDirPath" "${LW_sv_ThisScriptDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptFileName" "${LW_sv_ThisScriptFileName}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptName" "${LW_sv_ThisScriptName}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_ThisScriptPID" "${LW_iv_ThisScriptPID}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisScriptTempDirPath" "${LW_sv_ThisScriptTempDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisUserTempDirPath" "${LW_sv_ThisUserTempDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisUserLogDirPath" "${LW_sv_ThisUserLogDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisUserPrefDirPath" "${LW_sv_ThisUserPrefDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ThisUserName" "${LW_sv_ThisUserName}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_ThisUserID" "${LW_iv_ThisUserID}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_LoggedInUserID" "${LW_iv_LoggedInUserID}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LoggedInUserIsAdmin" "${LW_bv_LoggedInUserIsAdmin}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LoggedInUserIsLocal" "${LW_bv_LoggedInUserIsLocal}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LoggedInUserIsMobile" "${LW_bv_LoggedInUserIsMobile}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LoggedInUserHomeDirPath" "${LW_sv_LoggedInUserHomeDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LoggedInUserLocalHomeDirPath" "${LW_sv_LoggedInUserLocalHomeDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LoggedInUserHomeNetworkDirPath" "${LW_sv_LoggedInUserHomeNetworkDirPath}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_LoggedInUserHomeNetworkURI" "${LW_sv_LoggedInUserHomeNetworkURI}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_bv_LoggedInUserHomeIsLocal" "${LW_bv_LoggedInUserHomeIsLocal}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_BuildVersionStampAsNumber" "${LW_iv_BuildVersionStampAsNumber}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_BuildVersionStampAsString" "${LW_sv_BuildVersionStampAsString}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_iv_SystemVersionStampAsNumber" "${LW_iv_SystemVersionStampAsNumber}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_SystemVersionStampAsString" "${LW_sv_SystemVersionStampAsString}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_IPv4PrimaryService" "${LW_sv_IPv4PrimaryService}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_NetworkServiceDHCPOption15" "${LW_sv_NetworkServiceDHCPOption15}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_NetworkServiceInterfaceName" "${LW_sv_NetworkServiceInterfaceName}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_NetworkServiceInterfaceDevice" "${LW_sv_NetworkServiceInterfaceDevice}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_NetworkServiceInterfaceHardware" "${LW_sv_NetworkServiceInterfaceHardware}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ADTrustAccount" "${LW_sv_ADTrustAccount}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ADComputerName" "${LW_sv_ADComputerName}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ADDomainNameFlat" "${LW_sv_ADDomainNameFlat}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ADDomainNameDNS" "${LW_sv_ADDomainNameDNS}"
  LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:${sv_EventName}:LW_sv_ADTrustPassword" "$(echo "${LW_sv_ADTrustPassword}" | sed "s|.|\*|g")"

  # Trigger an event 
  LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

  # -- END POLICY --
  ;;

esac

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"


# ---
