#!/bin/bash
#
# Short:    Policy script - Write Debug info to the LabWarden preferences
# Author:   Mark J Swift
# Version:  1.0.82
# Modified: 27-May-2016
#
# Triggered by the following events:
#   All events (as user or root)
#
# Called as follows:    
#   Debug <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.82"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

case ${LCL_EventName} in
    
*)
  # -- BEGIN POLICY --

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserName" "${GLB_LoggedInUserName}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:OptionalParam" "${LCL_OptionalParam}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:BinDir" "${GLB_BinDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LabConfigDir" "${GLB_LabConfigDir}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisScriptName" "${GLB_ThisScriptName}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisScriptPID" "${GLB_ThisScriptPID}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisUserTempDir" "${GLB_ThisUserTempDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisUserLogDir" "${GLB_ThisUserLogDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisUserPrefDir" "${GLB_ThisUserPrefDir}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisUserName" "${GLB_ThisUserName}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ThisUserID" "${GLB_ThisUserID}"
  
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserID" "${GLB_LoggedInUserID}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserIsAdmin" "${GLB_LoggedInUserIsAdmin}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserIsLocal" "${GLB_LoggedInUserIsLocal}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserIsMobile" "${GLB_LoggedInUserIsMobile}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserHomeDir" "${GLB_LoggedInUserHomeDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserLocalHomeDir" "${GLB_LoggedInUserLocalHomeDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserHomeNetworkDir" "${GLB_LoggedInUserHomeNetworkDir}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserHomeNetworkURI" "${GLB_LoggedInUserHomeNetworkURI}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:LoggedInUserHomeIsLocal" "${GLB_LoggedInUserHomeIsLocal}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:BuildVersionStampAsNumber" "${GLB_BuildVersionStampAsNumber}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:BuildVersionStampAsString" "${GLB_BuildVersionStampAsString}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:SystemVersionStampAsNumber" "${GLB_SystemVersionStampAsNumber}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:SystemVersionStampAsString" "${GLB_SystemVersionStampAsString}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:IPv4PrimaryService" "${GLB_IPv4PrimaryService}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:NetworkServiceDHCPOption15" "${GLB_NetworkServiceDHCPOption15}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:NetworkServiceInterfaceName" "${GLB_NetworkServiceInterfaceName}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:NetworkServiceInterfaceDevice" "${GLB_NetworkServiceInterfaceDevice}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:NetworkServiceInterfaceHardware" "${GLB_NetworkServiceInterfaceHardware}"

  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ADTrustAccount" "${GLB_ADTrustAccount}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ADDomainNameFlat" "${GLB_ADDomainNameFlat}"
  f_SetPlistProperty "${GLB_ThisUserPrefDir}/LabWarden.plist" ":${LCL_PolicyName}:LocalPrefs:${LCL_EventName}:ADTrustPassword" "$(echo "${GLB_ADTrustPassword}" | sed "s|.|\*|g")"

  # Trigger an event 
  f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

  # -- END POLICY --
  ;;

esac

# Remove temporary files
rm -fR "${GLB_ThisScriptTempDir}"


# ---
