#!/bin/bash
#
# Short:    Sys Policy script - Sets system sleep options
# Author:   Mark J Swift
# Version:  2.0.10
# Modified: 12-Jun-2017
#
# Triggered by the following events:
#   Sys-LoginWindow          (as root)
#   Sys-ConsoleUserLoggedIn  (as root)
#
# Called as follows:    
#   Sys-SleepSettings <ConfigFilePath> <ConfigEntryName> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="2.0.10"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config file path
sv_ConfigFilePath="${1}"
if test -z "${sv_ConfigFilePath}"
then
  # We need something to work with
  exit 0
fi

# Get config entry name. This is the entry in the config that holds the configurable parameters for this policy.
sv_ConfigEntryName="${2}"

# Get event History
sv_EventHistory="${3}"

# Calculate the event that triggered this policy.
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get the name of the logged in user, a null string signifies no-one is logged in
GLB_sv_LoggedInUserName="${4}"

# Get optional parameter
# This is a general variable that is currently used to pass the following info:
#   Application info during a AppWillLaunch, AppDidLaunch or AppDidTerminate event.
#   User info during a Sys-ConsoleUserLoggedIn, Sys-ConsoleUserLoggedOut, Sys-ConsoleUserSwitch, Sys-Login or Sys-Logout event.
sv_OptionalParam="${5}"

# Get info from optional parameter
case ${sv_EventName} in

Sys-ConsoleUserLoggedIn|Sys-ConsoleUserLoggedOut|Sys-ConsoleUserSwitch|Sys-Login|Sys-Logout)
  GLB_sv_LoggedInUserName="${sv_OptionalParam}"
  ;;
  
esac

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Common.sh
fi

# By the time we get here, quite a few global variables have been set up.
# Look at 'CommonLib' for a complete list.

# ---

# Get policy name (Name of this script)
sv_PolicyName="${GLB_sv_ThisScriptName}"

# ---

# Calculate the pref file paths

# Local prefs are referenced by Policy UUID and are local to the running user. These are deleted when the policy is updated or uninstalled.
sv_ThisUserLocalPrefFilePath="${GLB_sv_ThisUserPrefDirPath}/${sv_ConfigEntryName}.plist"

# Global prefs are referenced by Policy Name and are read/write root but read-only for normal users. These survive policy updates and uninstalls.
sv_ThisPolicyGlobalPrefFilePath="${GLB_sv_ProjectConfigDirPath}/Config/Global/${sv_PolicyName}.plist"

# ---

# Usr-PolicyInstall & Usr-PolicyUninstall events (which are called as a normal user) are ignored by system policies

if [ "${sv_EventName}" = "Usr-PolicyInstall" ] || [ "${sv_EventName}" = "Usr-PolicyUninstall" ]
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Event '${sv_EventHistory}' ignored by policy '${sv_PolicyName}'"
  exit 0
fi

# ---

nf_SetSystemSleepSettings() # Trigger
{
  local sv_Trigger
  local iv_PowerSystemSleepSecs
  local iv_PowerDisplaySleepSecs
  local iv_PowerDiskSleepSecs
  local iv_BatterySystemSleepSecs
  local iv_BatteryDisplaySleepSecs
  local iv_BatteryDiskSleepSecs
  
  sv_Trigger="${1}"

  iv_PowerSystemSleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Power:SystemSleep")"
  if test -n "${iv_PowerSystemSleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting sleep=${iv_PowerSystemSleepSecs} (on power)"
    /usr/bin/pmset -a sleep "${iv_PowerSystemSleepSecs}"
  fi
  
  iv_PowerDisplaySleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Power:DisplaySleep")"
  if test -n "${iv_PowerDisplaySleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting displaysleep=${iv_PowerDisplaySleepSecs} (on power)"
    /usr/bin/pmset -a displaysleep "${iv_PowerDisplaySleepSecs}"
  fi
  
  iv_PowerDiskSleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Power:DiskSleep")"
  if test -n "${iv_PowerDiskSleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting disksleep=${iv_PowerDiskSleepSecs} (on power)"
    /usr/bin/pmset -a disksleep "${iv_PowerDiskSleepSecs}"
  fi
  
  iv_BatterySystemSleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Battery:SystemSleep")"
  if test -n "${iv_BatterySystemSleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting sleep=${iv_BatterySystemSleepSecs} (on battery)"
    /usr/bin/pmset -b sleep "${iv_BatterySystemSleepSecs}"
  fi
  
  iv_BatteryDisplaySleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Battery:DisplaySleep")"
  if test -n "${iv_BatteryDisplaySleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting displaysleep=${iv_BatteryDisplaySleepSecs} (on battery)"
    /usr/bin/pmset -b displaysleep "${iv_BatteryDisplaySleepSecs}"
  fi
  
  iv_BatteryDiskSleepSecs="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:${sv_Trigger}:Battery:DiskSleep")"
  if test -n "${iv_BatteryDiskSleepSecs}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting disksleep=${iv_BatteryDiskSleepSecs} (on battery)"
    /usr/bin/pmset -b disksleep "${iv_BatteryDiskSleepSecs}"
  fi
  
  /usr/bin/pmset -a autorestart 1 womp 1

}

# ---

# Execute the Policy

# Take a note of the Policy call
GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Policy '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${GLB_sv_ThisUserName}'"

# ---

# Exit if we are not root
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  GLB_nf_QuickExit "Policy aborted - User '${GLB_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
fi

# ---

case ${sv_EventName} in
    
Sys-LoginWindow|Sys-ConsoleUserLoggedIn)
  nf_SetSystemSleepSettings "${sv_EventName}"
  ;;

Sys-PolicyInstall|Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_nf_QuickExit "Policy aborted - Trigger '${sv_EventName}' is not supported by policy '${sv_PolicyName}'"
  ;;

esac

# ---

# Take a note that the Policy is complete
GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Policy done."

# Trigger an event
#/usr/local/LabWarden/lib/Trigger "${sv_EventHistory}:${sv_PolicyName}" "$(whoami)" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${GLB_sv_ThisScriptTempDirPath}"

# ---
