#!/bin/bash
#
# Short:    Policy script - Turns wireless on or off, and defines whether non-admins can change the wireless state
# Author:   Mark J Swift
# Version:  2.0.10
# Modified: 12-Jun-2017
#
# Triggered by the following events:
#   Sys-Boot (as root)
#
# Called as follows:    
#   Sys-WirelessSetState <ConfigFilePath> <ConfigEntryName> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="2.0.10"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config file path
sv_ConfigFilePath="${1}"
if test -z "${sv_ConfigFilePath}"
then
  # We need something to work with
  exit 0
fi

# Get config entry name. This is the entry in the config that holds the configurable parameters for this policy.
sv_ConfigEntryName="${2}"

# Get event History
sv_EventHistory="${3}"

# Calculate the event that triggered this policy.
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get the name of the logged in user, a null string signifies no-one is logged in
GLB_sv_LoggedInUserName="${4}"

# Get optional parameter
# This is a general variable that is currently used to pass the following info:
#   Application info during a AppWillLaunch, AppDidLaunch or AppDidTerminate event.
#   User info during a Sys-ConsoleUserLoggedIn, Sys-ConsoleUserLoggedOut, Sys-ConsoleUserSwitch, Sys-Login or Sys-Logout event.
sv_OptionalParam="${5}"

# Get info from optional parameter
case ${sv_EventName} in

Sys-ConsoleUserLoggedIn|Sys-ConsoleUserLoggedOut|Sys-ConsoleUserSwitch|Sys-Login|Sys-Logout)
  GLB_sv_LoggedInUserName="${sv_OptionalParam}"
  ;;
  
esac

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_sv_ProjectSignature}"
then
  . /usr/local/LabWarden/inc/Common.sh
fi

# By the time we get here, quite a few global variables have been set up.
# Look at 'CommonLib' for a complete list.

# ---

# Get policy name (Name of this script)
sv_PolicyName="${GLB_sv_ThisScriptName}"

# ---

# Calculate the pref file paths

# Local prefs are referenced by Policy UUID and are local to the running user. These are deleted when the policy is updated or uninstalled.
sv_ThisUserLocalPrefFilePath="${GLB_sv_ThisUserPrefDirPath}/${sv_ConfigEntryName}.plist"

# Global prefs are referenced by Policy Name and are read/write root but read-only for normal users. These survive policy updates and uninstalls.
sv_ThisPolicyGlobalPrefFilePath="${GLB_sv_ProjectConfigDirPath}/Config/Global/${sv_PolicyName}.plist"

# ---

# Usr-PolicyInstall & Usr-PolicyUninstall events (which are called as a normal user) are ignored by system policies

if [ "${sv_EventName}" = "Usr-PolicyInstall" ] || [ "${sv_EventName}" = "Usr-PolicyUninstall" ]
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelDebug} "Event '${sv_EventHistory}' ignored by policy '${sv_PolicyName}'"
  exit 0
fi

# ---

# Execute the Policy

# Take a note of the Policy call
GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Policy '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${GLB_sv_ThisUserName}'"

# ---

# Exit if we are not root
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  GLB_nf_QuickExit "Policy aborted - User '${GLB_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
fi

# ---

# Exit if there is no wi-fi hardware
if test -z "${GLB_sv_WirelessInterfaceDevice}"
then
  GLB_nf_QuickExit "Policy aborted - There is no Wi-Fi hardware (thats odd)"
fi

# ---

case ${sv_EventName} in
    
Sys-Boot|Sys-PolicyInstall)
  sv_WirelessState="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:WirelessState")"

  if test -n "${sv_WirelessState}"
  then
    # Turn Wi-Fi port on or off
    networksetup -setairportpower ${GLB_sv_WirelessInterfaceDevice} ${sv_WirelessState}

    bv_RequireAdminIBSS="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:RequireAdminIBSS")"
    if [ "${bv_RequireAdminIBSS}" = "true" ]
    then
      sv_YesNoAdminIBSS="YES"
    else
      sv_YesNoAdminIBSS="NO"
    fi
      
    bv_RequireAdminNetworkChange="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:RequireAdminNetworkChange")"
    if [ "${bv_RequireAdminNetworkChange}" = "true" ]
    then
      sv_YesNoAdminNetworkChange="YES"
    else
      sv_YesNoAdminNetworkChange="NO"
    fi
      
    bv_RequireAdminPowerToggle="$(GLB_sf_GetPlistProperty "${sv_ConfigFilePath}" ":${sv_ConfigEntryName}:Config:RequireAdminPowerToggle")"
    if [ "${bv_RequireAdminPowerToggle}" = "true" ]
    then
      sv_YesNoAdminPowerToggle="YES"
    else
      sv_YesNoAdminPowerToggle="NO"
    fi
      
    # Set the Wi-Fi options
    /usr/libexec/airportd prefs RequireAdminIBSS="${sv_YesNoAdminIBSS}" RequireAdminNetworkChange="${sv_YesNoAdminNetworkChange}" RequireAdminPowerToggle="${sv_YesNoAdminPowerToggle}"
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Setting Wi-Fi options to RequireAdminIBSS=${sv_YesNoAdminIBSS} RequireAdminNetworkChange=${sv_YesNoAdminNetworkChange} RequireAdminPowerToggle=${sv_YesNoAdminPowerToggle}"
  fi
  ;;

Sys-PolicyUninstall)
  # Do nothing
  ;;
  
*)
  GLB_nf_QuickExit "Policy aborted - Trigger '${sv_EventName}' is not supported by policy '${sv_PolicyName}'"
  ;;

esac
  
# ---

# Take a note that the Policy is complete
GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Policy done."

# Trigger an event
#/usr/local/LabWarden/lib/Trigger "${sv_EventHistory}:${sv_PolicyName}" "$(whoami)" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${GLB_sv_ThisScriptTempDirPath}"

# ---
