#!/bin/bash
#
# Short:    Policy script - Delete system files
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemDeleteFiles <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else
  bv_PolicyExecuted="false"
  iv_PathCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path")"
  for (( iv_LoopCount=0; iv_LoopCount<${iv_PathCount}; iv_LoopCount++ ))
  do
    sv_DelPath="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path:${iv_LoopCount}")"

    # Sanitise the file/folder Path
    sv_DelPath=$(echo "/${sv_DelPath}" | sed "s|^/[/]*|/|;s|/$||")

    if test -n "${sv_DelPath}"
    then
      if test -e "${sv_DelPath}"
      then
        if test -d "${sv_DelPath}"
        then
          # Delete folder
          LW_nf_logmessage "NOTE, deleting folder '${sv_DelPath}' "
          rm -fR "${LW_sv_LoggedInUserHomeDirPath}${sv_DelPath}"
          if [ "$?" = "0" ]
          then
            bv_PolicyExecuted="true"
          fi
        else
          # Delete file
          LW_nf_logmessage "NOTE, deleting file '${sv_DelPath}' "
          rm -f "${LW_sv_LoggedInUserHomeDirPath}${sv_DelPath}"
          if [ "$?" = "0" ]
          then
            bv_PolicyExecuted="true"
          fi
        fi
      fi
    fi

  done
  
  if [ "${bv_PolicyExecuted}" = "false" ]
  then
    LW_nf_QuickExit "NOTE, policy aborted: there are no system files to delete."
    
  else
    # Restart if there are any system files removed
    LW_nf_RestartNow "ATTENTION, system files have been removed - we need to reboot."
    
  fi

fi
  
# We might never get here, but I don't suppose that matters
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
