#!/bin/bash
#
# Short:    Policy script - Set System Time server options
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemTimeServer <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else    
  bv_PolicyExecuted="false"

  # Get time server
  sv_TimeServer="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:TimeServer")"
  /usr/sbin/systemsetup -setusingnetworktime off
  if test -n "${sv_TimeServer}"
  then
    LW_nf_logmessage "NOTE, setting time server to '${sv_TimeServer}'."
    /usr/sbin/systemsetup -setnetworktimeserver "${sv_TimeServer}"
    /usr/sbin/systemsetup -setusingnetworktime on
    bv_PolicyExecuted="true"
  fi

  # Get time zone
  sv_TimeZone="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:TimeZone")"
  if test -n "${sv_TimeZone}"
  then
    LW_nf_logmessage "NOTE, setting time zone to '${sv_TimeZone}'."
    /usr/sbin/systemsetup -settimezone "${sv_TimeZone}"
    bv_PolicyExecuted="true"
  fi

  if [ "${bv_PolicyExecuted}" = "true" ]
  then
    LW_nf_logmessage "ATTENTION, time settings configured."
  
  else
    LW_nf_QuickExit "NOTE, policy aborted: No Time server or Time Zone defined"
    
  fi

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
