#!/bin/bash
#
# Short:    Policy script - Set User Experience
# Author:   Mark J Swift
# Version:  1.0.98
# Modified: 11-Oct-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemUserExperience <ConfigDir> <EventHistory> <LoggedInUser> <ConfigEntryName> <OptionalParam>

# REF: Remove network home question mark from dock - jclark - https://jamfnation.jamfsoftware.com/discussion.html?id=10753

# ---

sv_CodeVersion="1.0.98"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get the name of the logged in user, a null string signifies no-one is logged in
# This is generally null during a system event, and not null during a user event
LW_sv_LoggedInUserName="${3}"

# Get config entry name. This is the entry in the config that holds the configurable parameters for this policy.
sv_ConfigEntryName="${4}"

# Get optional parameter
# So far, this is only ever used to get Application info after a AppWillLaunch, AppDidLaunch or AppDidTerminate event.
sv_OptionalParam="${5}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

LW_nf_SetSearchPathForAD() # <recordpath> <value>
{
  local sv_RecordPath
  local sv_Value
  local bv_ReloadDirectoryServices
  local bv_AddActiveSearchPath
  local sv_SearchPath
  
  sv_RecordPath="${1}"
  sv_Value="${2}"

  bv_ReloadDirectoryServices="false"
  bv_AddActiveSearchPath="true"
  
  dscl "${sv_RecordPath}" -create / SearchPolicy CSPSearchPath

  while read sv_SearchPath
  do
    if [ "${sv_SearchPath}" = "${sv_Value}" ]
    then
      bv_AddActiveSearchPath="false"
      
    else
      LW_nf_logmessage "NOTE, deleting CSPSearchPath: '${sv_SearchPath}' from '${sv_RecordPath}'"
      bv_ReloadDirectoryServices="true"
      dscl "${sv_RecordPath}" -delete / CSPSearchPath "${sv_SearchPath}"
    fi
  done < <(dscl "${sv_RecordPath}" -read / CSPSearchPath | sed 's|^CSPSearchPath:||;s|^[ ]*||;/^\s*$/d' | grep "/Active Directory")
  
  if [ "${bv_AddActiveSearchPath}" = "true" ]
  then
    LW_nf_logmessage "NOTE, appending CSPSearchPath: '${sv_Value}' to '${sv_RecordPath}'"
    dscl "${sv_RecordPath}" -append / CSPSearchPath "${sv_Value}"
    bv_ReloadDirectoryServices="true"
  fi

  if [ "${bv_ReloadDirectoryServices}" = "true" ]
  then
    killall DirectoryService
  fi
}

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else    
  LW_nf_logmessage "ATTENTION, setting user experience (how we handle home folders for network users)"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:mobile")"
  sv_OPTmobile="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTmobile="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:mobileconfirm")"
  sv_OPTmobileconfirm="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTmobileconfirm="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:localhome")"
  sv_OPTlocalhome="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTlocalhome="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:sharepoint")"
  sv_OPTsharepoint="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTsharepoint="enable"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:useuncpath")"
  sv_OPTuseuncpath="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTuseuncpath="enable"

  sv_OPTprotocol="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:protocol")"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:alldomains")"
  sv_OPTallomains="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTallomains="enable"

  sv_OPTpreferredserver="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:preferredserver")"

  dsconfigad -mobile ${sv_OPTmobile}
  dsconfigad -mobileconfirm ${sv_OPTmobileconfirm}
  dsconfigad -localhome ${sv_OPTlocalhome}
  dsconfigad -sharepoint ${sv_OPTsharepoint}
  dsconfigad -useuncpath ${sv_OPTuseuncpath}
  dsconfigad -protocol ${sv_OPTprotocol}
  
  if test -n "${sv_OPTpreferredserver}"
  then
    dsconfigad -preferred ${sv_OPTpreferredserver}
  fi

  dsconfigad -alldomains ${sv_OPTallomains}

  if [ "${sv_OPTallomains}" = "enable" ]
  then
    sv_ActiveSearchPath="/Active Directory/${LW_sv_ADDomainNameFlat}/All Domains"
  else
    sv_ActiveSearchPath="/Active Directory/${LW_sv_ADDomainNameFlat}/${LW_sv_ADDomainNameDNS}"
  fi
  
  LW_nf_SetSearchPathForAD "/Search" "${sv_ActiveSearchPath}"
  LW_nf_SetSearchPathForAD "/Search/Contacts" "${sv_ActiveSearchPath}"
  
  # Remove network home question mark from dock - thanks to - jclark - https://jamfnation.jamfsoftware.com/discussion.html?id=10753
  /usr/libexec/PlistBuddy 2>/dev/null -c "Delete :module\ options:ActiveDirectory:managed\ client\ template:mcx_application_data:com.apple.dock:Forced:0:mcx_preference_settings:MCXDockSpecialFolders-Raw:0" "/Library/Preferences/OpenDirectory/Configurations/Active Directory/${LW_sv_ADDomainNameFlat}.plist"

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
