#!/bin/bash
#
# Short:    Policy script - Forget SSIDs and remove SSID passwords
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemWirelessForgetSSID <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.90"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else
  bv_PolicyExecuted="false"

  # Get the the hardware port for wireless (eg en1)
  sv_WirelessHardwarePort="$(networksetup -listallhardwareports | tr "\n" ":" | sed "s|^[:]*||;s|::|;|g" | tr ";" "\n" | grep "Wi-Fi" | sed "s|\(.*Device:[ ]*\)\([^:]*\)\(.*\)|\2|")"
  
  if test -n "${sv_WirelessHardwarePort}"
  then
  
    # Forget a list of SSIDs
    iv_SSIDCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:SSID")"
    for (( iv_LoopCount=0; iv_LoopCount<${iv_SSIDCount}; iv_LoopCount++ ))
    do
      sv_SSIDName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:SSID:${iv_LoopCount}")"
      if test -n "${sv_SSIDName}"
      then
        if test -n "$(networksetup -listpreferredwirelessnetworks en1 | tr -d "\t" | grep -v "^Preferred networks on" | grep -v "No preferred networks" | grep "^${sv_SSIDName}$")"
        then
          bv_PolicyExecuted="true"
          LW_nf_logmessage "NOTE, removing '${sv_SSIDName}' from preferred networks on ${sv_WirelessHardwarePort}"
          networksetup -removepreferredwirelessnetwork en1 "${sv_SSIDName}"
        fi
        security delete-generic-password -D "AirPort network password" -l "${sv_SSIDName}" /Library/Keychains/System.keychain
      fi
    done

    if [ "${bv_PolicyExecuted}" = "true" ]
    then
      LW_nf_logmessage "ATTENTION, some SSIDs have been forgotten."
  
    else
      LW_nf_QuickExit "NOTE, policy aborted: "
    
    fi
  
  fi

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
srm -fR "${LW_sv_ThisScriptTempDirPath}"

# ---
