#!/bin/bash
#
# Short:    Policy script - Set System Time server options
# Author:   Mark J Swift
# Version:  1.0.86
# Modified: 09-Jun-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemTimeServer <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.86"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if [ "${GLB_ThisUserName}" != "root" ]
then
  f_QuickExit "NOTE, policy aborted: User '${GLB_ThisUserName}' is not supported by policy '${LCL_PolicyName}'"
  
else    
  LCL_PolicyExecuted="false"

  # Get time server
  LCL_TimeServer="$(f_GetPlistProperty "${LCL_ConfigDir}/LabWarden.plist" ":${LCL_PolicyName}:Config:TimeServer")"
  /usr/sbin/systemsetup -setusingnetworktime off
  if test -n "${LCL_TimeServer}"
  then
    f_logmessage "NOTE, setting time server to '${LCL_TimeServer}'."
    /usr/sbin/systemsetup -setnetworktimeserver "${LCL_TimeServer}"
    /usr/sbin/systemsetup -setusingnetworktime on
    LCL_PolicyExecuted="true"
  fi

  # Get time zone
  LCL_TimeZone="$(f_GetPlistProperty "${LCL_ConfigDir}/LabWarden.plist" ":${LCL_PolicyName}:Config:TimeZone")"
  if test -n "${LCL_TimeZone}"
  then
    f_logmessage "NOTE, setting time zone to '${LCL_TimeZone}'."
    /usr/sbin/systemsetup -settimezone "${LCL_TimeZone}"
    LCL_PolicyExecuted="true"
  fi

  if [ "${LCL_PolicyExecuted}" = "true" ]
  then
    f_logmessage "ATTENTION, time settings configured."
  
  else
    f_QuickExit "NOTE, policy aborted: No Time server or Time Zone defined"
    
  fi

fi
  
# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
srm -fR "${GLB_ThisScriptTempDir}"

# ---
