#!/bin/bash
#
# Short:    Policy script - Forget SSIDs and remove SSID passwords
# Author:   Mark J Swift
# Version:  1.0.82
# Modified: 27-May-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemWirelessForgetSSID <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.82"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if [ "${GLB_ThisUserName}" != "root" ]
then
  f_QuickExit "NOTE, policy aborted: User '${GLB_ThisUserName}' is not supported by policy '${LCL_PolicyName}'"
  
else
  LCL_PolicyExecuted="false"

  # Get the the hardware port for wireless (eg en1)
  LCL_WirelessHardwarePort="$(networksetup -listallhardwareports | tr "\n" ":" | sed "s|^[:]*||;s|::|;|g" | tr ";" "\n" | grep "Wi-Fi" | sed "s|\(.*Device:[ ]*\)\([^:]*\)\(.*\)|\2|")"
  
  if test -n "${LCL_WirelessHardwarePort}"
  then
  
    # Forget a list of SSIDs
    LCL_SSIDCount="$(f_GetPlistArraySize "${LCL_ConfigDir}/LabWarden.plist" ":${LCL_PolicyName}:Config:SSID")"
    for (( LCL_i=0; LCL_i<${LCL_SSIDCount}; LCL_i++ ))
    do
      LCL_SSID="$(f_GetPlistProperty "${LCL_ConfigDir}/LabWarden.plist" ":${LCL_PolicyName}:Config:SSID:${LCL_i}")"
      if test -n "${LCL_SSID}"
      then
        if test -n "$(networksetup -listpreferredwirelessnetworks en1 | tr -d "\t" | grep -v "^Preferred networks on" | grep -v "No preferred networks" | grep "^${LCL_SSID}$")"
        then
          LCL_PolicyExecuted="true"
          f_logmessage "NOTE, removing '${LCL_SSID}' from preferred networks on ${LCL_WirelessHardwarePort}"
          networksetup -removepreferredwirelessnetwork en1 "${LCL_SSID}"
        fi
        security delete-generic-password -D "AirPort network password" -l "${LCL_SSID}" /Library/Keychains/System.keychain
      fi
    done

    if [ "${LCL_PolicyExecuted}" = "true" ]
    then
      f_logmessage "ATTENTION, some SSIDs have been forgotten."
  
    else
      f_QuickExit "NOTE, policy aborted: "
    
    fi
  
  fi

fi
  
# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
rm -fR "${GLB_ThisScriptTempDir}"

# ---
