#!/bin/bash
#
# Short:    Policy script - Set User Experience
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemUserExperience <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# REF: Remove network home question mark from dock - jclark - https://jamfnation.jamfsoftware.com/discussion.html?id=10753

# ---

sv_CodeVersion="1.0.90"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else    
  LW_nf_logmessage "ATTENTION, setting user experience (how we handle home folders for network users)"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:mobile")"
  sv_OPTmobile="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTmobile="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:mobileconfirm")"
  sv_OPTmobileconfirm="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTmobileconfirm="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:localhome")"
  sv_OPTlocalhome="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTlocalhome="enable"
  
  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:sharepoint")"
  sv_OPTsharepoint="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTsharepoint="enable"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:useuncpath")"
  sv_OPTuseuncpath="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTuseuncpath="enable"

  sv_OPTprotocol="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:protocol")"

  sv_PropertyName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:alldomains")"
  sv_OPTallomains="disable";[ "${sv_PropertyName}" = "true" ] && sv_OPTallomains="enable"

  sv_OPTpreferredserver="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:preferredserver")"

  dsconfigad -mobile ${sv_OPTmobile}
  dsconfigad -mobileconfirm ${sv_OPTmobileconfirm}
  dsconfigad -localhome ${sv_OPTlocalhome}
  dsconfigad -sharepoint ${sv_OPTsharepoint}
  dsconfigad -useuncpath ${sv_OPTuseuncpath}
  dsconfigad -protocol ${sv_OPTprotocol}
  
  if test -n "${sv_OPTpreferredserver}"
  then
    dsconfigad -preferred ${sv_OPTpreferredserver}
  fi

  dsconfigad -alldomains ${sv_OPTallomains}

  # Remove network home question mark from dock - thanks to - jclark - https://jamfnation.jamfsoftware.com/discussion.html?id=10753
  /usr/libexec/PlistBuddy 2>/dev/null -c "Delete :module\ options:ActiveDirectory:managed\ client\ template:mcx_application_data:com.apple.dock:Forced:0:mcx_preference_settings:MCXDockSpecialFolders-Raw:0" "/Library/Preferences/OpenDirectory/Configurations/Active Directory/${LW_sv_ADDomainNameFlat}.plist"

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
srm -fR "${LW_sv_ThisScriptTempDirPath}"

# ---
