#!/bin/bash
#
# Short:    Policy script - Delete old user profiles
# Author:   Mark J Swift
# Version:  1.0.93
# Modified: 21-Aug-2016
#
# Triggered by the following events:
#   LoginWindowIdle (as root)
#
# Called as follows:    
#   SystemDeleteOldUserProfiles <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.93"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else    
  bv_PolicyExecuted="false"

  # Get the days allowable between logins before profiles are deleted
  iv_LoginMaxAgeDays="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:LoginMaxAgeDays")"
  
  # Get the earliest creation date/time allowable - cache files (in /private/var/folders) created earlier than this are deleted
  iv_UserCacheEarliestEpoch="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:UserCacheEarliestEpoch")"

  if test -z "${iv_LoginMaxAgeDays}"
  then
    iv_LoginMaxAgeDays=62
  fi

  while read sv_FolderDirPath
  do
    if test -d "${sv_FolderDirPath}"
    then
      sv_UserName="$(stat -f "%Su" "${sv_FolderDirPath}")"
      
      # Check if user is a local account (returns "true" or "false")
      if [ "$(dseditgroup -o checkmember -m "${sv_UserName}" -n . localaccounts | cut -d" " -f1)" = "yes" ]
      then
        bv_UserIsLocal="true"
      else
        bv_UserIsLocal="false"
      fi
    
      # Only Delete user folders for network users
      if [ "${bv_UserIsLocal}" = "false" ]
      then
      
        if test -n "$(dscl 2>/dev/null localhost -read /Local/Default/Users/${sv_UserName} OriginalHomeDirectory)"
        then
          bv_UserIsMobile="true"
        else
          bv_UserIsMobile="false"
        fi

        # Only delete user folders for non-mobile accounts
        if [ "${bv_UserIsMobile}" = "false" ]
        then
        
          bv_DeleteProfile="false"
          if test -e "${sv_FolderDirPath}/Library/Preferences/com.apple.finder.plist"
          then
            iv_LastUseEpoch=$(stat -f "%m" "${sv_FolderDirPath}/Library/Preferences/com.apple.finder.plist")
            if [ $((${LW_iv_ThisScriptStartEpoch}-${iv_LastUseEpoch})) -gt $((${iv_LoginMaxAgeDays}*24*60*60)) ]
            then
              bv_DeleteProfile="true"
              LW_nf_logmessage "NOTE, user '${sv_UserName}' hasn't logged on for more than ${iv_LoginMaxAgeDays} days"
            fi
        
          else
            bv_DeleteProfile="true"
            LW_nf_logmessage "NOTE, user '${sv_UserName}' has never logged on"
          fi
        
        fi
        
        if [ "${bv_DeleteProfile}" = "true" ]
        then
          bv_PolicyExecuted="true"
          LW_nf_logmessage "ATTENTION, deleting profle for user '${sv_UserName}'"
          
          # Delete the user folder
          rm -fR "${sv_FolderDirPath}"
          
          # Delete the user cache folders
          find /private/var/folders \( -depth 2 -prune \) -and -user "${sv_UserName}" -exec rm -fR "{}" \; 
        fi
      fi
      
      if test -n "${iv_UserCacheEarliestEpoch}"
      then
        while read sv_DelPath
        do
          iv_CreatedEpoch=$(stat -f "%c" "${sv_DelPath}")
          if [ ${iv_CreatedEpoch} -lt ${iv_UserCacheEarliestEpoch} ]
          then
            bv_PolicyExecuted="true"
            LW_nf_logmessage "ATTENTION, deleting outdated cache folder for user '${sv_UserName}'"
            rm -fR "${sv_DelPath}"
          fi

        done < <(find /private/var/folders \( -depth 2 -prune \) -and \( -user "${sv_UserName}" \))
      fi
    
      if [ "${bv_PolicyExecuted}" = "false" ]
      then
        LW_nf_QuickExit "NOTE, policy aborted: there are no old user profiles to delete"
    
      fi
      
    fi
  done < <(find /Users \( -depth 1 -prune \) -and \( -type d \) -and \( ! -user root \))

fi

# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
