#!/bin/bash
#
# Short:    Policy script - Install package(s) from folder
# Author:   Mark J Swift
# Version:  1.0.90
# Modified: 01-Jul-2016
#
# Triggered by the following events:
#   Boot (as root)
#
# Called as follows:    
#   SystemInstallPackageFromFolder <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.90"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if [ "${LW_sv_ThisUserName}" != "root" ]
then
  LW_nf_QuickExit "NOTE, policy aborted: User '${LW_sv_ThisUserName}' is not supported by policy '${sv_PolicyName}'"
  
else    
  bv_PolicyExecuted="false"

  iv_PathCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path")"
  for (( iv_LoopCount=0; iv_LoopCount<${iv_PathCount}; iv_LoopCount++ ))
  do
    sv_PackageDirPath="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path:${iv_LoopCount}")"
    if test -n "${sv_PackageDirPath}"
    then
      while read sv_PackageFilePath
      do
        sv_PackageFileShasum="$(shasum -a 256 "${sv_PackageFilePath}")"
        if ! test -n "$(LW_sf_GetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:Installed" | grep -v "{" | grep -v "}" | sed "s|^[ ]*||;s|[ ]*$||" | grep -E "^${sv_PackageFileShasum}$")"
        then
          bv_PolicyExecuted="true"
          iv_InstalledCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:Installed")"
          LW_nf_logmessage "NOTE, Installing ${sv_PackageFilePath}"
          installer -pkg "${sv_PackageFilePath}" -target /
          LW_nf_SetPlistProperty "${LW_sv_ThisUserPrefDirPath}/LabWarden.plist" ":${sv_PolicyName}:LocalPrefs:Installed:${iv_InstalledCount}" "${sv_PackageFileShasum}"
        fi
      done < <(find "${sv_PackageDirPath}" -iname "*.pkg")
    fi
  done
  
  if [ "${bv_PolicyExecuted}" = "true" ]
  then
    # Restart if there are any packages installed
    LW_nf_RestartNow "ATTENTION, packages installed - we need to reboot."
  
  else
    LW_nf_QuickExit "NOTE, policy aborted: No packages to install"
    
  fi

fi
  
# We might never get here, but I don't suppose that matters
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
srm -fR "${LW_sv_ThisScriptTempDirPath}"

# ---
