#!/bin/bash
#
# Short:    Policy script - Check user network home folder quota usage
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   UserPoll (as user)
#
# Called at regular intervals as follows:    
#   UserCheckQuotaOnNetHome <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if test -z "${LW_sv_LoggedInUserName}"
then
  LW_nf_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ "${LW_bv_LoggedInUserIsLocal}" = "true" ]
  then
    LW_nf_QuickExit "NOTE, policy aborted: User account is local."
    
  else
    # We are a network account
    
    if [ -z "${LW_sv_LoggedInUserHomeNetworkDirPath}" ]
    then
      LW_nf_QuickExit "NOTE, policy aborted: Network share unavailable."

    else
      # The original home network share is mounted and available

      if [ ! -e "${LW_sv_LoggedInUserHomeNetworkDirPath}" ]
      then
        LW_nf_QuickExit "NOTE, policy aborted: Network home unavailable."
        
      else
        # The original home network folder exists and is available

        iv_QuotaMegs=$(df -hm "${LW_sv_LoggedInUserHomeNetworkDirPath}" | awk 'NR==2 {print $2}')
        iv_FreeMegs=$(df -hm "${LW_sv_LoggedInUserHomeNetworkDirPath}" | awk 'NR==2 {print $4}')

        if [ ${iv_FreeMegs} -lt 100 ]
        then
          LW_nf_logmessage "ATTENTION, user told to 'free up some space'. ${iv_FreeMegs} MB left out of ${iv_QuotaMegs} MB."
          LW_nf_ShowNotification "FREE UP SOME SPACE" "Your network space is low. You have ${iv_FreeMegs} MB left out of ${iv_QuotaMegs} MB."
        else
          LW_nf_QuickExit "NOTE, policy aborted: User Network Home storage is fine. ${iv_FreeMegs} MB left out of ${iv_QuotaMegs} MB."
        fi
      
      fi
    fi
  
  fi

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
