#!/bin/bash
#
# Short:    Policy script - Set Desktop wallpaper for user
# Author:   Mark J Swift
# Version:  1.0.82
# Modified: 27-May-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called as follows:
#   UserDesktopWallpaperURI <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.82"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if test -z "${GLB_LoggedInUserName}"
then
  f_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else
  if [ ! -e "${GLB_LoggedInUserHomeDir}" ]
  then
    f_QuickExit "NOTE, policy aborted: Home folder doesn't exist."

  else
    # User home exists and is available

    LCL_DesktopWallpaperURI="$(f_GetPlistProperty "${LCL_ConfigDir}/LabWarden.plist" ":${LCL_PolicyName}:Config:DesktopWallpaperURI")"
    if test -z "${LCL_DesktopWallpaperURI}"
    then
      f_QuickExit "NOTE, policy aborted: No desktop URI defined."

    else
      LCL_DesktopWallpaperFile=$(f_ResolveFilename "${LCL_DesktopWallpaperURI}")
      if test -z "${LCL_DesktopWallpaperFile}"
      then
        f_QuickExit "NOTE, policy aborted: Desktop URI '${LCL_DesktopWallpaperURI}' is not resolvable."

      else
        f_logmessage "ATTENTION, setting Desktop Wallpaper"
        osascript -e "tell application \"System Events\" to set picture of every desktop to \"${LCL_DesktopWallpaperFile}\""
      fi
    fi
  
  fi

fi
  
# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
rm -fR "${GLB_ThisScriptTempDir}"

# ---
