#!/bin/bash
#
# Short:    Policy script - Check user network home folder quota usage
# Author:   Mark J Swift
# Version:  1.0.86
# Modified: 09-Jun-2016
#
# Triggered by the following events:
#   UserPoll (as user)
#
# Called at regular intervals as follows:    
#   UserCheckQuotaOnNetHome <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.86"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if test -z "${GLB_LoggedInUserName}"
then
  f_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ "${GLB_LoggedInUserIsLocal}" = "true" ]
  then
    f_QuickExit "NOTE, policy aborted: User account is local."
    
  else
    # We are a network account
    
    if [ -z "${GLB_LoggedInUserHomeNetworkDir}" ]
    then
      f_QuickExit "NOTE, policy aborted: Network share unavailable."

    else
      # The original home network share is mounted and available

      if [ ! -e "${GLB_LoggedInUserHomeNetworkDir}" ]
      then
        f_QuickExit "NOTE, policy aborted: Network home unavailable."
        
      else
        # The original home network folder exists and is available

        LCL_QuotaMegs=$(df -hm "${GLB_LoggedInUserHomeNetworkDir}" | awk 'NR==2 {print $2}')
        LCL_FreeMegs=$(df -hm "${GLB_LoggedInUserHomeNetworkDir}" | awk 'NR==2 {print $4}')

        if [ ${LCL_FreeMegs} -lt 100 ]
        then
          f_logmessage "ATTENTION, user told to 'free up some space'. ${LCL_FreeMegs} MB left out of ${LCL_QuotaMegs} MB."
          f_ShowNotification "FREE UP SOME SPACE" "Your network space is low. You have ${LCL_FreeMegs} MB left out of ${LCL_QuotaMegs} MB."
        else
          f_QuickExit "NOTE, policy aborted: User Network Home storage is fine. ${LCL_FreeMegs} MB left out of ${LCL_QuotaMegs} MB."
        fi
      
      fi
    fi
  
  fi

fi
  
# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
srm -fR "${GLB_ThisScriptTempDir}"

# ---
