#!/bin/bash
#
# Short:    Policy script - Set up sidebar for user
# Author:   Mark J Swift
# Version:  1.0.100
# Modified: 27-Oct-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called (as user) as follows:    
#   UserSidebarContent <ConfigDir> <EventHistory> <LoggedInUser> <ConfigEntryName> <OptionalParam>

# ---

sv_CodeVersion="1.0.100"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get the name of the logged in user, a null string signifies no-one is logged in
# This is generally null during a system event, and not null during a user event
LW_sv_LoggedInUserName="${3}"

# Get config entry name. This is the entry in the config that holds the configurable parameters for this policy.
sv_ConfigEntryName="${4}"

# Get optional parameter
# So far, this is only ever used to get Application info after a AppWillLaunch, AppDidLaunch or AppDidTerminate event.
sv_OptionalParam="${5}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_BuildVersionStampAsString}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

sf_SanitiseURI() # FileURI - make HOMEDIR substitutions to the given URI
{
  local sv_FileURI

  # Get URI
  sv_FileURI="${1}"

  if [ -n "${sv_FileURI}" ]
  then
    # if it's not a URI - make it into one
    if [ -z "$(echo "${sv_FileURI}" | grep -E '\w*://')" ]
    then
      sv_FileURI="file://${sv_FileURI}"
    fi

    # make HOMEDIR, LOCALHOME and NETWORKHOME substitutions to the given URI
    sv_FileURI="$(echo "${sv_FileURI}" | sed "s|HOMEDIR|"${LW_sv_LoggedInUserHomeDirPath}"|;s|LOCALHOME|"${LW_sv_LoggedInUserLocalHomeDirPath}"|;s|NETWORKHOME|"${LW_sv_LoggedInUserHomeNetworkDirPath}"|")"

    # make ALTHOME substitutions to the given URI
    if [ "${LW_bv_LoggedInUserHomeIsLocal}" = "true" ]
    then
      # The user home is local, so the alternative home is the network home
      sv_FileURI="$(echo "${sv_FileURI}" | sed "s|ALTHOME|"${LW_sv_LoggedInUserHomeNetworkDirPath}"|")"

    else
      # The user home is on the network, so the alternative home is the local home
      sv_FileURI="$(echo "${sv_FileURI}" | sed "s|ALTHOME|"${LW_sv_LoggedInUserLocalHomeDirPath}"|")"
 
    fi
  
    # Check if its become a null URI
    if [ "${sv_FileURI}" = "file://" ]
    then
      sv_FileURI=""
    fi
  fi
  
  echo "${sv_FileURI}"
}

Nf_RemoveEntry() # sv_ObjectFileURI sv_ObjectName - Delete all objects with the given uri/name from the sidebar
{
  local sv_ObjectFileURI
  local sv_ObjectName
  local sv_ObjectFilePath
  
  # Get object to delete
  sv_ObjectFileURI="${1}"
  sv_ObjectName="${2}"
  
  sv_ObjectFileURI="$(sf_SanitiseURI "${sv_ObjectFileURI}")"
  
  # If there is no object name (label), create one
  if [ -z "${sv_ObjectName}" ]
  then
    sv_ObjectName="$(basename "${sv_ObjectFileURI}" | sed "s|.app$||")"
  fi
    
  if [ -n "${sv_ObjectName}" ]
  then
    # Remove all existing entries
    while [ -n "$("${LW_sv_BinDirPath}"/mysides 2>/dev/null list | grep -E "^$sv_ObjectName -> ")" ]
    do
      LW_nf_logmessage "NOTE, removing ${sv_ObjectName} from side bar."
      "${LW_sv_BinDirPath}"/mysides 2>/dev/null remove "${sv_ObjectName}"
    done
  fi
}

Nf_AddEntry() # sv_ObjectFileURI sv_ObjectName - Add object with the given uri/name to the sidebar
{
  local sv_ObjectFileURI
  local sv_ObjectName
  local sv_ObjectFilePath
  
  # Get object to add
  sv_ObjectFileURI="${1}"
  sv_ObjectName="${2}"
  
  sv_ObjectFileURI="$(sf_SanitiseURI "${sv_ObjectFileURI}")"

  if [ -n "${sv_ObjectFileURI}" ]
  then
    # If there is no object name (label), create one
    if [ -z "${sv_ObjectName}" ]
    then
      sv_ObjectName="$(basename "${sv_ObjectFileURI}" | sed "s|.app$||")"
    fi
    
    if [ -n "${sv_ObjectName}" ]
    then
      # Only add the entry of it doesn't already exist
      if [ -z "$("${LW_sv_BinDirPath}"/mysides 2>/dev/null list | grep -E "^$sv_ObjectName -> ")" ]
      then
        LW_nf_logmessage "NOTE, adding ${sv_ObjectName} to side bar."
        "${LW_sv_BinDirPath}"/mysides 2>/dev/null add "${sv_ObjectName}" "${sv_ObjectFileURI}"
      fi
    fi
    
  fi
}

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if test -z "${LW_sv_LoggedInUserName}"
then
  LW_nf_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ ! -e "${LW_sv_LoggedInUserHomeDirPath}" ]
  then
    LW_nf_QuickExit "NOTE, policy aborted: home folder doesn't exist."
    
  else
    # Use mysides (see https://GitHub.com/mosen) to set up the sidebar list
    if ! test -e "${LW_sv_BinDirPath}"/mysides
    then
      LW_nf_QuickExit "NOTE, policy aborted: mysides utility doesn't exist."
    
    else
      # Remove Entries
      iv_ObjectCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Remove")"
      for (( iv_LoopCount=0; iv_LoopCount<${iv_ObjectCount}; iv_LoopCount++ ))
      do
        sv_ReqdObjectFilePath="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Remove:${iv_LoopCount}:URI")"
        sv_ReqdObjectLabel="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Remove:${iv_LoopCount}:Label")"
        Nf_RemoveEntry "${sv_ReqdObjectFilePath}" "${sv_ReqdObjectLabel}"
      done

      # Check if we are replacing 
      bv_ReplaceEntries="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Replace")"

      if [ "${bv_ReplaceEntries}" = "true" ]
      then
        # Deleting them all first is quickest
        iv_ObjectCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add")"
        for (( iv_LoopCount=0; iv_LoopCount<${iv_ObjectCount}; iv_LoopCount++ ))
        do
          sv_ReqdObjectFilePath="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add:${iv_LoopCount}:URI")"
          sv_ReqdObjectLabel="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add:${iv_LoopCount}:Label")"
          Nf_RemoveEntry "${sv_ReqdObjectFilePath}" "${sv_ReqdObjectLabel}"
        done
      fi

      # Add Entries
      iv_ObjectCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add")"
      for (( iv_LoopCount=0; iv_LoopCount<${iv_ObjectCount}; iv_LoopCount++ ))
      do
        sv_ReqdObjectFilePath="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add:${iv_LoopCount}:URI")"
        sv_ReqdObjectLabel="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_ConfigEntryName}:Config:Add:${iv_LoopCount}:Label")"
        Nf_AddEntry "${sv_ReqdObjectFilePath}" "${sv_ReqdObjectLabel}"
      done

   fi
  fi

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
