#!/bin/bash
#
# Short:    Policy script - Fix for when a users Login password does not match the keychain password
# Author:   Mark J Swift
# Version:  1.0.86
# Modified: 09-Jun-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called as follows:    
#   UserKeychainFix <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.86"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if test -z "${GLB_LoggedInUserName}"
then
  f_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ ! -e "${GLB_LoggedInUserHomeDir}" ]
  then
    f_QuickExit "NOTE, policy aborted: Home folder doesn't exist."
    
  else
    # User home exists and is available
    
    # Fix for if you hit "Continue Log In" when you are asked to update your keychain password.
    # (When your Login password does not match your keychain password)

    # Needs to be done UserAtDesktop, because the keychain isn't unlocked until after login

    # Check if Keychain is unlocked.
    if test -z "$(security 2>&1 unlock-keychain -p "" "${GLB_LoggedInUserHomeDir}/Library/Keychains/login.keychain")"
    then
      f_QuickExit "NOTE, policy aborted: Keychain is fine."
    
    else
      f_logmessage "ATTENTION, deleting keychain."

      # Keychain will not unlock, so delete known keychains and hope for the best
      # Not ideal really.
      rm -fR "${GLB_LoggedInUserHomeDir}/Library/Keychains"
      mkdir -p "${GLB_LoggedInUserHomeDir}/Library/Keychains"
   fi
  fi

fi
  
# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
srm -fR "${GLB_ThisScriptTempDir}"

# ---
