#!/bin/bash
#
# Short:    Policy script - Create symbolic links in users local home pointing to files/folders in the network home
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called as follows:    
#   UserRedirLocalHomeToNetwork <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

Nf_UndoFolderRedir() # FileRedirectList TargetHomeDir - Undo any existing home folder redirections
{
  local sv_TargetHomeDirPath
  local sv_RedirectListFilePath
  local sv_ReqdLinkEntry
  local sv_ReqdLinkFilePath

  sv_RedirectListFilePath="${1}"
  sv_TargetHomeDirPath="${2}"
    
  if test -f "${sv_RedirectListFilePath}"
  then
    # We may have symbolic links that need to be removed

    while read sv_ReqdLinkEntry
    do
      # Sanitise the Entry
      sv_ReqdLinkEntry=$(echo "/${sv_ReqdLinkEntry}" | sed "s|/[/]*|/|g")
  
      sv_ReqdLinkFilePath=$(echo "${sv_ReqdLinkEntry}" | sed "s|/$||")
      if test -n "${sv_ReqdLinkFilePath}"
      then
        if test -L "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
        then
          # There is a symbolic link where our file/folder should be
        
          if [ "${sv_ReqdLinkEntry}" != "${sv_ReqdLinkFilePath}" ]
          then
            # If the link was on a directory, re-create directory
            /bin/rm -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
            mkdir -p "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
          else
            /bin/rm -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
          fi
        fi
      fi
      
    done < "${sv_RedirectListFilePath}"
    
  fi
}

Nf_DoFolderRedir() # FileRedirectList TargetHomeDir SourceHomeDir
{
  local sv_TargetHomeDirPath
  local sv_SourceHomeDirPath
  local sv_RedirectListFilePath
  local sv_BackupDirPath
  local sv_ReqdLinkEntry
  local sv_ReqdLinkFilePath
  local sv_EnclosingDirPath
  local bv_TargetIsLocal
  local iv_StartEpoch
  local bv_GotError

  sv_RedirectListFilePath="${1}"
  sv_TargetHomeDirPath="${2}"    # Where the link files will be created
  sv_SourceHomeDirPath="${3}"    # Where the files/folders are that the links will be pointing to to

  # Take a note when this function started
  iv_StartEpoch=$(date -u "+%s")
  
  if test -f "${sv_RedirectListFilePath}"
  then
  
    # Decide whether the target is on the local drive
    if test -n "$(stat -f "%Sd" "${sv_TargetHomeDirPath}" | grep "^disk")"
    then
      bv_TargetIsLocal="true"
    else
      bv_TargetIsLocal="false"
    fi

    # Backup location for existing files/folders that might be replaced by a link
    sv_BackupDirPath="${sv_TargetHomeDirPath}/Backup/"$(date -r ${iv_StartEpoch} '+%Y-%m-%d_%H-%M-%S')

    # Read entries from file
    while read sv_ReqdLinkEntry
    do
      bv_GotError="false"

      # Sanitise the Entry
      sv_ReqdLinkEntry=$(echo "/${sv_ReqdLinkEntry}" | sed "s|/[/]*|/|g")
      
      sv_ReqdLinkFilePath=$(echo "${sv_ReqdLinkEntry}" | sed "s|/$||")
      if test -n "${sv_ReqdLinkFilePath}"
      then
      
        # Make sure there is a target enclosing folder to store the symbolic link
        sv_EnclosingDirPath="$(dirname "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}")"
        /bin/mkdir -p "${sv_EnclosingDirPath}"
      
        # Make sure we have a source folder or source file parent folder
        if [ "${sv_ReqdLinkEntry}" != "${sv_ReqdLinkFilePath}" ]
        then
          # We are linking to a directory - so make sure it exists
          /bin/mkdir -p "${sv_SourceHomeDirPath}${sv_ReqdLinkFilePath}"
          if [ "$?" != "0" ]
          then
            LW_nf_logmessage "ATTENTION, error creating folder '${sv_SourceHomeDirPath}${sv_ReqdLinkFilePath}'"
            bv_GotError="true"
          fi
        else
          # We are linking to a file - so make sure the parent folder exists
          sv_EnclosingDirPath="$(dirname "${sv_SourceHomeDirPath}${sv_ReqdLinkFilePath}")"
          /bin/mkdir -p "${sv_EnclosingDirPath}"
          if [ "$?" != "0" ]
          then
            LW_nf_logmessage "ATTENTION, error creating folder '${sv_EnclosingDirPath}'"
            bv_GotError="true"
          fi
        fi
      
        # If there are errors at source, delete any existing link at target
        if [ "${bv_GotError}" = "true" ]
        then
          if test -L "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
          then
            rm -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
          fi
        
        else
        
          # Check if a file or folder already exists at the target (where the link is going to be stored)
          if test -e "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
          then
            # Delete symbolic links
            if test -L "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
            then
              rm -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
            else
              # Back up everything else
              if test -d "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
              then
                # If the existing folder at the target is local, remove any ACLs that might stop us doing our stuff
                if [ "${bv_TargetIsLocal}" = "true" ]
                then
                  /bin/chmod -RN "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
                fi
                # Check if existing folder is empty - and backup if necessary
                if test -z "$(ls -A1 "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}" | grep -Ev "^.DS_Store$|^.localized$")"
                then
                  /bin/rm -fR "${sv_TargetHomeDirPath}/${sv_ReqdLinkFilePath}"
                else
                  # Make sure there is a target enclosing folder to backup the folder
                  sv_EnclosingDirPath="$(dirname "${sv_BackupDirPath}${sv_ReqdLinkFilePath}")"
                  /bin/mkdir -p "${sv_EnclosingDirPath}"
                  # Move (back up) existing folder at target
                  /bin/mv -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}" "${sv_EnclosingDirPath}/"
                fi
              else
                # If the existing file at the target is local, remove any ACLs that might stop us doing our stuff
                if [ "${bv_TargetIsLocal}" = "true" ]
                then
                  /bin/chmod -N "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
                fi
                # Make sure there is a target enclosing folder to backup the file
                sv_EnclosingDirPath="$(dirname "${sv_BackupDirPath}${sv_ReqdLinkFilePath}")"
                /bin/mkdir -p "${sv_EnclosingDirPath}"
                # Move (back up) existing file at target
                /bin/mv -f "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}" "${sv_EnclosingDirPath}/"
              fi
            fi
          fi
          
          # Create link - source file/folder -to- target link
          /bin/ln -sf "${sv_SourceHomeDirPath}${sv_ReqdLinkFilePath}" "${sv_TargetHomeDirPath}${sv_ReqdLinkFilePath}"
        fi
      fi
    done < "${sv_RedirectListFilePath}"
    
  fi
}

Nf_RemoveAllLocalRedirs()
{
  if test -s "${LW_sv_LoggedInUserLocalHomeDirPath}/.FolderRedir.txt"
  then
    Nf_UndoFolderRedir "${LW_sv_LoggedInUserLocalHomeDirPath}/.FolderRedir.txt" "${LW_sv_LoggedInUserLocalHomeDirPath}"
  fi

  if [ "${LW_bv_LoggedInUserHomeIsLocal}" = "true" ]
  then
    # Check if the Desktop was linked/unlinked
    if test -n "$(printf "$(cat "${LW_sv_LoggedInUserLocalHomeDirPath}/.FolderRedir.txt")" | grep -E "^/Desktop/$")"
    then
      # Kill the Finder (Refreshes Desktop)
      LW_nf_logmessage "NOTE, folder redirections removed and Finder reloaded"
      pkill -U ${LW_iv_ThisUserID} Finder
    fi
  fi

  rm -f "${LW_sv_LoggedInUserLocalHomeDirPath}/.FolderRedir.txt"
}

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if test -z "${LW_sv_LoggedInUserName}"
then
  LW_nf_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ ! -e "${LW_sv_LoggedInUserHomeDirPath}" ]
  then
    LW_nf_QuickExit "NOTE, policy aborted: Home folder doesn't exist."
    
  else
    # The user home dir exists, so far so good

    if [ "${LW_bv_LoggedInUserIsLocal}" = "true" ]
    then
      # We are a local account
      
      Nf_RemoveAllLocalRedirs
      LW_nf_QuickExit "NOTE, policy aborted: User account is local."

    else
      # We are a network account
    
      if [ "${LW_bv_LoggedInUserHomeIsLocal}" = "false" ]
      then
        # The user home is on the network

        Nf_RemoveAllLocalRedirs
        LW_nf_QuickExit "NOTE, policy aborted: Home folder is on the network."
      
      else
        # The user home is local

        if [ -z "${LW_sv_LoggedInUserHomeNetworkDirPath}" ]
        then
          # The original home network share is unavailable

          # For some reason, the network home didnt mount - so remove any existing redirections
          Nf_RemoveAllLocalRedirs
          LW_nf_ShowNotification "DONT PANIC" "Your network share is not available at present. Try Rebooting."
          LW_nf_QuickExit "ERROR, policy aborted: Network share is unavailable."
 
        else
          # The original home network share is mounted and available

          if [ ! -e "${LW_sv_LoggedInUserHomeNetworkDirPath}" ]
          then
            # The original home network folder is unavailable
            
            # For some reason, the network home folder is unavailable - so remove any existing redirections
            Nf_RemoveAllLocalRedirs
            LW_nf_QuickExit "ERROR, policy aborted: Network home is unavailable."
            
          else
            # The original home network folder is available

            bv_PolicyExecuted="false"
    
            if [ "${LW_bv_LoggedInUserIsMobile}" = "true" ]
            then
              # We are a mobile network account
        
              # we dont want redirections as in any case, they would only work on-network
              Nf_RemoveAllLocalRedirs
              LW_nf_logmessage "NOTE, User account is mobile."
        
            else
              # We are a normal (non-mobile) network account

              # There shouldn't be any folder redirections on the network drive
              # If there are, these may have been left when swapping between "Network Homes" and "Force local homes".
              if test -s "${LW_sv_LoggedInUserHomeNetworkDirPath}/.FolderRedir.txt"
              then
                Nf_UndoFolderRedir "${LW_sv_LoggedInUserHomeNetworkDirPath}/.FolderRedir.txt" "${LW_sv_LoggedInUserHomeNetworkDirPath}"
              fi
              rm -f "${LW_sv_LoggedInUserHomeNetworkDirPath}/.FolderRedir.txt"

              # Make sure the link list exists
              touch "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"

              # Check the existing link list
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt"
              touch "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt"
              while read sv_ReqdLinkEntry
              do
                # Sanitise the Entry
                sv_ReqdLinkEntry=$(echo "/${sv_ReqdLinkEntry}" | sed "s|/[/]*|/|g")
                sv_ReqdLinkFilePath=$(echo "${sv_ReqdLinkEntry}" | sed "s|/$||")
                if test -n "${sv_ReqdLinkFilePath}"
                then
                  if test -L "${LW_sv_LoggedInUserLocalHomeDirPath}${sv_ReqdLinkFilePath}"
                  then
                    echo "${sv_ReqdLinkEntry}" >>"${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt"
                  fi
                fi
              done < "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
            
              # Create the required link list
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
              touch "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
              iv_ObjectCount="$(LW_if_GetPlistArraySize "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path")"
              for (( iv_LoopCount=0; iv_LoopCount<${iv_ObjectCount}; iv_LoopCount++ ))
              do
                sv_ReqdLinkEntry="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:Path:${iv_LoopCount}")"
                sv_ReqdLinkEntry=$(echo "/${sv_ReqdLinkEntry}" | sed "s|/[/]*|/|g")
                sv_ReqdLinkFilePath=$(echo "${sv_ReqdLinkEntry}" | sed "s|/$||")
                if test -n "${sv_ReqdLinkFilePath}"
                then
                  echo "${sv_ReqdLinkEntry}" >>"${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
                fi
              done
      
              # Find out which folders we need to check for links/unlinks
              echo "$(cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt" ; cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt" )" | sort -u > "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Check.txt"

              # Find out which folders we need to unlink (if we ever change the link list)
              echo "$(cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt" ; cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Check.txt" )" | sort | uniq -u > "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Unlink.txt"

              # Find out which folders we need to link
              echo "$(cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt" ; cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Check.txt" )" | sort | uniq -u > "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Link.txt"

              # Link files (did use .FolderRedir-Link.txt, but the home folder might change)
              if test -s "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
              then
                LW_nf_logmessage "ATTENTION, linking folders."
                bv_PolicyExecuted="true"
                Nf_DoFolderRedir  "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt" "${LW_sv_LoggedInUserHomeDirPath}" "${LW_sv_LoggedInUserHomeNetworkDirPath}"
              fi

              # Unlink files
              if test -s "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Unlink.txt"
              then
                LW_nf_logmessage "ATTENTION, unlinking folders."
                bv_PolicyExecuted="true"
                Nf_UndoFolderRedir "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Unlink.txt" "${LW_sv_LoggedInUserHomeDirPath}"
              fi

              # Check if the Desktop was linked/unlinked
              if test -n "$(printf "$(cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Unlink.txt";cat "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Link.txt")" | grep -E "^/Desktop/$")"
              then
                # Kill the Finder (Refreshes Desktop)
                LW_nf_logmessage "ATTENTION, folders redirected and Finder reloaded."
                pkill -U ${LW_iv_ThisUserID} Finder
              fi

              # Delete temporary files
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Old.txt"
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Check.txt"
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Unlink.txt"
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir-Link.txt"

              # Delete the link file if it is empty
              if ! test -s "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
              then
                # Link list file is empty
                rm -f "${LW_sv_LoggedInUserHomeDirPath}/.FolderRedir.txt"
              fi
              
            fi
          
            # Create a link to the user home root (affects all network accounts - mobile too)
            sv_NetworkHomeLinkName="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:NetworkHomeLinkName")"
            if test -n "${sv_NetworkHomeLinkName}"
            then
              LW_nf_logmessage "ATTENTION, creating link to network home."
              bv_PolicyExecuted="true"
              rm -f "${LW_sv_LoggedInUserHomeDirPath}/${sv_NetworkHomeLinkName}"
              /bin/ln -sf "${LW_sv_LoggedInUserHomeNetworkDirPath}" "${LW_sv_LoggedInUserHomeDirPath}/${sv_NetworkHomeLinkName}"
            fi
          
          fi
        fi
      fi
    fi
  fi

fi

# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
