#!/bin/bash
#
# Short:    Policy script - Disable Spotlight on a users network home
# Author:   Mark J Swift
# Version:  1.0.86
# Modified: 09-Jun-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called as follows:    
#   UserNoSpotlightOnNetHome <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

LCL_ScriptVersion="1.0.86"

if [ $# -eq 0 ]
then
  echo "${LCL_ScriptVersion}"
  exit 0
fi

# ---

# Take a note when this script started
LCL_MyStartEpoch=$(date -u "+%s")

# Get the config directory
LCL_ConfigDir="${1}"
if test -z "${LCL_ConfigDir}"
then
  # We need something to work with
  exit 0
fi

# Get event History
LCL_EventHistory="${2}"

# Get event that triggered this policy
LCL_EventName="$(echo ${LCL_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${LCL_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
GLB_LoggedInUserName="${3}"

# Get optional parameter
LCL_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${GLB_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Filename of this script)
LCL_PolicyName="${GLB_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
f_logmessage "NOTE, policy triggered: '${LCL_PolicyName}' ${LCL_OptionalParam} triggered by event '${LCL_EventHistory}' as user '${GLB_ThisUserName}' "

if test -z "${GLB_LoggedInUserName}"
then
  f_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else    
  if [ "${GLB_LoggedInUserIsLocal}" = "true" ]
  then
    f_QuickExit "NOTE, policy aborted: User account is local."
    
  else
    # We are a network account
    
    if [ -z "${GLB_LoggedInUserHomeNetworkDir}" ]
    then
      f_QuickExit "NOTE, policy aborted: Network home is unavailable."

    else
      # The original home network share is mounted and available

      if [ ! -e "${GLB_LoggedInUserHomeNetworkDir}" ]
      then
        f_QuickExit "NOTE, policy aborted: Network home unavailable."
        
      else
        # The original home network folder exists and is available
    
        if [ -e "${GLB_LoggedInUserHomeNetworkDir}/.metadata_never_index" ]
        then
          f_QuickExit "NOTE, policy aborted: Spotlight already disabled."

        else
          f_logmessage "ATTENTION, disabling Spotlight on network home."
  
          # tell the system never to index the folder
          touch "${GLB_LoggedInUserHomeNetworkDir}/.metadata_never_index"

          # switch off spotlight for folder
          mdutil -i off "${GLB_LoggedInUserHomeNetworkDir}"
        fi
    
        if [ -d "${GLB_LoggedInUserHomeNetworkDir}/.Spotlight-V100" ]
        then
          # remove redundant indexing data
          rm -fR "${GLB_LoggedInUserHomeNetworkDir}/.Spotlight-V100"
        fi

      fi
    fi
  fi

fi

# Trigger an event
f_TriggerEvent "${LCL_EventHistory}" "${LCL_PolicyName}" "${LCL_OptionalParam}"

# Remove temporary files
srm -fR "${GLB_ThisScriptTempDir}"

# ---
