#!/bin/bash
#
# Short:    Policy script - Set Desktop wallpaper for user
# Author:   Mark J Swift
# Version:  1.0.92
# Modified: 21-Jul-2016
#
# Triggered by the following events:
#   UserAtDesktop (as user)
#
# Called as follows:
#   UserDesktopWallpaperURI <ConfigDir> <EventHistory> <LoggedInUser> <OptionalParam>

# ---

sv_CodeVersion="1.0.92"

if [ $# -eq 0 ]
then
  echo "${sv_CodeVersion}"
  exit 0
fi

# ---

# Get the config directory
sv_ConfigDirPath="${1}"
if test -z "${sv_ConfigDirPath}"
then
  # We need something to work with
  exit 0
fi

# Get event History
sv_EventHistory="${2}"

# Get event that triggered this policy
sv_EventName="$(echo ${sv_EventHistory} | tr ":" "\n" | tail -n 1)"
if test -z "${sv_EventName}"
then
  # We need something to work with
  exit 0
fi

# Get optional user
LW_sv_LoggedInUserName="${3}"

# Get optional parameter
sv_OptionalParam="${4}"

# ---

# Load the library, only if it is not already loaded
if test -z "${LW_sv_LabWardenVersion}"
then
  . /usr/local/LabWarden/lib/CommonLib
fi

# ---

# Get policy name (Name of this script)
sv_PolicyName="${LW_sv_ThisScriptName}"

# ---

# Execute the Policy

# Take a note of the Policy call
LW_nf_logmessage "NOTE, policy triggered: '${sv_PolicyName}' ${sv_OptionalParam} triggered by event '${sv_EventHistory}' as user '${LW_sv_ThisUserName}' "

if test -z "${LW_sv_LoggedInUserName}"
then
  LW_nf_QuickExit "NOTE, policy aborted: No-one is logged in."
  
else
  if [ ! -e "${LW_sv_LoggedInUserHomeDirPath}" ]
  then
    LW_nf_QuickExit "NOTE, policy aborted: Home folder doesn't exist."

  else
    # User home exists and is available

    sv_DesktopWallpaperURI="$(LW_sf_GetPlistProperty "${sv_ConfigDirPath}/LabWarden.plist" ":${sv_PolicyName}:Config:DesktopWallpaperURI")"
    if test -z "${sv_DesktopWallpaperURI}"
    then
      LW_nf_QuickExit "NOTE, policy aborted: No desktop URI defined."

    else
      sv_DesktopWallpaperFilePath=$(LW_sf_ResolveFilename "${sv_DesktopWallpaperURI}")
      if test -z "${sv_DesktopWallpaperFilePath}"
      then
        LW_nf_QuickExit "NOTE, policy aborted: Desktop URI '${sv_DesktopWallpaperURI}' is not resolvable."

      else
        LW_nf_logmessage "ATTENTION, setting Desktop Wallpaper"
        osascript -e "tell application \"System Events\" to set picture of every desktop to \"${sv_DesktopWallpaperFilePath}\""
      fi
    fi
  
  fi

fi
  
# Trigger an event
LW_nf_TriggerEvent "${sv_EventHistory}" "${sv_PolicyName}" "${sv_OptionalParam}"

# Remove temporary files
rm -fPR "${LW_sv_ThisScriptTempDirPath}"

# ---
